/****** Script for SelectTopNRows command from SSMS  ******/
-- 10.254.195.201

-- TRUNCATE TABLE [INFORMES3].dbo.INSTOCK_CARNES_SURTIDO

-- INSERT INTO [INFORMES3].dbo.INSTOCK_CARNES_SURTIDO

SELECT 
	--*,
	D.ORG_LVL_NUMBER COD_LOCAL,
	D.ORG_NAME_FULL NOM_LOCAL,
	D.TBL_CODE_SYST REPO,
	D.METOD_ABAST ABAST,
	D.PRD_LVL_NUMBER SKU,
	D.MIN_PRES_STOCK MIN_PRES_STOCK,
	D.PRD_NAME_FULL SKU_DESC,
	M.MARCA MARCA,
	LEFT(M.DIVISION, 3) DIVISION,
	RIGHT(M.DIVISION, LEN(M.DIVISION)-6) NOM_DIVISION,
	LEFT(M.DEPARTAMENTO, 5) DEPARTAMENTO,
	RIGHT(M.DEPARTAMENTO, LEN(M.DEPARTAMENTO)-5) DESC_DEPTO,
	LEFT(M.SUBDEPARTAMENTO, 7) [SUB-DEPTO],
	RIGHT(M.SUBDEPARTAMENTO, LEN(M.SUBDEPARTAMENTO)-7) [DESC_SUB-DEPTO],
	p.[COD_PROV],
	p.[NOM_PROVEEDOR]
FROM [192.168.148.177].[DATOS_MAESTROS].[dbo].[SURTIDO_LOCAL] D
	LEFT JOIN [192.168.148.177].RepNonFood.dbo.MAESTRA_SKU M ON d.PRD_LVL_NUMBER = M.SKU
	LEFT JOIN [192.168.148.177].RepNonFood.dbo.MAESTRA_PROVEEDORES P ON d.PRD_LVL_NUMBER = p.PRODUCTO_SKU
WHERE m.CLASE like '%J03%'