INSERT INTO [INFORMES3].[dbo].[CE_INSTOCK_EVOLUTIVO_RESUMEN]
           ([NOM_LOCAL]
           ,[COD_LOCAL]
           ,[DIVISION]
           ,[DEPARTAMENTO]
           ,[SUBDEP]
           ,[CLASE]
           ,[NOM_PROV]
           ,[RUT]
           ,[NUM_OH_VALORIZADO]
           ,[NUM_VTA_SEM_X_PERFIL]
           ,[VTA_PERDIDA_VP]
           ,[CANTIDAD_SKUS]
           ,[SEMANA])

SELECT
	A.NOM_LOCAL,
	A.COD_LOCAL,
	A.DIVISION,
	A.DEPARTAMENTO,
	A.SUBDEP,
	A.CLASE,
	A.NOM_PROV,
	A.RUT,
	SUM(A.NUM_OH_VALORIZADO) AS NUM_OH_VALORIZADO,
	SUM(A.NUM_VTA_SEM_X_PERFIL) AS NUM_VTA_SEM_X_PERFIL,
	SUM(A.VTA_PERDIDA_VP) AS VTA_PERDIDA_VP,
	SUM(A.CANTIDAD_SKUS) AS CANTIDAD_SKUS,
	A.SEMANA
FROM [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA_HISTORIA] AS A
WHERE 
	((A.DIVISION IN ('J01 - PGC COMESTIBLE', 'J02 - PGC NO COMESTIBLE', 'J05 - FLC'))
	AND (A.SIS_REPOSICION IN ('Reposicion x ASR', 'Informar a ASR')) 
	AND (A.IND_SURTIDO = 1) 
	AND A.SEMANA=(SELECT semana from [INFORMES3].dbo.DHW_MES_GC WHERE CONVERT(DATE,FECHA)=CONVERT(DATE,GETDATE()-7))) 
	OR ((A.DIVISION IN ('J06 - PANADERIA Y PASTELERIA', 'J07 - PLATOS PREPARADOS')) 
	AND (A.SIS_REPOSICION IN ('Reposicion x ASR'))
	AND (A.IND_SURTIDO = 1) 
	AND A.SEMANA=(SELECT semana from [INFORMES3].dbo.DHW_MES_GC WHERE CONVERT(DATE,FECHA)=CONVERT(DATE,GETDATE()-7)))
GROUP BY 
	A.NOM_LOCAL,
	A.COD_LOCAL,
	A.DIVISION,
	A.DEPARTAMENTO,
	A.SUBDEP,
	A.CLASE,
	A.NOM_PROV,
	A.RUT,
	A.SEMANA


--==========================================================================

INSERT INTO [INFORMES3].[dbo].[CE_INSTOCK_EVOLUTIVO_RESUMEN_BINARIO]

SELECT
	NOM_LOCAL,
	COD_LOCAL,
	DIVISION,
	DEPARTAMENTO,
	EDLP, SUBDEP,
	CLASE,
	NOM_PROV,
	RUT,
	SEMANA,SUM(BINARIO) BINARIO,
	SUM(CANTIDAD) CANTIDAD
--INTO [INFORMES3].[dbo].[CE_INSTOCK_EVOLUTIVO_RESUMEN_BINARIO_EDLP]
FROM (
	SELECT 
		CASE WHEN B.SKU IS NOT NULL THEN 'EDLP' ELSE 'NO EDLP' END EDLP, 
		A.NOM_LOCAL, 
		A.COD_LOCAL, 
		A.DIVISION, 
		A.DEPARTAMENTO, 
		A.SUBDEP, 
		A.CLASE, 
		A.NOM_PROV, 
		A.RUT,
		CASE 
			WHEN [NUM_OH_VALORIZADO] = 0 AND  [NUM_VTA_SEM_X_PERFIL] = 0 THEN 0
			WHEN [NUM_VTA_SEM_X_PERFIL] = 0 AND [NUM_OH_VALORIZADO] > 0 THEN 1
			WHEN [NUM_OH_VALORIZADO] < [NUM_VTA_SEM_X_PERFIL] THEN 0
			ELSE 1 
		END AS [BINARIO],
		A.CANTIDAD_SKUS CANTIDAD, 
		A.SEMANA
	FROM [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA_HISTORIA] AS A
	LEFT JOIN [INSTOCK_OPT].[dbo].[SKU_EDLP] B 
		ON B.SKU = A.SKU
	WHERE 
		((A.DIVISION IN ('J01 - PGC COMESTIBLE', 'J02 - PGC NO COMESTIBLE', 'J05 - FLC'))
		AND (A.SIS_REPOSICION IN ('Reposicion x ASR', 'Informar a ASR')) 
		AND (A.IND_SURTIDO = 1) 
		AND A.SEMANA = (SELECT semana from [INFORMES3].dbo.DHW_MES_GC WHERE CONVERT(DATE,FECHA)=CONVERT(DATE,GETDATE()-7))) 
		OR ((A.DIVISION IN ('J06 - PANADERIA Y PASTELERIA', 'J07 - PLATOS PREPARADOS')) 
		AND (A.SIS_REPOSICION IN ('Reposicion x ASR')) 
		AND (A.IND_SURTIDO = 1)
		AND A.SEMANA = (SELECT semana FROM [INFORMES3].dbo.DHW_MES_GC WHERE CONVERT(DATE,FECHA)=CONVERT(DATE,GETDATE()-7)))
) T
GROUP BY 
	NOM_LOCAL,
	COD_LOCAL,
	DIVISION,
	DEPARTAMENTO,
	SUBDEP,
	CLASE,
	NOM_PROV,
	RUT,
	SEMANA,
	EDLP

