-- TRUNCATE TABLE [INFORMES3].[dbo].[CE_INSTOCK_EVOLUTIVO_RESUMEN_LIGHT]

-- INSERT INTO [INFORMES3].[dbo].[CE_INSTOCK_EVOLUTIVO_RESUMEN_LIGHT]

SELECT DISTINCT 
	EDLP
	,[NOM_LOCAL]
	,[COD_LOCAL]
	,[DIVISION]
	,[DEPARTAMENTO]
	,[SUBDEP]
	,[CLASE]
	,[NOM_PROV]
	,[RUT]
	,[NUM_OH_VALORIZADO]
	,[NUM_VTA_SEM_X_PERFIL]
	,[VTA_PERDIDA_VP]
	,[CANTIDAD_SKUS]
	,[SEMANA]
--INTO [INFORMES3].[dbo].[CE_INSTOCK_EVOLUTIVO_RESUMEN_LIGHT]
FROM [INFORMES3].[dbo].[CE_INSTOCK_EVOLUTIVO_RESUMEN]
WHERE SEMANA IN (
	SELECT DISTINCT TOP 15 SEMANA
	FROM [INFORMES3].[dbo].[CE_INSTOCK_EVOLUTIVO_RESUMEN]
	ORDER BY 1 DESC
)