SELECT *
FROM INSTOCK_OPT.dbo.INSTOCK_MIN_PRE B
LEFT JOIN (
	SELECT 
		[SKU ID],
		[Store ID],
		COUNT([SKU ID]) CUENTA
	FROM INSTOCK_OPT.dbo.INSTOCK_MIN_PRE
	GROUP BY
		[SKU ID],
		[Store ID]
	HAVING COUNT([SKU ID]) > 1
) D
	ON D.[SKU ID] = B.[SKU ID] AND D.[Store ID] = B.[Store ID]
WHERE D.CUENTA > 1