-- INSERT INTO [INFORMES3].[dbo].[INSTOCK_SEMANAL_ABC_RESUMEN] (
-- 	[CLASE_A]
-- 	,[CLASE_B]
-- 	,[CLASE_C]
-- 	,[NUEVA_CLASE_A]
-- 	,[NUEVA_CLASE_B]
-- 	,[NUEVA_CLASE_C]
-- 	,[SEMANA]
-- )


SELECT 
	0 AS CLASE_A
	,0 AS CLASE_B
	,0 AS CLASE_C
	,NUEVA_CLASE_A
	,NUEVA_CLASE_B
	,NUEVA_CLASE_C
	,SEMANA
FROM [INFORMES3].[dbo].[View_INSTOCK_SEMANA_NUEVO_ABC]
PIVOT(
	SUM(INSTOCK) FOR [CUADRO_RESUMEN] IN (
		[NUEVA_CLASE_A],
		[NUEVA_CLASE_B],
		[NUEVA_CLASE_C]
	)
) pvtable





