SELECT
	i.SUBDEP,
	I.CLASE,
	I.SUBCLASE,
	i.METOD_ABAST,
	I.COD_LOCAL,
	I.NOM_LOCAL,
	ISNULL(SUM(P.PRECIO_VIGENTE * I.UN_INV_DISP_HOY), 0) OH_VALORIZADO,
	CASE
		WHEN SUM(P.PRECIO_VIGENTE * I.UN_INV_DISP_HOY) < 0 THEN 0
		WHEN SUM(P.PRECIO_VIGENTE * I.UN_INV_DISP_HOY) > SUM(I.NUM_VTA_SEM_X_PERFIL) THEN SUM(I.NUM_VTA_SEM_X_PERFIL)
		ELSE ISNULL(SUM(P.PRECIO_VIGENTE * I.UN_INV_DISP_HOY),0)
	END NUM_OH_VALORIZADO_2,
	ISNULL(SUM(I.NUM_OH_VALORIZADO), 0) NUM_OH_VALORIZADO,
	ISNULL(SUM(I.NUM_VTA_SEM_X_PERFIL),0) NUM_VTA_SEM_X_PERFIL,
	ISNULL(SUM(I.UN_INV_DISP_HOY_REAL),0) UN_INV_DISP_HOY_REAL,
	ISNULL(SUM(I.UN_INV_DISP_HOY),0) UN_INV_DISP_HOY,
	ISNULL(SUM(I.CANTIDAD_SKUS),0) CANTIDAD_SKUS,
	ISNULL(SUM(I.DEMANDA_SEMANAL),0) DEMANDA_SEMANAL,
	I.FECHA_ACTUALIZ,
	ISNULL(A.[GRUPO ], '') CLASE_A
FROM (

	SELECT I.*,
		S.UN_INV_DISP_HOY UN_INV_DISP_HOY_REAL,
		CASE WHEN S.UN_INV_DISP_HOY < 0 THEN 0 ELSE S.UN_INV_DISP_HOY END UN_INV_DISP_HOY
	FROM INFORMES3.dbo.CE_INSTOCK_FYV I
	LEFT JOIN INFORMES3.dbo.STOCK_HOY_CIA S
		ON I.SKU = S.SKU
		AND I.COD_LOCAL = S.COD_LOCAL

) I
LEFT JOIN INFORMES3.dbo.INSTOCK_FFVV_PRECIO_VIGENTE P
	ON I.SKU = P.SKU
	AND I.COD_LOCAL = P.COD_LOCAL
LEFT JOIN [INFORMES3].[dbo].[FFVV_SKUS_CLASE_A] A
	ON A.SKU = I.SKU
WHERE
	I.SUBDEP LIKE '%J04%'
	AND I.COD_LOCAL NOT IN (SELECT * FROM INFORMES3.dbo.TIENDAS_ASENTADAS)
GROUP BY
	I.SUBDEP,
	I.CLASE,
	I.SUBCLASE,
	I.FECHA_ACTUALIZ,
	I.METOD_ABAST,
	I.COD_LOCAL,
	I.NOM_LOCAL,
	A.[GRUPO ]