SELECT TOP 12
	COMPAÑIA,
	TOP500,
	TOP2100,
	MES AS FECHA,
	AÑOMES
FROM (

	SELECT TOP 12 *
	FROM (

		SELECT 
			FECHA AS AÑOMES,
			[INSTOCK COMPAÑIA] COMPAÑIA,
			TOP500,
			TOP2100
		FROM (

			SELECT 
				[CUADRO RESUMEN],
				INSTOCK_G,
				FECHA
			FROM [INFORMES3].[dbo].[CE_INSTOCK_G_COMPAÑIA_MES]

		) AS I
		PIVOT (
			SUM(INSTOCK_G)
			FOR [CUADRO RESUMEN] IN ([INSTOCK COMPAÑIA], TOP500, TOP2100)
		) AS PVT

	) AS I
	LEFT JOIN [INFORMES3].[dbo].[MES] M
		ON I.AÑOMES % 100 = M.id
	ORDER BY AÑOMES DESC

) AS I
ORDER BY AÑOMES ASC