SELECT DISTINCT
	T.SKU,
	T.NOM_PRODUCTO,
	T.DIVISION,
	T.DEPARTAMENTO,
	T.SUBDEP,
	T.CLASE,
	T.SUBCLASE,
	T.NOM_PROV
FROM [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA] T
WHERE 
	T.TOP_500 IS NOT NULL
	AND T.COD_LOCAL = 301