USE [INFORMES3]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:			Sebastian Cornejo
-- Create date: 2019/11/12
-- Description: Datos para Grafico Instock Evolutivo Semanal
-- EXECCT [INFORMES3].[dbo].[SP_GRAFICO_INSTOCK_SEMANA_v2]
-- =============================================
CREATE PROCEDURE [dbo].[SP_GRAFICO_INSTOCK_SEMANA_v2]

AS

BEGIN

	SELECT *
	FROM (

		SELECT
			'TOP500' AS CUADRO_RESUMEN,
			SEMANA,
			CONVERT(NUMERIC(12,1),SUM([NUM_OH_VALORIZADO])/NULLIF(SUM([NUM_VTA_SEM_X_PERFIL]),0)*100) AS INSTOCK
		FROM [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA_HISTORIA]
		WHERE 
			TOP_500='TOP500' 
			AND SEMANA BETWEEN (DATEPART(WW, GETDATE())-4+DATEPART(YYYY, GETDATE())*100) AND (DATEPART(WW, GETDATE())+DATEPART(YYYY, GETDATE())*100)
			AND COD_LOCAL NOT IN (209, 203, 205, 202, 206, 105, 129, 107, 207)
		GROUP BY SEMANA

		UNION ALL

		SELECT 
			'TOP2100' AS CUADRO_RESUMEN,
			SEMANA,
			CONVERT(NUMERIC(12,1),SUM([NUM_OH_VALORIZADO])/NULLIF(SUM([NUM_VTA_SEM_X_PERFIL]),0)*100) AS INSTOCK
		FROM  [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA_HISTORIA]
		WHERE
			TOP_2100='TOP2100' 
			AND SEMANA BETWEEN (DATEPART(WW, GETDATE())-4+DATEPART(YYYY, GETDATE())*100) AND (DATEPART(WW, GETDATE())+DATEPART(YYYY, GETDATE())*100)
			AND COD_LOCAL NOT IN (209, 203, 205, 202, 206, 105, 129, 107, 207)
		GROUP BY SEMANA

		UNION ALL

		SELECT 
			'CIA' AS CUADRO_RESUMEN,
			SEMANA,
			CONVERT(NUMERIC(12,1),SUM([NUM_OH_VALORIZADO])/NULLIF(SUM([NUM_VTA_SEM_X_PERFIL]),0)*100) AS INSTOCK
		FROM  [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA_HISTORIA]
		WHERE 
			SEMANA BETWEEN (DATEPART(WW, GETDATE())-4+DATEPART(YYYY, GETDATE())*100) AND (DATEPART(WW, GETDATE())+DATEPART(YYYY, GETDATE())*100)
			AND COD_LOCAL NOT IN (209, 203, 205, 202, 206, 105, 129, 107, 207)
		group by SEMANA

	) AS T
	PIVOT (
		SUM(T.INSTOCK)
		FOR T.CUADRO_RESUMEN IN (CIA, TOP500, TOP2100)
	) AS pivotTable

END
