SELECT 
	SUM(AA.INSTOCK_G_C)  AS INSTOCK_G_C
	,SUM(AA.INSTOCK_G_T5) AS INSTOCK_G_T5
	,SUM(AA.INSTOCK_G_T2) AS INSTOCK_G_T2
	,AA.FECHA
	,AA.ROW_FECHA
FROM (
	SELECT
		[INSTOCK_G] AS INSTOCK_G_C
		,0 AS INSTOCK_G_T5
		,0 AS INSTOCK_G_T2
		,[INSTOCK]
		,CASE
			WHEN [FECHA] =201901 THEN 'ENERO'
			WHEN [FECHA] =201902 THEN 'FEBRERO'
			WHEN [FECHA] =201903 THEN 'MARZO'
			WHEN [FECHA] =201904 THEN 'ABRIL'
			WHEN [FECHA] =201905 THEN 'MAYO'
			WHEN [FECHA] =201906 THEN 'JUNIO'
			WHEN [FECHA] =201907 THEN 'JULIO'
			WHEN [FECHA] =201908 THEN 'AGOSTO'
			WHEN [FECHA] =201909 THEN 'SEPTIEMBRE'
			WHEN [FECHA] =201910 THEN 'OCTUBRE'
			WHEN [FECHA] =201911 THEN 'NOVIEMBRE'
		END AS FECHA
		--,FECHA
		,ROW_NUMBER() OVER(ORDER BY [FECHA] ASC ) AS ROW_FECHA
  FROM [INFORMES3].[dbo].[CE_INSTOCK_G_COMPAÑIA_MES]
  WHERE [Cuadro Resumen] ='instock Compañia'

	UNION ALL

  SELECT  
		0  AS INSTOCK_G_C  
    ,[INSTOCK_G]  AS INSTOCK_G_T5
    ,0  AS INSTOCK_G_T2
    ,[INSTOCK]
    ,CASE
			WHEN [FECHA] =201901 THEN 'ENERO'
			WHEN [FECHA] =201902 THEN 'FEBRERO'
			WHEN [FECHA] =201903 THEN 'MARZO'
			WHEN [FECHA] =201904 THEN 'ABRIL'
			WHEN [FECHA] =201905 THEN 'MAYO'
			WHEN [FECHA] =201906 THEN 'JUNIO'
			WHEN [FECHA] =201907 THEN 'JULIO'
			WHEN [FECHA] =201908 THEN 'AGOSTO'
			WHEN [FECHA] =201909 THEN 'SEPTIEMBRE'
			WHEN [FECHA] =201910 THEN 'OCTUBRE'
			WHEN [FECHA] =201911 THEN 'NOVIEMBRE'
    END AS FECHA
		--,FECHA
    ,ROW_NUMBER() OVER(ORDER BY [FECHA] ASC ) AS ROW_FECHA
  FROM [INFORMES3].[dbo].[CE_INSTOCK_G_COMPAÑIA_MES]
  WHERE [Cuadro Resumen] ='top500'
	
	UNION ALL
 
  SELECT  
		0  AS INSTOCK_G_C  
    ,0   AS INSTOCK_G_T5
    ,[INSTOCK_G]  AS INSTOCK_G_T2
    ,[INSTOCK]
    ,CASE       
			WHEN [FECHA] =201901 THEN 'ENERO'
			WHEN [FECHA] =201902 THEN 'FEBRERO'
			WHEN [FECHA] =201903 THEN 'MARZO'
			WHEN [FECHA] =201904 THEN 'ABRIL'
			WHEN [FECHA] =201905 THEN 'MAYO'
			WHEN [FECHA] =201906 THEN 'JUNIO'
			WHEN [FECHA] =201907 THEN 'JULIO'
			WHEN [FECHA] =201908 THEN 'AGOSTO'
			WHEN [FECHA] =201909 THEN 'SEPTIEMBRE'
			WHEN [FECHA] =201910 THEN 'OCTUBRE'
			WHEN [FECHA] =201911 THEN 'NOVIEMBRE'
    END AS FECHA
		-- ,FECHA
    ,ROW_NUMBER() OVER(ORDER BY [FECHA] ASC ) AS ROW_FECHA
  FROM [INFORMES3].[dbo].[CE_INSTOCK_G_COMPAÑIA_MES]
  WHERE [Cuadro Resumen] ='top2100'
) AS AA
WHERE AA.FECHA IS NOT NULL
GROUP BY 
	AA.FECHA,
	AA.ROW_FECHA