--=======INSTOCK DIVISION =========================
--=================================================
/* Updated_at: 2019/11/21
 * Updated_by: Sebastian Cornejo
 * Detalle: Filtro de salas cerradas se hace cruzando con la tabla TIENDAS_ASENTADAS
 */

-- TRUNCATE TABLE INSTOCK_OPT.[dbo].[NUEVO_INSTOCK_MAIL_DIVISION]

-- INSERT INTO INSTOCK_OPT.[dbo].[NUEVO_INSTOCK_MAIL_DIVISION]
-- 					([DIVISION]
-- 					,[INSTOCK])

-- SELECT DIVISION
--         ,''+CONVERT(VARCHAR(10),CONVERT(NUMERIC(12,1),SUM([NUM_OH_VALORIZADO])/nullif(SUM([NUM_VTA_SEM_X_PERFIL]),0)*100))+'%'		AS INSTOCK
--   -- INTO INSTOCK_OPT.[dbo].[NUEVO_INSTOCK_MAIL_DIVISION]
--          FROM  [INSTOCK_OPT].[dbo].[INSTOCK_NUEVA_PLANILLA] 
--         where  COD_LOCAL not in (209,203,205,202,206,105,129,107,207)
--  GROUP BY DIVISION

SELECT 
	DIVISION
	,''+CONVERT(VARCHAR(10),CONVERT(NUMERIC(12,1),SUM([NUM_OH_VALORIZADO])/nullif(SUM([NUM_VTA_SEM_X_PERFIL]),0)*100))+'%' AS INSTOCK
--INTO INSTOCK_OPT.[dbo].[NUEVO_INSTOCK_MAIL_DIVISION]
FROM [INSTOCK_OPT].[dbo].[INSTOCK_NUEVA_PLANILLA] I
LEFT JOIN [INFORMES3].[dbo].[TIENDAS_ASENTADAS] T
	ON I.COD_LOCAL = T.COD_LOCAL
WHERE T.COD_LOCAL IS NULL
GROUP BY DIVISION