TRUNCATE TABLE INSTOCK_PTE_EXP_WMOS
INSERT INTO INSTOCK_PTE_EXP_WMOS

SELECT 
TIENDA,  
SUM(CONVERT(INT,ON_HAND_QTY)) ON_HAND_QTY, 
SKU,  
DESC_SKU, 
SUM(CONVERT(FLOAT,CASEPACK)) CASEPACK,  
SUM(CONVERT(FLOAT,CAJAS_DSP)) CAJAS_DSP

FROM OPENQUERY(MANHATAN,'
SELECT DSP_LOCN, TIPO_DE_ZONA,  TC_LPN_ID OLPN, TIPO_DE_LPN,  ACT_DE_ESTADO FECHA, TC_SHIPMENT_ID,  D_FACILITY_ALIAS_ID TIENDA,  ON_HAND_QTY, SKU_CASEPACK.ITEM_NAME SKU,  SKU_CASEPACK.DESCRIPTION DESC_SKU,  SKU_CASEPACK.QUANTITY CASEPACK, (ON_HAND_QTY/SKU_CASEPACK.QUANTITY) CAJAS_DSP

FROM (with 
LOCATION8 as 
    (select distinct 
           LOCN_HDR.LOCN_ID  as  LOCN_ID,
           LOCN_HDR.DSP_LOCN  as  DSP_LOCN,
           SUBSTR(LOCN_HDR.DSP_LOCN,1, 3)  as  TIPO_DE_ZONA
     from 
           LOCN_HDR LOCN_HDR
     where 
           (SUBSTR(LOCN_HDR.DSP_LOCN,1, 3) = ''DSP'')  or (SUBSTR(LOCN_HDR.DSP_LOCN,1, 3) = ''PTS'') 
    ),
INVENTORY9 as 
    (select distinct 
           WM_INVENTORY.LOCATION_ID  as  LOCATION_ID,
           WM_INVENTORY.ITEM_ID  as  ITEM_ID,
           WM_INVENTORY.TC_LPN_ID  as  TC_LPN_ID,
           WM_INVENTORY.INBOUND_OUTBOUND_INDICATOR  as  INBOUND_OUTBOUND_INDICATOR,
           WM_INVENTORY.ON_HAND_QTY  as  ON_HAND_QTY,
           WM_INVENTORY.INVENTORY_TYPE  as  INVENTORY_TYPE
     from 
           WM_INVENTORY WM_INVENTORY
    ),
INV____LOCN10 as 
    (select distinct 
           LOCATION8.DSP_LOCN  as  DSP_LOCN,
           LOCATION8.TIPO_DE_ZONA  as  TIPO_DE_ZONA,
           INVENTORY9.TC_LPN_ID  as  TC_LPN_ID,
           INVENTORY9.INBOUND_OUTBOUND_INDICATOR  as  INBOUND_OUTBOUND_INDICATOR,
           INVENTORY9.ITEM_ID  as  ITEM_ID,
           INVENTORY9.INVENTORY_TYPE  as  INVENTORY_TYPE,
           INVENTORY9.ON_HAND_QTY  as  ON_HAND_QTY
     from 
           LOCATION8,
           INVENTORY9
     where 
           (INVENTORY9.LOCATION_ID = LOCATION8.LOCN_ID)
    ),
LPN11 as 
    (select distinct 
           LPN.TC_LPN_ID  as  TC_LPN_ID,
           LPN.DEST_SUB_LOCN_ID  as  DEST_SUB_LOCN_ID,
           LPN_FACILITY_STATUS.DESCRIPTION  as  DESCRIPTION,
           LPN.LPN_FACILITY_STAT_UPDATED_DTTM  as  ACT_DE_ESTADO,
           LPN.INBOUND_OUTBOUND_INDICATOR  as  TIPO_DE_LPN,
           LPN.TC_ASN_ID  as  TC_ASN_ID,
           LPN.TC_SHIPMENT_ID  as  TC_SHIPMENT_ID,
           LPN.PREV_SUB_LOCN_ID  as  PREV_SUB_LOCN_ID,
           LPN.TC_PARENT_LPN_ID  as  TC_PARENT_LPN_ID,
           LPN.BUSINESS_PARTNER_ID  as  BUSINESS_PARTNER_ID,
           LPN.D_FACILITY_ALIAS_ID  as  D_FACILITY_ALIAS_ID
     from 
           LPN LPN,
           LPN_FACILITY_STATUS LPN_FACILITY_STATUS
     where 
           (LPN.LPN_TYPE = ''1'') and 
           ((not (LPN.D_FACILITY_ALIAS_ID like ''405'')) and (not (LPN.D_FACILITY_ALIAS_ID like ''423''))) and 
           ((LPN_FACILITY_STATUS.LPN_FACILITY_STATUS = LPN.LPN_FACILITY_STATUS) and (LPN_FACILITY_STATUS.INBOUND_OUTBOUND_INDICATOR = LPN.INBOUND_OUTBOUND_INDICATOR))
    ),
LPN_INV12 as 
    (select distinct 
           INV____LOCN10.DSP_LOCN  as  DSP_LOCN,
           INV____LOCN10.TIPO_DE_ZONA  as  TIPO_DE_ZONA,
           INV____LOCN10.TC_LPN_ID  as  TC_LPN_ID,
           LPN11.TC_PARENT_LPN_ID  as  TC_PARENT_LPN_ID,
           LPN11.TIPO_DE_LPN  as  TIPO_DE_LPN,
           LPN11.ACT_DE_ESTADO  as  ACT_DE_ESTADO,
           LPN11.DESCRIPTION  as  DESCRIPTION,
           LPN11.TC_ASN_ID  as  TC_ASN_ID,
           LPN11.TC_SHIPMENT_ID  as  TC_SHIPMENT_ID,
           LPN11.D_FACILITY_ALIAS_ID  as  D_FACILITY_ALIAS_ID,
           LPN11.DEST_SUB_LOCN_ID  as  DEST_SUB_LOCN_ID,
           LPN11.PREV_SUB_LOCN_ID  as  PREV_SUB_LOCN_ID,
           INV____LOCN10.ITEM_ID  as  ITEM_ID,
           INV____LOCN10.INVENTORY_TYPE  as  INVENTORY_TYPE,
           INV____LOCN10.ON_HAND_QTY  as  ON_HAND_QTY
     from 
           INV____LOCN10,
           LPN11
     where 
           ((INV____LOCN10.TC_LPN_ID = LPN11.TC_LPN_ID) and (INV____LOCN10.INBOUND_OUTBOUND_INDICATOR = LPN11.TIPO_DE_LPN))
    ),
NEXT_LOCATION13 as 
    (select distinct 
           LOCN_HDR.LOCN_ID  as  LOCN_ID,
           LOCN_HDR.DSP_LOCN  as  DSP_LOCN
     from 
           LOCN_HDR LOCN_HDR
    )
select 
       LPN_INV12.DSP_LOCN  as  DSP_LOCN,
       LPN_INV12.TIPO_DE_ZONA  as  TIPO_DE_ZONA,
       LPN_INV12.TC_LPN_ID  as  TC_LPN_ID,
       LPN_INV12.TC_PARENT_LPN_ID  as  TC_PARENT_LPN_ID,
       LPN_INV12.TIPO_DE_LPN  as  TIPO_DE_LPN,
       LPN_INV12.ACT_DE_ESTADO  as  ACT_DE_ESTADO,
       LPN_INV12.DESCRIPTION  as  DESCRIPTION,
       LPN_INV12.TC_ASN_ID  as  TC_ASN_ID,
       LPN_INV12.TC_SHIPMENT_ID  as  TC_SHIPMENT_ID,
       LPN_INV12.D_FACILITY_ALIAS_ID  as  D_FACILITY_ALIAS_ID,
       LPN_INV12.DEST_SUB_LOCN_ID  as  DEST_SUB_LOCN_ID,
       LPN_INV12.PREV_SUB_LOCN_ID  as  PREV_SUB_LOCN_ID,
       NEXT_LOCATION13.DSP_LOCN  as  DSP_LOCN1,
       LPN_INV12.ITEM_ID  as  ITEM_ID,
       LPN_INV12.INVENTORY_TYPE  as  INVENTORY_TYPE,
       LPN_INV12.ON_HAND_QTY  as  ON_HAND_QTY
 from 
       LPN_INV12
        left outer join 
       NEXT_LOCATION13
        on (LPN_INV12.DEST_SUB_LOCN_ID = NEXT_LOCATION13.LOCN_ID)) LPN_DSP LEFT JOIN
        (SELECT 
        IT.ITEM_ID,
        IT.ITEM_NAME,
        IT.DESCRIPTION, 
        ITC.QUANTITY
        FROM ITEM_CBO IT 
        LEFT JOIN ITEM_PACKAGE_CBO ITC ON ITC.ITEM_ID = IT.ITEM_ID
        WHERE ITC.PACKAGE_UOM_ID =''73''
        AND ITC.MARK_FOR_DELETION = ''0''
        AND ITC.IS_STD = ''1'') SKU_CASEPACK ON LPN_DSP.ITEM_ID = SKU_CASEPACK.ITEM_ID WHERE D_FACILITY_ALIAS_ID  NOT LIKE ''4%''
')
GROUP BY
TIENDA,
SKU,
DESC_SKU
