-- TRUNCATE TABLE [INSTOCK_OPT].[dbo].[INSTOCK_OPT_BASE_PARTE_2]

-- INSERT INTO [INSTOCK_OPT].[dbo].[INSTOCK_OPT_BASE_PARTE_2]

SELECT 
	[NOM_PRODUCTO]
	,A.[SKU]
	,1 as [CANTIDAD]
	,NULL AS [COD_CLASIFICACION_SKU]
	,B.[ABC_2018] AS [ABC_2018]
	,C.[ABC_CL] AS [ABC_CL_2018]
	,CASE
		WHEN A.[SKU] IN (SELECT DISTINCT [SKU] FROM [INSTOCK_OPT].[dbo].[CE_TOP_TICKET]) THEN 'TOP_TICKET' 
	END AS [SKU_TOP_TICKET]
	,CASE 
		WHEN A.[SKU] IN (SELECT [SKU] FROM [INSTOCK_OPT].[dbo].[CE_SKU_PALLET_READY]) THEN 'PALLET_READY' 
	END AS [SKU_PALLET_READY]
	,CASE 
		WHEN A.[SKU] IN (SELECT DISTINCT [SKU] FROM [INSTOCK_OPT].[dbo].[CE_INV_417_IMPORT]) 
			THEN (
				SELECT DISTINCT ISNULL([UN_INV_CONT],0) 
				FROM [INSTOCK_OPT].[dbo].[CE_INV_417_IMPORT] 
				WHERE SKU = A.SKU AND [DESC_PROCEDENCIA] ='IMPORTADO' 
			)
	END AS [INV_IMPORTADOS]
	,CASE WHEN A.[SKU] IN (SELECT DISTINCT [SKU] FROM [INSTOCK_OPT].[dbo].[SKU_TOP_500_2100] WHERE TIPO = 'TOP2100') THEN 'TOP2100' END AS [TOP_2100]
	,CASE WHEN A.[SKU] IN (SELECT DISTINCT [SKU] FROM [INSTOCK_OPT].[dbo].[SKU_TOP_500_2100] WHERE TIPO = 'TOP500') THEN 'TOP500' END AS [TOP_500]
	,CASE WHEN [MARCA] IN ('TOTTUS','PRECIO UNO') THEN 'MMPP' END AS [MMPP]
	,[IND_SURTIDO]
	,[ESTADO]
	,[NOM_LOCAL]
	,[COD_LOCAL]
	,[DIVISION]
	,[DEPARTAMENTO]
	,[SUBDEP]
	,[CLASE]
	,[SUBCLASE]
	,[COD_PROV]
	,[NOM_PROV]
	,[RUT]
	,[MARCA]
	,[METOD_ABAST]
	,[NUM_OH_VALORIZADO]
	,[NUM_VTA_SEM_X_PERFIL]
	,[VTA_PERDIDA_VP]
	,CASE WHEN [NUM_OH_VALORIZADO]<=0 THEN 'QUIEBRE' ELSE 'OK' END AS [OH_QUIEBRE]
	,[CANTIDAD_SKUS]
	,[DEMANDA_SEMANAL]
	,[FECHA_ACTUALIZ]
	,[SIS_REPOSICION]
	,[PROCEDENCIA]
	,RI.[Analistas Abastecimiento] as RESPONSABLE
--INTO [INSTOCK_OPT].[dbo].[INSTOCK_OPT_BASE_PARTE_2]
FROM [INSTOCK_OPT].[dbo].[INSTOCK_OPT_BASE] AS A
	LEFT JOIN	[INSTOCK_OPT].[dbo].[ABC_2018] AS B
		ON B.SKU = A.SKU
	LEFT JOIN [INSTOCK_OPT].dbo.ABC_CL_2018 AS C
		ON C.SKU = A.SKU
	LEFT JOIN	[INSTOCK_OPT].[dbo].[CE_RESPONSABLES_INSTOCK] AS RI
		ON LTRIM(RTRIM(RI.[Sub - departamento])) = LTRIM(RTRIM(A.SUBDEP))
