-- TRUNCATE TABLE [INSTOCK_OPT].[dbo].[INSTOCK_NUEVA_PLANILLA]

-- INSERT INTO [INSTOCK_OPT].[dbo].[INSTOCK_NUEVA_PLANILLA]

SELECT DISTINCT 
	[NOM_PRODUCTO]
	,[SKU]
	,CANTIDAD
	,[COD_CLASIFICACION_SKU]
	,ABC_2018
	,ABC_CL_2018
	,[IND_SURTIDO]
	,[ESTADO]
	,[TOP_2100]
	,[TOP_500]
	,[MMPP]
	,[INV_NEGATIVO]
	,[NOM_LOCAL]
	,[COD_LOCAL]
	,TIPO_TIENDA
	,NOMBRE_TIPO_TIENDA
	,[DIVISION]
	,[DEPARTAMENTO]
	,[SUBDEP]
	,[CLASE]
	,[SUBCLASE]
	,[COD_PROV]
	,[NOM_PROV]
	,[RUT]
	,[MARCA]
	,[METOD_ABAST]
	,[NUM_OH_VALORIZADO]
	,[NUM_OH_BINARIO_]
	,[NUM_VTA_SEM_X_PERFIL]
	,[VTA_PERDIDA_VP]
	,[OH_QUIEBRE]
	,[COSTO_INV_DISP_HOY]
	,[MONTO_VTA]
	,[CANTIDAD_SKUS]
	,[DEMANDA_SEMANAL]
	,FECHA_ACTUALIZ
	,[SIS_REPOSICION]
	,[PROCEDENCIA]
	,[RESPONSABLE]
--INTO [INSTOCK_OPT].[dbo].[INSTOCK_NUEVA_PLANILLA]
FROM [INSTOCK_OPT].[dbo].[INSTOCK_OPT_BASE_PARTE_4]
WHERE
	CONVERT(DATE, FECHA_ACTUALIZ) = CONVERT(DATE, GETDATE())
	AND (
		(
			DIVISION IN ('J01 - PGC COMESTIBLE')
			AND SIS_REPOSICION IN ('Reposicion x ASR', 'Informar a ASR')
		)
		OR (
			DIVISION IN ('J02 - PGC NO COMESTIBLE', 'J05 - FLC', 'J06 - PANADERIA Y PASTELERIA', 'J07 - PLATOS PREPARADOS')
			AND SIS_REPOSICION IN ('Reposicion x ASR')
		)
	)
