-- truncate table [INSTOCK_OPT].[dbo].[INSTOCK_NUEVA_PLANILLA_NF] 

-- insert into [INSTOCK_OPT].[dbo].[INSTOCK_NUEVA_PLANILLA_NF] 

SELECT  DISTINCT
	[NOM_PRODUCTO]
	,[SKU]
	,[COD_CLASIFICACION_SKU]
	,[IND_SURTIDO]
	,[ESTADO]
	,[TOP_2100]
	,[TOP_500]
	,[MMPP]
	,[INV_NEGATIVO]
	,[NOM_LOCAL]
	,[COD_LOCAL]
	,[DIVISION]
	,[DEPARTAMENTO]
	,[SUBDEP]
	,[CLASE]
	,[SUBCLASE]
	,[COD_PROV]
	,[NOM_PROV]
	,[RUT]
	,[MARCA]
	,[METOD_ABAST]
	,[NUM_OH_VALORIZADO]
	,[NUM_VTA_SEM_X_PERFIL]
	,[VTA_PERDIDA_VP]
	,[OH_QUIEBRE]
	,[COSTO_INV_DISP_HOY]
	,[MONTO_VTA]
	,[CANTIDAD_SKUS]
	,[DEMANDA_SEMANAL]
	,CONVERT(DATE,[FECHA_ACTUALIZ]) AS FECHA_ACTUALIZ
	,[SIS_REPOSICION]
	,[PROCEDENCIA]
	,[RESPONSABLE]
--INTO [INSTOCK_OPT].[dbo].[INSTOCK_NUEVA_PLANILLA_NF] 
FROM INSTOCK_OPT.dbo.INSTOCK_OPT_BASE_PARTE_4
WHERE 
	DIVISION IN ('J08 - VESTUARIO','J09 - HOGAR','J10 - BAZAR','J11 - ELECTRO')
	AND SIS_REPOSICION IN ('Reposicion x ASR', 'Informar a ASR')


