-- TRUNCATE TABLE [INSTOCK_OPT].[dbo].[INSTOCK_NUEVA_PLANILLA_CAMILA]
  
-- INSERT INTO [INSTOCK_OPT].[dbo].[INSTOCK_NUEVA_PLANILLA_CAMILA]
  
SELECT
	CASE
		WHEN A.SKU IN (SELECT SKU FROM [INSTOCK_OPT].dbo.PRODUCTOS_CAMILA WHERE ESTADO='ALTA VENTA') THEN 'ALTA VENTA'
		WHEN A.SKU IN (SELECT SKU FROM [INSTOCK_OPT].dbo.PRODUCTOS_CAMILA WHERE ESTADO='MEDIANA VENTA')  THEN 'MEDIANA VENTA' 
		WHEN A.SKU IN (SELECT SKU FROM [INSTOCK_OPT].dbo.PRODUCTOS_CAMILA WHERE ESTADO='PRODUCTOS NUEVOS')  THEN 'PRODUCTOS NUEVOS'
	END AS [CLUSTER_DE_PRODUCTOS]
	,A.[NOM_PRODUCTO]
	,A.[SKU]
	,A.[CANTIDAD]
	,A.[SKU_TOP_TICKET]
	,A.[SKU_PALLET_READY]
	,A.[COD_CLASIFICACION_SKU]
	,A.[ABC_2018]
	,A.[ABC_CL_2018]
	,A.[IND_SURTIDO]
	,A.[ESTADO]
	,A.[TOP_2100]
	,A.[TOP_500]
	,A.[MMPP]
	,A.[INV_NEGATIVO]
	,A.[NOM_LOCAL]
	,A.[COD_LOCAL]
	,A.[DIVISION]
	,A.[DEPARTAMENTO]
	,A.[SUBDEP]
	,A.[CLASE]
	,A.[SUBCLASE]
	,C.[COD_PROV_PMM] AS COD_PROV
	,A.[NOM_PROV]
	,A.[RUT]
	,A.[MARCA]
	,A.[METOD_ABAST]
	,B.[ON_HAND]
	,B.[ON_ORDER]
	,A.[NUM_OH_VALORIZADO]
	,A.[NUM_OH_BINARIO_]
	,A.[NUM_VTA_SEM_X_PERFIL]
	,A.[INV_IMPORTADOS]
	,A.[VTA_PERDIDA_VP]
	,A.[OH_QUIEBRE]
	,A.[UN_INV_DISP_HOY]
	,A.[COSTO_INV_DISP_HOY]
	,A.[UN_VTA]
	,A.[MONTO_VTA]
	,A.[CANTIDAD_SKUS]
	,A.[DEMANDA_SEMANAL]
	,A.[FECHA_ACTUALIZ]
	,A.[SIS_REPOSICION]
	,A.[PROCEDENCIA]
	,A.[RESPONSABLE]
--INTO [INSTOCK_OPT].[dbo].[INSTOCK_NUEVA_PLANILLA_CAMILA]
FROM [INSTOCK_OPT].[dbo].[INSTOCK_OPT_BASE_PARTE_4] AS A 
LEFT JOIN [INSTOCK_OPT].dbo.CE_OH_ON_ORDER_INSTOCK AS B 
	ON B.CUSTCOL_7 = A.SKU 
	AND B.COD_LOCALFISICO = A.COD_LOCAL 
LEFT JOIN [INSTOCK_OPT].dbo.COD_PROV_PMM_DWH AS C 
	ON C.COD_PROV_DWH = A.COD_PROV
WHERE (
	CONVERT(DATE, FECHA_ACTUALIZ) = CONVERT(DATE, GETDATE())
	AND (
		A.DIVISION IN ('J01 - PGC COMESTIBLE','J02 - PGC NO COMESTIBLE','J05 - FLC') 
		AND SIS_REPOSICION IN ('Reposicion x ASR', 'Informar a ASR') 
	) 
	OR (
		DIVISION IN ('J06 - PANADERIA Y PASTELERIA', 'J07 - PLATOS PREPARADOS')
		AND SIS_REPOSICION IN ('Reposicion x ASR')
	) 
	OR DIVISION in ('J08 - VESTUARIO','J09 - HOGAR','J10 - BAZAR','J11 - ELECTRO')
	OR (
		A.SUBDEP LIKE '%POLLO%' 
		OR A.SUBDEP LIKE '%PAVO%' 
		OR A.SUBDEP LIKE '%CERDO%'
	)
)