-- INSERT INTO [INSTOCK_OPT].[dbo].[MAIL_INSTOCK_SUBDEP_2_TOP_DIV]

-- SELECT   [TOP_2100]
--       ,[TOP_500]
--       ,[MMPP]
--       ,PROCEDENCIA
--       ,DIVISION
--       ,SIS_REPOSICION
--       ,SUM([NUM_OH_VALORIZADO]) AS [NUM_OH_VALORIZADO]
--       ,SUM([NUM_VTA_SEM_X_PERFIL]) AS [NUM_VTA_SEM_X_PERFIL]
--       ,CONVERT(DATE,[FECHA_ACTUALIZ]) FECHA_ACTUALIZ 
--  FROM [INSTOCK_OPT].dbo.INSTOCK_OPT_BASE_PARTE_4
--  WHERE ((DIVISION  in ('J01 - PGC COMESTIBLE') and SIS_REPOSICION in ('Reposicion x ASR','Informar a ASR'))
--    or (DIVISION  in ('J02 - PGC NO COMESTIBLE') and SIS_REPOSICION in ('Reposicion x ASR'))
--   or (DIVISION in ('J05 - FLC','J06 - PANADERIA Y PASTELERIA','J07 - PLATOS PREPARADOS')  and  SIS_REPOSICION in ('Reposicion x ASR')))
-- and COD_LOCAL not in (209,203,205,202,206,105,129,107,207)
--    GROUP BY   [TOP_2100]
--       ,[TOP_500]
--       ,[MMPP]
--       ,PROCEDENCIA
--       ,DIVISION
--       ,SIS_REPOSICION
--       ,[FECHA_ACTUALIZ]


SELECT
	[TOP_2100]
	,[TOP_500]
	,[MMPP]
	,PROCEDENCIA
	,DIVISION
	,SIS_REPOSICION
	,SUM([NUM_OH_VALORIZADO]) AS [NUM_OH_VALORIZADO]
	,SUM([NUM_VTA_SEM_X_PERFIL]) AS [NUM_VTA_SEM_X_PERFIL]
	,CONVERT(DATE,[FECHA_ACTUALIZ]) FECHA_ACTUALIZ
FROM [INSTOCK_OPT].dbo.INSTOCK_OPT_BASE_PARTE_4 I
LEFT JOIN [INFORMES3].[dbo].[TIENDAS_ASENTADAS] T
	ON I.COD_LOCAL = T.COD_LOCAL
WHERE 
	(
		(
			DIVISION IN ('J01 - PGC COMESTIBLE', 'J02 - PGC NO COMESTIBLE', 'J05 - FLC') 
			AND SIS_REPOSICION IN ('Reposicion x ASR','Informar a ASR')
		)
		OR (
			DIVISION IN ('J06 - PANADERIA Y PASTELERIA','J07 - PLATOS PREPARADOS') 
			AND SIS_REPOSICION IN ('Reposicion x ASR')
		)
	)
	AND T.COD_LOCAL IS NULL
GROUP BY
	[TOP_2100]
	,[TOP_500]
	,[MMPP]
	,PROCEDENCIA
	,DIVISION
	,SIS_REPOSICION
	,[FECHA_ACTUALIZ]