-- INSERT INTO [INSTOCK_OPT].[dbo].[MAIL_INSTOCK_SUBDEP_2] (
-- 	[DIVISION]
-- 	,[SUBDEP]
-- 	,[SIS_REPOSICION]
-- 	,[NUM_OH_VALORIZADO]
-- 	,[NUM_VTA_SEM_X_PERFIL]
-- 	,[FECHA_ACTUALIZ]
-- )

--   SELECT [DIVISION]
--       ,[SUBDEP]
--       ,[SIS_REPOSICION]
--       ,SUM([NUM_OH_VALORIZADO]) AS [NUM_OH_VALORIZADO]
--       ,SUM([NUM_VTA_SEM_X_PERFIL]) AS [NUM_VTA_SEM_X_PERFIL]
--       ,CONVERT(DATE,[FECHA_ACTUALIZ]) AS FECHA_ACTUALIZ
--  -- INTO [INSTOCK_OPT].[dbo].[MAIL_INSTOCK_SUBDEP_2]
--   FROM [INSTOCK_OPT].dbo.INSTOCK_OPT_BASE_PARTE_4  
--  where  COD_LOCAL not in (209,203,205,202,206,105,129,107,207)
--   GROUP BY [DIVISION]
--       ,[SUBDEP]
--       ,[SIS_REPOSICION]
--       ,[FECHA_ACTUALIZ]



SELECT 
	[DIVISION]
	,[SUBDEP]
	,[SIS_REPOSICION]
	,SUM([NUM_OH_VALORIZADO]) AS [NUM_OH_VALORIZADO]
	,SUM([NUM_VTA_SEM_X_PERFIL]) AS [NUM_VTA_SEM_X_PERFIL]
	,CONVERT(DATE,[FECHA_ACTUALIZ]) AS FECHA_ACTUALIZ
--INTO [INSTOCK_OPT].[dbo].[MAIL_INSTOCK_SUBDEP_2]
FROM [INSTOCK_OPT].dbo.INSTOCK_OPT_BASE_PARTE_4 I
LEFT JOIN [INFORMES3].[dbo].[TIENDAS_ASENTADAS] T
	ON I.COD_LOCAL = T.COD_LOCAL
WHERE T.COD_LOCAL IS NULL
GROUP BY
	[DIVISION]
	,[SUBDEP]
	,[SIS_REPOSICION]
	,[FECHA_ACTUALIZ]
