/* Updated_at: 2019/11/21
 * Updated_by: Sebastian Cornejo
 * Detalle: 
 *	-> 2019/11/21: Filtro de salas cerradas se hace cruzando con la tabla TIENDAS_ASENTADAS
 *	-> 2020/01/08: Se agrega EDLP
 */

-- INSERT INTO [INSTOCK_OPT].[dbo].[MAIL_INSTOCK_SUBDEP_2] (
-- 	[DIVISION]
-- 	,[SUBDEP]
-- 	,[SIS_REPOSICION]
-- 	,[NUM_OH_VALORIZADO]
-- 	,[NUM_VTA_SEM_X_PERFIL]
-- 	,[FECHA_ACTUALIZ]
-- )

--   SELECT [DIVISION]
--       ,[SUBDEP]
--       ,[SIS_REPOSICION]
--       ,SUM([NUM_OH_VALORIZADO]) AS [NUM_OH_VALORIZADO]
--       ,SUM([NUM_VTA_SEM_X_PERFIL]) AS [NUM_VTA_SEM_X_PERFIL]
--       ,CONVERT(DATE,[FECHA_ACTUALIZ]) AS FECHA_ACTUALIZ
--  -- INTO [INSTOCK_OPT].[dbo].[MAIL_INSTOCK_SUBDEP_2]
--   FROM [INSTOCK_OPT].dbo.INSTOCK_OPT_BASE_PARTE_4  
--  where  COD_LOCAL not in (209,203,205,202,206,105,129,107,207)
--   GROUP BY [DIVISION]
--       ,[SUBDEP]
--       ,[SIS_REPOSICION]
--       ,[FECHA_ACTUALIZ]



SELECT 
	[DIVISION]
	,[SUBDEP]
	,[SIS_REPOSICION]
	,SUM([NUM_OH_VALORIZADO]) AS [NUM_OH_VALORIZADO]
	,SUM([NUM_VTA_SEM_X_PERFIL]) AS [NUM_VTA_SEM_X_PERFIL]
	,CONVERT(DATE,[FECHA_ACTUALIZ]) AS FECHA_ACTUALIZ
	,EDLP.EDLP
--INTO [INSTOCK_OPT].[dbo].[MAIL_INSTOCK_SUBDEP_2]
FROM [INSTOCK_OPT].dbo.INSTOCK_OPT_BASE_PARTE_4 I
LEFT JOIN [INSTOCK_OPT].dbo.SKU_EDLP EDLP
	ON EDLP.SKU = I.SKU
WHERE I.COD_LOCAL NOT IN (SELECT * FROM [INFORMES3].[dbo].[TIENDAS_ASENTADAS])
GROUP BY
	[DIVISION]
	,[SUBDEP]
	,[SIS_REPOSICION]
	,[FECHA_ACTUALIZ]
	,EDLP.EDLP
