-- TRUNCATE TABLE [INSTOCK_OPT].[dbo].[INSTOCK_NUEVA_PLANILLA_BEMINING]

-- INSERT INTO [INSTOCK_OPT].[dbo].[INSTOCK_NUEVA_PLANILLA_BEMINING]

SELECT 
	A.[NOM_PRODUCTO]
	,A.[SKU]
	,A.[CANTIDAD]
	,A.[COD_CLASIFICACION_SKU]
	,A.[ABC_2018]
	,A.[ABC_CL_2018]
	,A.[IND_SURTIDO]
	,A.[ESTADO]
	,A.[TOP_2100]
	,A.[TOP_500]
	,A.[MMPP]
	,A.[INV_NEGATIVO]
	,A.[NOM_LOCAL]
	,A.[COD_LOCAL]
	,A.[DIVISION]
	,A.[DEPARTAMENTO]
	,A.[SUBDEP]
	,A.[CLASE]
	,A.[SUBCLASE]
	,A.[COD_PROV]
	,A.[NOM_PROV]
	,A.[RUT]
	,A.[MARCA]
	,A.[METOD_ABAST]
	,A.[NUM_OH_VALORIZADO]
	,A.[NUM_OH_BINARIO_]
	,A.[NUM_VTA_SEM_X_PERFIL]
	,A.[VTA_PERDIDA_VP]
	,A.[OH_QUIEBRE]
	,A.[COSTO_INV_DISP_HOY]
	,A.[MONTO_VTA]
	,A.[CANTIDAD_SKUS]
	,A.[DEMANDA_SEMANAL]
	,A.[FECHA_ACTUALIZ]
	,A.[SIS_REPOSICION]
	,A.[PROCEDENCIA]
	,A.[RESPONSABLE]
	,ISNULL(B.UN_INV_DISP_HOY,0) AS UN_INV_DISP_HOY 
	,ISNULL(B.UN_INV_CONT_HOY,0) AS UN_INV_CONT_HOY
--INTO [INSTOCK_OPT].[dbo].[INSTOCK_NUEVA_PLANILLA_BEMINING]
FROM [INSTOCK_OPT].dbo.INSTOCK_OPT_BASE_PARTE_4 AS A 
LEFT JOIN [INSTOCK_OPT].dbo.STOCK_HOY_CIA AS B 
	ON B.COD_LOCAL = A.COD_LOCAL 
	AND B.SKU = A.SKU
WHERE 
	CONVERT(DATE, FECHA_ACTUALIZ) = CONVERT(DATE, GETDATE())
	AND (
	(
		(
			A.DIVISION IN ('J01 - PGC COMESTIBLE'))
			AND SIS_REPOSICION IN ('Reposicion x ASR', 'Informar a ASR')
		)
		OR (
			A.DIVISION IN ('J02 - PGC NO COMESTIBLE', 'J05 - FLC', 'J06 - PANADERIA Y PASTELERIA', 'J07 - PLATOS PREPARADOS')
			AND SIS_REPOSICION IN ('Reposicion x ASR')
		)
	)