--========= CE_INSTOCK_G_COMPAÑIA_MES ======================================
/* Updated_at: 2019/11/21
 * Updated_by: Sebastian Cornejo
 * Detalle: Filtro de salas cerradas se hace cruzando con la tabla TIENDAS_ASENTADAS
 */


-- TRUNCATE TABLE [INSTOCK_OPT].[dbo].[CE_INSTOCK_G_COMPAÑIA_MES]

-- INSERT INTO [INSTOCK_OPT].[dbo].[CE_INSTOCK_G_COMPAÑIA_MES] (
-- 	[Cuadro Resumen]
-- 	,[INSTOCK_G]
-- 	,[INSTOCK]
-- 	,[FECHA]
-- )

SELECT 
	'INSTOCK COMPAÑIA' AS [Cuadro Resumen]
	,CONVERT(NUMERIC(12,2),SUM([NUM_OH_VALORIZADO])/nullif(SUM([NUM_VTA_SEM_X_PERFIL]),0)*100) AS INSTOCK_G
	,CONVERT(VARCHAR(10),CONVERT(NUMERIC(12,2),SUM([NUM_OH_VALORIZADO])/nullif(SUM([NUM_VTA_SEM_X_PERFIL]),0)*100))+'%' AS INSTOCK
	,MES_GROGORIANO AS FECHA
--INTO [INSTOCK_OPT].[dbo].[CE_INSTOCK_G_COMPAÑIA_MES]
FROM [INSTOCK_OPT].[dbo].[MAIL_INSTOCK_SUBDEP_2] AS A
JOIN [INSTOCK_OPT].dbo.DHW_MES_GC AS B 
	ON B.FECHA = CONVERT(DATE,A.FECHA_ACTUALIZ) 
WHERE 
	(
		(
			A.DIVISION IN ('J01 - PGC COMESTIBLE', 'J02 - PGC NO COMESTIBLE', 'J05 - FLC') 
			AND A.SIS_REPOSICION IN ('Reposicion x ASR','Informar a ASR')
		)
		OR (
			A.DIVISION IN ('J06 - PANADERIA Y PASTELERIA','J07 - PLATOS PREPARADOS')
			AND A.SIS_REPOSICION in ('Reposicion x ASR')
		)
	)
	-- AND COD_LOCAL not in (209,203,205,202,206,105,129,107,207) 
GROUP BY MES_GROGORIANO

UNION ALL

-- SELECT     'TOP2100' AS [Cuadro Resumen], CONVERT(NUMERIC(12, 2), SUM(A.NUM_OH_VALORIZADO) / NULLIF (SUM(A.NUM_VTA_SEM_X_PERFIL), 0) * 100) AS INSTOCK_G, 
--                       CONVERT(VARCHAR(10), CONVERT(NUMERIC(12, 2), SUM(A.NUM_OH_VALORIZADO) / NULLIF (SUM(A.NUM_VTA_SEM_X_PERFIL), 0) * 100)) + '%' AS INSTOCK, 
--                       B.MES_GROGORIANO AS FECHA
-- FROM         INSTOCK_OPT.dbo.MAIL_INSTOCK_SUBDEP_2_TOP_DIV AS A INNER JOIN
--                       INSTOCK_OPT.dbo.DHW_MES_GC AS B ON B.FECHA = CONVERT(DATE, A.FECHA_ACTUALIZ)
-- WHERE     (A.DIVISION IN ('J01 - PGC COMESTIBLE')) AND (A.SIS_REPOSICION IN ('Reposicion x ASR', 'Informar a ASR')) AND (A.TOP_2100 = 'TOP2100') OR
--                       (A.DIVISION IN ('J02 - PGC NO COMESTIBLE')) AND (A.SIS_REPOSICION IN ('Reposicion x ASR')) AND (A.TOP_2100 = 'TOP2100') OR
--                       (A.DIVISION IN ('J05 - FLC', 'J06 - PANADERIA Y PASTELERIA', 'J07 - PLATOS PREPARADOS')) AND (A.SIS_REPOSICION IN ('Reposicion x ASR')) AND 
--                       (A.TOP_2100 = 'TOP2100') 
--                       --and COD_LOCAL not in (209,203,205,202,206,105,129,107,207)
-- GROUP BY B.MES_GROGORIANO

SELECT 
	'TOP2100' AS [Cuadro Resumen], 
	CONVERT(NUMERIC(12, 2), SUM(A.NUM_OH_VALORIZADO) / NULLIF (SUM(A.NUM_VTA_SEM_X_PERFIL), 0) * 100) AS INSTOCK_G, 
	CONVERT(VARCHAR(10), CONVERT(NUMERIC(12, 2), SUM(A.NUM_OH_VALORIZADO) / NULLIF (SUM(A.NUM_VTA_SEM_X_PERFIL), 0) * 100)) + '%' AS INSTOCK,
	B.MES_GROGORIANO AS FECHA
FROM INSTOCK_OPT.dbo.MAIL_INSTOCK_SUBDEP_2_TOP_DIV AS A 
INNER JOIN INSTOCK_OPT.dbo.DHW_MES_GC AS B 
	ON B.FECHA = CONVERT(DATE, A.FECHA_ACTUALIZ)
WHERE
	A.TOP_2100 = 'TOP2100'
	AND (
		(
			A.DIVISION IN ('J01 - PGC COMESTIBLE''J02 - PGC NO COMESTIBLE', 'J05 - FLC')
			AND A.SIS_REPOSICION IN ('Reposicion x ASR', 'Informar a ASR')
		)
		OR (
			A.DIVISION IN ('J06 - PANADERIA Y PASTELERIA', 'J07 - PLATOS PREPARADOS')
			AND A.SIS_REPOSICION IN ('Reposicion x ASR')
		)
	)
	-- AND COD_LOCAL not in (209,203,205,202,206,105,129,107,207)
GROUP BY B.MES_GROGORIANO

UNION ALL 


--   SELECT     'TOP500' AS [Cuadro Resumen], CONVERT(NUMERIC(12, 2), SUM(A.NUM_OH_VALORIZADO) / NULLIF (SUM(A.NUM_VTA_SEM_X_PERFIL), 0) * 100) AS INSTOCK_G, 
--                       CONVERT(VARCHAR(10), CONVERT(NUMERIC(12, 2), SUM(A.NUM_OH_VALORIZADO) / NULLIF (SUM(A.NUM_VTA_SEM_X_PERFIL), 0) * 100)) + '%' AS INSTOCK, 
--                       B.MES_GROGORIANO AS FECHA
-- FROM         INSTOCK_OPT.dbo.MAIL_INSTOCK_SUBDEP_2_TOP_DIV AS A INNER JOIN
--                       INSTOCK_OPT.dbo.DHW_MES_GC AS B ON B.FECHA = CONVERT(DATE, A.FECHA_ACTUALIZ)
-- WHERE     (A.DIVISION IN ('J01 - PGC COMESTIBLE')) AND (A.SIS_REPOSICION IN ('Reposicion x ASR', 'Informar a ASR')) AND (A.TOP_500 = 'TOP500') OR
--                       (A.DIVISION IN ('J02 - PGC NO COMESTIBLE')) AND (A.SIS_REPOSICION IN ('Reposicion x ASR')) AND (A.TOP_500 = 'TOP500') OR
--                       (A.DIVISION IN ('J05 - FLC', 'J06 - PANADERIA Y PASTELERIA', 'J07 - PLATOS PREPARADOS')) AND (A.SIS_REPOSICION IN ('Reposicion x ASR')) AND 
--                       (A.TOP_500 = 'TOP500') 
--                       --and COD_LOCAL not in (209,203,205,202,206,105,129,107,207)
-- GROUP BY B.MES_GROGORIANO


SELECT 
	'TOP500' AS [Cuadro Resumen], 
	CONVERT(NUMERIC(12, 2), SUM(A.NUM_OH_VALORIZADO) / NULLIF (SUM(A.NUM_VTA_SEM_X_PERFIL), 0) * 100) AS INSTOCK_G,
	CONVERT(VARCHAR(10), CONVERT(NUMERIC(12, 2), SUM(A.NUM_OH_VALORIZADO) / NULLIF (SUM(A.NUM_VTA_SEM_X_PERFIL), 0) * 100)) + '%' AS INSTOCK,
	B.MES_GROGORIANO AS FECHA
FROM INSTOCK_OPT.dbo.MAIL_INSTOCK_SUBDEP_2_TOP_DIV AS A 
INNER JOIN INSTOCK_OPT.dbo.DHW_MES_GC AS B 
	ON B.FECHA = CONVERT(DATE, A.FECHA_ACTUALIZ)
WHERE 
	A.TOP_500 = 'TOP500'
	AND (
		(
			A.DIVISION IN ('J01 - PGC COMESTIBLE''J02 - PGC NO COMESTIBLE', 'J05 - FLC')
			AND A.SIS_REPOSICION IN ('Reposicion x ASR', 'Informar a ASR')
		)
		OR (
			A.DIVISION IN ('J06 - PANADERIA Y PASTELERIA', 'J07 - PLATOS PREPARADOS')
			AND A.SIS_REPOSICION IN ('Reposicion x ASR')
		)
	)
	-- AND COD_LOCAL not in (209,203,205,202,206,105,129,107,207)
GROUP BY B.MES_GROGORIANO
