--========= CE_INSTOCK_G_COMPAÑIA_MES ======================================
/* Updated_at: 2020/01/08
 * Updated_by: Sebastian Cornejo
 * Detalle: 
 *	-> 2019/11/21: Filtro de salas cerradas se hace cruzando con la tabla TIENDAS_ASENTADAS
 *	-> 2020/01/08: Se agrega EDLP
 */


TRUNCATE TABLE [INSTOCK_OPT].[dbo].[CE_INSTOCK_G_COMPAÑIA_MES]

INSERT INTO [INSTOCK_OPT].[dbo].[CE_INSTOCK_G_COMPAÑIA_MES] (
	[Cuadro Resumen]
	,[INSTOCK_G]
	,[INSTOCK]
	,[FECHA]
)


-- SELECT 
-- 	'INSTOCK COMPAÑIA' AS [Cuadro Resumen]
-- 	,CONVERT(NUMERIC(12,2),SUM([NUM_OH_VALORIZADO])/nullif(SUM([NUM_VTA_SEM_X_PERFIL]),0)*100) AS INSTOCK_G
-- 	,CONVERT(VARCHAR(10),CONVERT(NUMERIC(12,2),SUM([NUM_OH_VALORIZADO])/nullif(SUM([NUM_VTA_SEM_X_PERFIL]),0)*100))+'%' AS INSTOCK
-- 	,MES_GROGORIANO AS FECHA
-- --INTO [INSTOCK_OPT].[dbo].[CE_INSTOCK_G_COMPAÑIA_MES]
-- FROM [INSTOCK_OPT].[dbo].[MAIL_INSTOCK_SUBDEP_2] AS A
-- JOIN [INSTOCK_OPT].dbo.DHW_MES_GC AS B 
-- 	ON B.FECHA = CONVERT(DATE,A.FECHA_ACTUALIZ) 
-- WHERE 
-- 	(
-- 		(
-- 			A.DIVISION IN ('J01 - PGC COMESTIBLE', 'J02 - PGC NO COMESTIBLE', 'J05 - FLC') 
-- 			AND A.SIS_REPOSICION IN ('Reposicion x ASR','Informar a ASR')
-- 		)
-- 		OR (
-- 			A.DIVISION IN ('J06 - PANADERIA Y PASTELERIA','J07 - PLATOS PREPARADOS')
-- 			AND A.SIS_REPOSICION in ('Reposicion x ASR')
-- 		)
-- 	)
-- 	-- AND COD_LOCAL not in (209,203,205,202,206,105,129,107,207) 
-- GROUP BY MES_GROGORIANO

-- UNION ALL

-- -- SELECT     'TOP2100' AS [Cuadro Resumen], CONVERT(NUMERIC(12, 2), SUM(A.NUM_OH_VALORIZADO) / NULLIF (SUM(A.NUM_VTA_SEM_X_PERFIL), 0) * 100) AS INSTOCK_G, 
-- --                       CONVERT(VARCHAR(10), CONVERT(NUMERIC(12, 2), SUM(A.NUM_OH_VALORIZADO) / NULLIF (SUM(A.NUM_VTA_SEM_X_PERFIL), 0) * 100)) + '%' AS INSTOCK, 
-- --                       B.MES_GROGORIANO AS FECHA
-- -- FROM         INSTOCK_OPT.dbo.MAIL_INSTOCK_SUBDEP_2_TOP_DIV AS A INNER JOIN
-- --                       INSTOCK_OPT.dbo.DHW_MES_GC AS B ON B.FECHA = CONVERT(DATE, A.FECHA_ACTUALIZ)
-- -- WHERE     (A.DIVISION IN ('J01 - PGC COMESTIBLE')) AND (A.SIS_REPOSICION IN ('Reposicion x ASR', 'Informar a ASR')) AND (A.TOP_2100 = 'TOP2100') OR
-- --                       (A.DIVISION IN ('J02 - PGC NO COMESTIBLE')) AND (A.SIS_REPOSICION IN ('Reposicion x ASR')) AND (A.TOP_2100 = 'TOP2100') OR
-- --                       (A.DIVISION IN ('J05 - FLC', 'J06 - PANADERIA Y PASTELERIA', 'J07 - PLATOS PREPARADOS')) AND (A.SIS_REPOSICION IN ('Reposicion x ASR')) AND 
-- --                       (A.TOP_2100 = 'TOP2100') 
-- --                       --and COD_LOCAL not in (209,203,205,202,206,105,129,107,207)
-- -- GROUP BY B.MES_GROGORIANO

-- SELECT 
-- 	'TOP2100' AS [Cuadro Resumen], 
-- 	CONVERT(NUMERIC(12, 2), SUM(A.NUM_OH_VALORIZADO) / NULLIF (SUM(A.NUM_VTA_SEM_X_PERFIL), 0) * 100) AS INSTOCK_G, 
-- 	CONVERT(VARCHAR(10), CONVERT(NUMERIC(12, 2), SUM(A.NUM_OH_VALORIZADO) / NULLIF (SUM(A.NUM_VTA_SEM_X_PERFIL), 0) * 100)) + '%' AS INSTOCK,
-- 	B.MES_GROGORIANO AS FECHA
-- FROM INSTOCK_OPT.dbo.MAIL_INSTOCK_SUBDEP_2_TOP_DIV AS A 
-- INNER JOIN INSTOCK_OPT.dbo.DHW_MES_GC AS B 
-- 	ON B.FECHA = CONVERT(DATE, A.FECHA_ACTUALIZ)
-- WHERE
-- 	A.TOP_2100 = 'TOP2100'
-- 	AND (
-- 		(
-- 			A.DIVISION IN ('J01 - PGC COMESTIBLE','J02 - PGC NO COMESTIBLE', 'J05 - FLC')
-- 			AND A.SIS_REPOSICION IN ('Reposicion x ASR', 'Informar a ASR')
-- 		)
-- 		OR (
-- 			A.DIVISION IN ('J06 - PANADERIA Y PASTELERIA', 'J07 - PLATOS PREPARADOS')
-- 			AND A.SIS_REPOSICION IN ('Reposicion x ASR')
-- 		)
-- 	)
-- 	-- AND COD_LOCAL not in (209,203,205,202,206,105,129,107,207)
-- GROUP BY B.MES_GROGORIANO

-- UNION ALL 


-- --   SELECT     'TOP500' AS [Cuadro Resumen], CONVERT(NUMERIC(12, 2), SUM(A.NUM_OH_VALORIZADO) / NULLIF (SUM(A.NUM_VTA_SEM_X_PERFIL), 0) * 100) AS INSTOCK_G, 
-- --                       CONVERT(VARCHAR(10), CONVERT(NUMERIC(12, 2), SUM(A.NUM_OH_VALORIZADO) / NULLIF (SUM(A.NUM_VTA_SEM_X_PERFIL), 0) * 100)) + '%' AS INSTOCK, 
-- --                       B.MES_GROGORIANO AS FECHA
-- -- FROM         INSTOCK_OPT.dbo.MAIL_INSTOCK_SUBDEP_2_TOP_DIV AS A INNER JOIN
-- --                       INSTOCK_OPT.dbo.DHW_MES_GC AS B ON B.FECHA = CONVERT(DATE, A.FECHA_ACTUALIZ)
-- -- WHERE     (A.DIVISION IN ('J01 - PGC COMESTIBLE')) AND (A.SIS_REPOSICION IN ('Reposicion x ASR', 'Informar a ASR')) AND (A.TOP_500 = 'TOP500') OR
-- --                       (A.DIVISION IN ('J02 - PGC NO COMESTIBLE')) AND (A.SIS_REPOSICION IN ('Reposicion x ASR')) AND (A.TOP_500 = 'TOP500') OR
-- --                       (A.DIVISION IN ('J05 - FLC', 'J06 - PANADERIA Y PASTELERIA', 'J07 - PLATOS PREPARADOS')) AND (A.SIS_REPOSICION IN ('Reposicion x ASR')) AND 
-- --                       (A.TOP_500 = 'TOP500') 
-- --                       --and COD_LOCAL not in (209,203,205,202,206,105,129,107,207)
-- -- GROUP BY B.MES_GROGORIANO


-- SELECT 
-- 	'TOP500' AS [Cuadro Resumen], 
-- 	CONVERT(NUMERIC(12, 2), SUM(A.NUM_OH_VALORIZADO) / NULLIF (SUM(A.NUM_VTA_SEM_X_PERFIL), 0) * 100) AS INSTOCK_G,
-- 	CONVERT(VARCHAR(10), CONVERT(NUMERIC(12, 2), SUM(A.NUM_OH_VALORIZADO) / NULLIF (SUM(A.NUM_VTA_SEM_X_PERFIL), 0) * 100)) + '%' AS INSTOCK,
-- 	B.MES_GROGORIANO AS FECHA
-- FROM INSTOCK_OPT.dbo.MAIL_INSTOCK_SUBDEP_2_TOP_DIV AS A 
-- INNER JOIN INSTOCK_OPT.dbo.DHW_MES_GC AS B 
-- 	ON B.FECHA = CONVERT(DATE, A.FECHA_ACTUALIZ)
-- WHERE 
-- 	A.TOP_500 = 'TOP500'
-- 	AND (
-- 		(
-- 			A.DIVISION IN ('J01 - PGC COMESTIBLE','J02 - PGC NO COMESTIBLE', 'J05 - FLC')
-- 			AND A.SIS_REPOSICION IN ('Reposicion x ASR', 'Informar a ASR')
-- 		)
-- 		OR (
-- 			A.DIVISION IN ('J06 - PANADERIA Y PASTELERIA', 'J07 - PLATOS PREPARADOS')
-- 			AND A.SIS_REPOSICION IN ('Reposicion x ASR')
-- 		)
-- 	)
-- 	-- AND COD_LOCAL not in (209,203,205,202,206,105,129,107,207)
-- GROUP BY B.MES_GROGORIANO


SELECT
	CUADRO_RESUMEN,
	CONVERT(NUMERIC(12, 2), SUM(NUM_OH_VALORIZADO) / NULLIF (SUM(NUM_VTA_SEM_X_PERFIL), 0) * 100) AS INSTOCK_G,
	CONVERT(VARCHAR(10), CONVERT(NUMERIC(12, 2), SUM(NUM_OH_VALORIZADO) / NULLIF (SUM(NUM_VTA_SEM_X_PERFIL), 0) * 100)) + '%' AS INSTOCK,
	MES FECHA
FROM (

	SELECT 
		MES,
		NUM_OH_VALORIZADO,
		NUM_VTA_SEM_X_PERFIL,
		CUADRO_RESUMEN,
		FILTRO
	FROM (
		SELECT 
			F.MES_GROGORIANO MES,
			SUM(NUM_OH_VALORIZADO) NUM_OH_VALORIZADO,
			SUM(NUM_VTA_SEM_X_PERFIL) NUM_VTA_SEM_X_PERFIL,
			1 [INSTOCK COMPAÑIA],
			CASE WHEN TOP_500 = 'TOP500' THEN 1 END TOP500,
			CASE WHEN TOP_2100 = 'TOP2100' THEN 1 END TOP2100,
			CASE WHEN EDLP = 'X' THEN 1 END EDLP
			-- CASE WHEN MMPP = 'MMPP' THEN 1 END MMPP
		FROM INSTOCK_OPT.dbo.MAIL_INSTOCK_SUBDEP_2_TOP_DIV I
		INNER JOIN INSTOCK_OPT.dbo.DHW_MES_GC AS F
			ON F.FECHA = CONVERT(DATE, FECHA_ACTUALIZ)
		WHERE
			(
				(DIVISION IN ('J01 - PGC COMESTIBLE', 'J02 - PGC NO COMESTIBLE', 'J05 - FLC') AND SIS_REPOSICION IN ('Reposicion x ASR','Informar a ASR'))
				OR (DIVISION IN ('J06 - PANADERIA Y PASTELERIA','J07 - PLATOS PREPARADOS')AND SIS_REPOSICION in ('Reposicion x ASR'))
			)
		GROUP BY 
			MES_GROGORIANO,
			TOP_2100,
			TOP_500,
			EDLP
			-- MMPP
	) I
	UNPIVOT (
		FILTRO FOR CUADRO_RESUMEN IN (
			[INSTOCK COMPAÑIA],
			TOP500,
			TOP2100,
			EDLP
			-- MMPP
		)
	) AS unpvt

) AS I
GROUP BY 
	CUADRO_RESUMEN, 
	MES
