USE [RepNonFood]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:			<Sebastian Cornejo>
-- Create date: <2019/10/17>
-- Update date: <---/--/-->
-- Description:	<Carga datos base para informe Non Food ASR>
-- ?? EXEC [RepNonFood].[dbo].[SP_NF_BASE_ASR__CARGA_BASE_DWH]
-- !! SE BORRO EL SP, SE ULTILIZARA TABLA [INFORMES3].[dbo].[N_OTB_2_DATOS_ASR]
-- =============================================
DROP PROCEDURE [dbo].[SP_NF_BASE_ASR__CARGA_BASE_DWH]
AS
BEGIN

	BEGIN TRY

		TRUNCATE DROP TABLE [RepNonFood].[dbo].[NF_BASE_ASR_DWH]

		-- !! Consulta contiene 2 MM de datos aprox.

		INSERT INTO [RepNonFood].[dbo].[NF_BASE_ASR_DWH]

		SELECT /* TOP 10 */
			A.CUSTCOL_7 SKU,
			A.DESC_SKU DESC_SKU,
			A.COD_LOCALFISICO COD_LOCAL,
			A.DESC_LOCALFISICO DESC_LOCAL,
			A.CUSTCOL_1 DIVISION,
			A.CUSTCOL_2 DEPARTAMENTO,
			A.CUSTCOL_3 SUBDEPARTAMENTO,
			A.CUSTCOL_4 CLASE,
			A.CUSTCOL_5 SUBCLASE,
			A.DESC_ESTADO ESTADO,
			A.DESC_PROCEDENCIA PROCEDENCIA,
			CONVERT(NUMERIC,A.F_CANT) CASEPACK,
			A.COD_SISTREPOSICION SIST_REPO,
			A.COD_METABASTECIMIENTO METODO_ABAST,
			A.INDICESURTIDO SURTIDO,
			A.WJXBFS1 OH_ASR,
			A.WJXBFS2 OO_ASR,
			A.WJXBFS3 DEMAND,
			CASE
				WHEN A.WJXBFS1 IS NULL THEN 'SUBIR_ASR'
				ELSE 'OK'
			END SUBIR_A_ASR,
			CASE
				WHEN  ISNULL(A.WJXBFS1,0) > 0 THEN 1
				ELSE 0
			END INDICADOR
		FROM OPENQUERY(DW, '
				SELECT *
				FROM dssmkpmmcl.NF_BASE_ASR
				--WHERE COD_LOCALFISICO = 104
			') A 
		WHERE A.COD_LOCALFISICO NOT LIKE '4%'

	END TRY

	BEGIN CATCH

		EXEC [ACTUALIZABLES].dbo.SP_GetErrorInfo 201, 'Job', 'NF_BASE_ASR__CARGA_BASE_DWH', '[RepNonFood].[dbo].[NF_BASE_ASR_DWH]'

	END CATCH

END
