DECLARE @fecha_inicio DATE, @fecha_termino DATE
	SET @fecha_inicio = '2019-10-01'
	SET @fecha_termino = CONVERT(DATE,GETDATE()-1)

SELECT 
		SF.[LOCAL],
		SF.AÑO_MES,
		SF.SUGERIDO,
		SF.CORREGIDO,
		VF.VENTA
	FROM (
		SELECT DISTINCT 
			S.[AÑO_MES],
			S.[LOCAL],
			SUM(S.[SUGERIDO]) AS SUGERIDO,
			SUM(S.[CORREGIDO]) AS CORREGIDO
			FROM (
				SELECT 
					[ID_USUARIO]
					,[LOCAL]
					,SUM([SUGERIDO_CAJAS]*[CASEPACK]) AS SUGERIDO
					,SUM(ISNULL([CORREGIDO]*[CASEPACK], (SUGERIDO_CAJAS)*[CASEPACK])) AS CORREGIDO
					,LEFT(CONVERT(VARCHAR,[DIA_LLEGADA],112),6) AS AÑO_MES
					,[DIA_LLEGADA]
					FROM [10.195.254.201].[SUGERIDO_COMPRA].[dbo].[SUGERIDO_CALCULADO_F]
					WHERE 
						[DIA_LLEGADA] BETWEEN @fecha_inicio AND @fecha_termino
					GROUP BY 
						[ID_USUARIO]
						,[LOCAL]
						,LEFT(CONVERT(VARCHAR,[DIA_LLEGADA],112),6)
						,[DIA_LLEGADA]
				
				UNION ALL

				SELECT 
						[ID_USUARIO]
						,[LOCAL]
						,SUM([SUGERIDO_CAJAS]*[CASEPACK]) AS SUGERIDO
						,SUM(ISNULL([CORREGIDO]*[CASEPACK], (SUGERIDO_CAJAS)*[CASEPACK])) AS CORREGIDO
						,LEFT(CONVERT(VARCHAR,[DIA_LLEGADA],112),6) AS AÑO_MES
						,[DIA_LLEGADA]
					FROM [SUGERIDO_COMPRA].[dbo].[SUGERIDO_CALCULADO_F]
					WHERE 
						[DIA_LLEGADA] BETWEEN @fecha_inicio AND @fecha_termino
					GROUP BY 
						[ID_USUARIO]
						,[LOCAL]
						,LEFT(CONVERT(VARCHAR,[DIA_LLEGADA],112),6)
						,[DIA_LLEGADA]
			) AS S
			GROUP BY 
				S.[AÑO_MES],
				S.[LOCAL]
		) AS SF
		LEFT JOIN (
			SELECT 
					V.[COD_LOCALFISICO]
					,LEFT(CONVERT(VARCHAR,V.[ID_DIAANALISIS],112),6) AS AÑO_MES
					,ROUND(SUM(V.[UN_VENTA]), 0) AS VENTA
				FROM (
					SELECT DISTINCT *
						FROM [SUGERIDO_COMPRA].[dbo].[FFYVV_VTA_SEMANAS]
				) AS V
				WHERE V.ID_DIAANALISIS BETWEEN @fecha_inicio AND @fecha_termino
				GROUP BY 
					V.[COD_LOCALFISICO],
					LEFT(CONVERT(VARCHAR,V.[ID_DIAANALISIS],112),6)
		) AS VF
			ON SF.AÑO_MES = VF.AÑO_MES
			AND SF.[LOCAL] = VF.COD_LOCALFISICO