USE [INFORMES3]
GO
/****** Object:  StoredProcedure [dbo].[SP_GRAFICO_INSTOCK_SEMANA_v2]    Script Date: 27-11-2019 17:51:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author: Sebastian Cornejo
-- Created at: 2019/11/12
-- Updated at: 2019/11/27
-- Description: Datos para Grafico Instock Evolutivo Semanal 
-- 	-> Se agrega filtro de tiendas cerradas con la tabla TIEDAS_ASENTADAS
-- ?? EXEC [INFORMES3].[dbo].[SP_GRAFICO_INSTOCK_SEMANA_v2]
-- =============================================
ALTER PROCEDURE [dbo].[SP_GRAFICO_INSTOCK_SEMANA_v2]

AS

BEGIN

	DECLARE @semanas INT
	SET @semanas = 4


	SELECT *
	FROM (
		SELECT 
			CUADRO_RESUMEN,
			SEMANA,
			INSTOCK
		FROM
			(SELECT
				CONVERT(VARCHAR(MAX), TOP_500) TOP_500,
				CONVERT(VARCHAR(MAX), TOP_2100) TOP_2100,
				NULL CIA,
				SEMANA,
				CONVERT(NUMERIC(12,1),SUM([NUM_OH_VALORIZADO])/NULLIF(SUM([NUM_VTA_SEM_X_PERFIL]),0)*100) AS INSTOCK
			FROM [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA_HISTORIA]
			WHERE 
				SEMANA IN (DATEPART(WW, GETDATE())+DATEPART(YYYY, GETDATE())*100)
				AND COD_LOCAL NOT IN (SELECT * FROM [INFORMES3].[dbo].[TIENDAS_ASENTADAS])
			GROUP BY
				SEMANA,
				TOP_500,
				TOP_2100

			UNION ALL

			SELECT
				NULL TOP_500,
				NULL TOP_2100,
				CONVERT(VARCHAR(MAX), 'CIA') CIA,
				SEMANA,
				CONVERT(NUMERIC(12,1),SUM([NUM_OH_VALORIZADO])/NULLIF(SUM([NUM_VTA_SEM_X_PERFIL]),0)*100) AS INSTOCK
			FROM [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA_HISTORIA]
			WHERE 
				SEMANA IN (DATEPART(WW, GETDATE())+DATEPART(YYYY, GETDATE())*100)
				AND COD_LOCAL NOT IN (SELECT * FROM [INFORMES3].[dbo].[TIENDAS_ASENTADAS])
			GROUP BY
				SEMANA
			
			UNION ALL
			
			SELECT 
				CONVERT(VARCHAR(MAX), TOP_500) TOP_500,
				CONVERT(VARCHAR(MAX), TOP_2100) TOP_2100,
				NULL CIA,
				SEMANA,
				CONVERT(NUMERIC(12,1),SUM([NUM_OH_VALORIZADO])/NULLIF(SUM([NUM_VTA_SEM_X_PERFIL]),0)*100) INSTOCK
			FROM [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA_RESUMEN_SEMANA]
			WHERE
				SEMANA BETWEEN (DATEPART(WW, GETDATE())-@semanas+DATEPART(YYYY, GETDATE())*100) AND (DATEPART(WW, GETDATE())-1+DATEPART(YYYY, GETDATE())*100)
				AND COD_LOCAL NOT IN (SELECT * FROM [INFORMES3].[dbo].[TIENDAS_ASENTADAS])
			GROUP BY
				SEMANA,
				TOP_500,
				TOP_2100

			UNION ALL

			SELECT 
				NULL TOP_500,
				NULL TOP_2100,
				CONVERT(VARCHAR(MAX), 'CIA') CIA,
				SEMANA,
				CONVERT(NUMERIC(12,1),SUM([NUM_OH_VALORIZADO])/NULLIF(SUM([NUM_VTA_SEM_X_PERFIL]),0)*100) INSTOCK
			FROM [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA_RESUMEN_SEMANA]
			WHERE
				SEMANA BETWEEN (DATEPART(WW, GETDATE())-@semanas+DATEPART(YYYY, GETDATE())*100) AND (DATEPART(WW, GETDATE())-1+DATEPART(YYYY, GETDATE())*100)
				AND COD_LOCAL NOT IN (SELECT * FROM [INFORMES3].[dbo].[TIENDAS_ASENTADAS])
			GROUP BY
				SEMANA
			) T
		UNPIVOT (
			INSTOCK_ FOR CUADRO_RESUMEN IN
				(TOP_500, TOP_2100, CIA)
		) AS UNPVT
	) AS T
	PIVOT (
		SUM(T.INSTOCK)
		FOR T.CUADRO_RESUMEN IN (CIA, TOP_500, TOP_2100)
	) AS pivotTable

END
