USE [INFORMES3]
GO
/****** Object:  StoredProcedure [dbo].[SP_NUEVO_INSTOCK_MAIL_CUADRO_RESUMEN]    Script Date: 21-11-2019 15:22:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	EXEC SP_NUEVO_INSTOCK_MAIL_CUADRO_RESUMEN
-- =============================================
ALTER PROCEDURE [dbo].[SP_NUEVO_INSTOCK_MAIL_CUADRO_RESUMEN]


AS
BEGIN

TRUNCATE TABLE [INFORMES3].[dbo].[NUEVO_INSTOCK_MAIL_CUADRO_RESUMEN]
INSERT INTO [INFORMES3].[dbo].[NUEVO_INSTOCK_MAIL_CUADRO_RESUMEN]
           ([CUADRO_RESUMEN]
           ,[SEM4]
           ,[SEM3]
           ,[SEM2]
           ,[SEM1]
           ,[SEM_ACTUAL])
SELECT
 TB_CUADRO_RESUMEN.CUADRO_RESUMEN,
 TB_CUADRO_RESUMEN.SEM4,
 TB_CUADRO_RESUMEN.SEM3,
 TB_CUADRO_RESUMEN.SEM2,
 TB_CUADRO_RESUMEN.SEM1,
 TB_CUADRO_RESUMEN.SEM_ACTUAL
FROM
(
--------------
--  TOP500  --
--------------

SELECT 
	A.CUADRO_RESUMEN,
	E.INSTOCK AS SEM4,
	D.INSTOCK AS SEM3,
	C.INSTOCK AS SEM2,
	B.INSTOCK AS SEM1,
	A.INSTOCK AS SEM_ACTUAL

FROM (
	SELECT 
		'TOP500' AS CUADRO_RESUMEN
		--,SEMANA
		,''+CONVERT(VARCHAR(10),CONVERT(NUMERIC(12,1),SUM([NUM_OH_VALORIZADO])/nullif(SUM([NUM_VTA_SEM_X_PERFIL]),0)*100))+'%' AS INSTOCK
	FROM  [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA_HISTORIA]
	WHERE 
		(
			TOP_500='TOP500' 
			AND SEMANA = (
				CASE 
					WHEN DATEPART(ww,GETDATE())<10 
						THEN (SELECT ''+CAST(DATEPART(YYYY,GETDATE()) AS NVARCHAR(MAX))+'0'+CAST(DATEPART(ww,GETDATE()) AS NVARCHAR(MAX))+'')
					ELSE (SELECT ''+CAST(DATEPART(YYYY,GETDATE()) AS NVARCHAR(MAX))+''+CAST(DATEPART(ww,GETDATE()) AS NVARCHAR(MAX))+'') 
				END
			) 
			AND DIVISION IN ('J01 - PGC COMESTIBLE','J02 - PGC NO COMESTIBLE','J05 - FLC')
		) 
		AND COD_LOCAL not in (209,203,205,202,206,105,129,107,207)
) as A
JOIN

(SELECT 'TOP500' AS CUADRO_RESUMEN
        --,SEMANA
        ,''+CONVERT(VARCHAR(10),CONVERT(NUMERIC(12,1),SUM([NUM_OH_VALORIZADO])/nullif(SUM([NUM_VTA_SEM_X_PERFIL]),0)*100))+'%'		AS INSTOCK
         FROM  [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA_RESUMEN_SEMANA] 
        
         WHERE (TOP_500='TOP500' AND SEMANA= (CASE WHEN DATEPART(ww,GETDATE()-7)<10 THEN (select ''+CAST(DATEPART(YYYY,GETDATE()-7) AS NVARCHAR(MAX))+'0'+CAST(DATEPART(ww,GETDATE()-7) AS NVARCHAR(MAX))+'')
										ELSE (select ''+CAST(DATEPART(YYYY,GETDATE()-7) AS NVARCHAR(MAX))+''+CAST(DATEPART(ww,GETDATE()-7) AS NVARCHAR(MAX))+'') END )) AND COD_LOCAL not in (209,203,205,202,206,105,129,107,207)) AS B ON B.CUADRO_RESUMEN=A.CUADRO_RESUMEN JOIN
(SELECT 'TOP500' AS CUADRO_RESUMEN
        --,SEMANA
        ,''+CONVERT(VARCHAR(10),CONVERT(NUMERIC(12,1),SUM([NUM_OH_VALORIZADO])/nullif(SUM([NUM_VTA_SEM_X_PERFIL]),0)*100))+'%'		AS INSTOCK
         FROM  [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA_RESUMEN_SEMANA] 
        
         WHERE (TOP_500='TOP500' AND SEMANA= (CASE WHEN DATEPART(ww,GETDATE()-13)<10 THEN (select ''+CAST(DATEPART(YYYY,GETDATE()-13) AS NVARCHAR(MAX))+'0'+CAST(DATEPART(ww,GETDATE()-13) AS NVARCHAR(MAX))+'')
										ELSE (select ''+CAST(DATEPART(YYYY,GETDATE()-13) AS NVARCHAR(MAX))+''+CAST(DATEPART(ww,GETDATE()-13) AS NVARCHAR(MAX))+'') END )) 
                                        AND COD_LOCAL not in (209,203,205,202,206,105,129,107,207)) AS C ON C.CUADRO_RESUMEN=A.CUADRO_RESUMEN JOIN
		
(SELECT 'TOP500' AS CUADRO_RESUMEN
        --,SEMANA
        ,''+CONVERT(VARCHAR(10),CONVERT(NUMERIC(12,1),SUM([NUM_OH_VALORIZADO])/nullif(SUM([NUM_VTA_SEM_X_PERFIL]),0)*100))+'%'		AS INSTOCK
         FROM  [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA_RESUMEN_SEMANA] 
        
         WHERE (TOP_500='TOP500' AND SEMANA= (CASE WHEN DATEPART(ww,GETDATE()-20)<10 THEN (select ''+CAST(DATEPART(YYYY,GETDATE()-20) AS NVARCHAR(MAX))+'0'+CAST(DATEPART(ww,GETDATE()-20) AS NVARCHAR(MAX))+'')
										ELSE (select ''+CAST(DATEPART(YYYY,GETDATE()-20) AS NVARCHAR(MAX))+''+CAST(DATEPART(ww,GETDATE()-20) AS NVARCHAR(MAX))+'') END ))
                                        AND COD_LOCAL not in (209,203,205,202,206,105,129,107,207)) AS D ON D.CUADRO_RESUMEN=A.CUADRO_RESUMEN JOIN
										
(SELECT 'TOP500' AS CUADRO_RESUMEN
        --,SEMANA
        ,''+CONVERT(VARCHAR(10),CONVERT(NUMERIC(12,1),SUM([NUM_OH_VALORIZADO])/nullif(SUM([NUM_VTA_SEM_X_PERFIL]),0)*100))+'%'		AS INSTOCK
         FROM  [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA_RESUMEN_SEMANA] 
        
         WHERE (TOP_500='TOP500' AND SEMANA= (CASE WHEN DATEPART(ww,GETDATE()-27)<10 THEN (select ''+CAST(DATEPART(YYYY,GETDATE()-27) AS NVARCHAR(MAX))+'0'+CAST(DATEPART(ww,GETDATE()-27) AS NVARCHAR(MAX))+'')
										ELSE (select ''+CAST(DATEPART(YYYY,GETDATE()-27) AS NVARCHAR(MAX))+''+CAST(DATEPART(ww,GETDATE()-27) AS NVARCHAR(MAX))+'') END ))
                                        AND COD_LOCAL not in (209,203,205,202,206,105,129,107,207)) AS E ON E.CUADRO_RESUMEN=A.CUADRO_RESUMEN 										

										
--------------
--  TOP2100  --
--------------
UNION


SELECT A.CUADRO_RESUMEN, E.INSTOCK AS SEM4,D.INSTOCK AS SEM3, C.INSTOCK AS SEM2, B.INSTOCK AS SEM1, A.INSTOCK AS SEM_ACTUAL
FROM (SELECT 'TOP2100' AS CUADRO_RESUMEN
        --,SEMANA
        ,''+CONVERT(VARCHAR(10),CONVERT(NUMERIC(12,1),SUM([NUM_OH_VALORIZADO])/nullif(SUM([NUM_VTA_SEM_X_PERFIL]),0)*100))+'%'		AS INSTOCK
         FROM  [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA_HISTORIA] 
        
         WHERE (TOP_2100='TOP2100' AND SEMANA= (CASE WHEN DATEPART(ww,GETDATE())<10 THEN (select ''+CAST(DATEPART(YYYY,GETDATE()) AS NVARCHAR(MAX))+'0'+CAST(DATEPART(ww,GETDATE()) AS NVARCHAR(MAX))+'')
										ELSE (select ''+CAST(DATEPART(YYYY,GETDATE()) AS NVARCHAR(MAX))+''+CAST(DATEPART(ww,GETDATE()) AS NVARCHAR(MAX))+'') END )AND DIVISION IN ('J01 - PGC COMESTIBLE','J02 - PGC NO COMESTIBLE','J05 - FLC')) AND COD_LOCAL not in (209,203,205,202,206,105,129,107,207)) as A JOIN

(SELECT 'TOP2100' AS CUADRO_RESUMEN
        --,SEMANA
        ,''+CONVERT(VARCHAR(10),CONVERT(NUMERIC(12,1),SUM([NUM_OH_VALORIZADO])/nullif(SUM([NUM_VTA_SEM_X_PERFIL]),0)*100))+'%'		AS INSTOCK
         FROM  [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA_RESUMEN_SEMANA] 
        
         WHERE (TOP_2100='TOP2100' AND SEMANA= (CASE WHEN DATEPART(ww,GETDATE()-7)<10 THEN (select ''+CAST(DATEPART(YYYY,GETDATE()-7) AS NVARCHAR(MAX))+'0'+CAST(DATEPART(ww,GETDATE()-7) AS NVARCHAR(MAX))+'')
										ELSE (select ''+CAST(DATEPART(YYYY,GETDATE()-7) AS NVARCHAR(MAX))+''+CAST(DATEPART(ww,GETDATE()-7) AS NVARCHAR(MAX))+'') END )) AND COD_LOCAL not in (209,203,205,202,206,105,129,107,207)) AS B ON B.CUADRO_RESUMEN=A.CUADRO_RESUMEN JOIN
										
(SELECT 'TOP2100' AS CUADRO_RESUMEN
        --,SEMANA
        ,''+CONVERT(VARCHAR(10),CONVERT(NUMERIC(12,1),SUM([NUM_OH_VALORIZADO])/nullif(SUM([NUM_VTA_SEM_X_PERFIL]),0)*100))+'%'		AS INSTOCK
         FROM  [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA_RESUMEN_SEMANA] 
        
         WHERE (TOP_2100='TOP2100' AND SEMANA= (CASE WHEN DATEPART(ww,GETDATE()-13)<10 THEN (select ''+CAST(DATEPART(YYYY,GETDATE()-13) AS NVARCHAR(MAX))+'0'+CAST(DATEPART(ww,GETDATE()-13) AS NVARCHAR(MAX))+'')
										ELSE (select ''+CAST(DATEPART(YYYY,GETDATE()-13) AS NVARCHAR(MAX))+''+CAST(DATEPART(ww,GETDATE()-13) AS NVARCHAR(MAX))+'') END )) 
                                        AND COD_LOCAL not in (209,203,205,202,206,105,129,107,207)) AS C ON C.CUADRO_RESUMEN=A.CUADRO_RESUMEN JOIN
		
(SELECT 'TOP2100' AS CUADRO_RESUMEN
        --,SEMANA
        ,''+CONVERT(VARCHAR(10),CONVERT(NUMERIC(12,1),SUM([NUM_OH_VALORIZADO])/nullif(SUM([NUM_VTA_SEM_X_PERFIL]),0)*100))+'%'		AS INSTOCK
         FROM  [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA_RESUMEN_SEMANA] 
        
         WHERE (TOP_2100='TOP2100' AND SEMANA= (CASE WHEN DATEPART(ww,GETDATE()-20)<10 THEN (select ''+CAST(DATEPART(YYYY,GETDATE()-20) AS NVARCHAR(MAX))+'0'+CAST(DATEPART(ww,GETDATE()-20) AS NVARCHAR(MAX))+'')
										ELSE (select ''+CAST(DATEPART(YYYY,GETDATE()-20) AS NVARCHAR(MAX))+''+CAST(DATEPART(ww,GETDATE()-20) AS NVARCHAR(MAX))+'') END ))
                                        AND COD_LOCAL not in (209,203,205,202,206,105,129,107,207)) AS D ON D.CUADRO_RESUMEN=A.CUADRO_RESUMEN JOIN
										
(SELECT 'TOP2100' AS CUADRO_RESUMEN
        --,SEMANA
        ,''+CONVERT(VARCHAR(10),CONVERT(NUMERIC(12,1),SUM([NUM_OH_VALORIZADO])/nullif(SUM([NUM_VTA_SEM_X_PERFIL]),0)*100))+'%'		AS INSTOCK
         FROM  [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA_RESUMEN_SEMANA] 
        
         WHERE (TOP_2100='TOP2100' AND SEMANA= (CASE WHEN DATEPART(ww,GETDATE()-27)<10 THEN (select ''+CAST(DATEPART(YYYY,GETDATE()-27) AS NVARCHAR(MAX))+'0'+CAST(DATEPART(ww,GETDATE()-27) AS NVARCHAR(MAX))+'')
										ELSE (select ''+CAST(DATEPART(YYYY,GETDATE()-27) AS NVARCHAR(MAX))+''+CAST(DATEPART(ww,GETDATE()-27) AS NVARCHAR(MAX))+'') END ))
                                        AND COD_LOCAL not in (209,203,205,202,206,105,129,107,207)) AS E ON E.CUADRO_RESUMEN=A.CUADRO_RESUMEN 										

	
											
--------------
--  MMPP  --
--------------
UNION


SELECT A.CUADRO_RESUMEN, E.INSTOCK AS SEM4,D.INSTOCK AS SEM3, C.INSTOCK AS SEM2, B.INSTOCK AS SEM1, A.INSTOCK AS SEM_ACTUAL
FROM (SELECT 'MMPP' AS CUADRO_RESUMEN
        --,SEMANA
        ,''+CONVERT(VARCHAR(10),CONVERT(NUMERIC(12,1),SUM([NUM_OH_VALORIZADO])/nullif(SUM([NUM_VTA_SEM_X_PERFIL]),0)*100))+'%'		AS INSTOCK
         FROM  [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA_HISTORIA] 
        
         WHERE (MMPP='MMPP' AND SEMANA= (CASE WHEN DATEPART(ww,GETDATE())<10 THEN (select ''+CAST(DATEPART(YYYY,GETDATE()) AS NVARCHAR(MAX))+'0'+CAST(DATEPART(ww,GETDATE()) AS NVARCHAR(MAX))+'')
										ELSE (select ''+CAST(DATEPART(YYYY,GETDATE()) AS NVARCHAR(MAX))+''+CAST(DATEPART(ww,GETDATE()) AS NVARCHAR(MAX))+'') END )AND DIVISION IN ('J01 - PGC COMESTIBLE','J02 - PGC NO COMESTIBLE','J05 - FLC')) AND COD_LOCAL not in (209,203,205,202,206,105,129,107,207)) as A JOIN

(SELECT 'MMPP' AS CUADRO_RESUMEN
        --,SEMANA
        ,''+CONVERT(VARCHAR(10),CONVERT(NUMERIC(12,1),SUM([NUM_OH_VALORIZADO])/nullif(SUM([NUM_VTA_SEM_X_PERFIL]),0)*100))+'%'		AS INSTOCK
         FROM  [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA_RESUMEN_SEMANA] 
        
         WHERE (MMPP='MMPP' AND SEMANA= (CASE WHEN DATEPART(ww,GETDATE()-7)<10 THEN (select ''+CAST(DATEPART(YYYY,GETDATE()-7) AS NVARCHAR(MAX))+'0'+CAST(DATEPART(ww,GETDATE()-7) AS NVARCHAR(MAX))+'')
										ELSE (select ''+CAST(DATEPART(YYYY,GETDATE()-7) AS NVARCHAR(MAX))+''+CAST(DATEPART(ww,GETDATE()-7) AS NVARCHAR(MAX))+'') END )) AND COD_LOCAL not in (209,203,205,202,206,105,129,107,207)) AS B ON B.CUADRO_RESUMEN=A.CUADRO_RESUMEN JOIN
										
(SELECT 'MMPP' AS CUADRO_RESUMEN
        --,SEMANA
        ,''+CONVERT(VARCHAR(10),CONVERT(NUMERIC(12,1),SUM([NUM_OH_VALORIZADO])/nullif(SUM([NUM_VTA_SEM_X_PERFIL]),0)*100))+'%'		AS INSTOCK
         FROM  [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA_RESUMEN_SEMANA] 
        
         WHERE (MMPP='MMPP' AND SEMANA= (CASE WHEN DATEPART(ww,GETDATE()-13)<10 THEN (select ''+CAST(DATEPART(YYYY,GETDATE()-13) AS NVARCHAR(MAX))+'0'+CAST(DATEPART(ww,GETDATE()-13) AS NVARCHAR(MAX))+'')
										ELSE (select ''+CAST(DATEPART(YYYY,GETDATE()-13) AS NVARCHAR(MAX))+''+CAST(DATEPART(ww,GETDATE()-13) AS NVARCHAR(MAX))+'') END ))
                                        AND COD_LOCAL not in (209,203,205,202,206,105,129,107,207)) AS C ON C.CUADRO_RESUMEN=A.CUADRO_RESUMEN JOIN
		
(SELECT 'MMPP' AS CUADRO_RESUMEN
        --,SEMANA
        ,''+CONVERT(VARCHAR(10),CONVERT(NUMERIC(12,1),SUM([NUM_OH_VALORIZADO])/nullif(SUM([NUM_VTA_SEM_X_PERFIL]),0)*100))+'%'		AS INSTOCK
         FROM  [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA_RESUMEN_SEMANA] 
        
         WHERE (MMPP='MMPP' AND SEMANA= (CASE WHEN DATEPART(ww,GETDATE()-20)<10 THEN (select ''+CAST(DATEPART(YYYY,GETDATE()-20) AS NVARCHAR(MAX))+'0'+CAST(DATEPART(ww,GETDATE()-20) AS NVARCHAR(MAX))+'')
										ELSE (select ''+CAST(DATEPART(YYYY,GETDATE()-20) AS NVARCHAR(MAX))+''+CAST(DATEPART(ww,GETDATE()-20) AS NVARCHAR(MAX))+'') END ))
                                        AND COD_LOCAL not in (209,203,205,202,206,105,129,107,207)) AS D ON D.CUADRO_RESUMEN=A.CUADRO_RESUMEN JOIN
										
(SELECT 'MMPP' AS CUADRO_RESUMEN
        --,SEMANA
        ,''+CONVERT(VARCHAR(10),CONVERT(NUMERIC(12,1),SUM([NUM_OH_VALORIZADO])/nullif(SUM([NUM_VTA_SEM_X_PERFIL]),0)*100))+'%'		AS INSTOCK
         FROM  [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA_RESUMEN_SEMANA] 
        
         WHERE (MMPP='MMPP' AND SEMANA= (CASE WHEN DATEPART(ww,GETDATE()-27)<10 THEN (select ''+CAST(DATEPART(YYYY,GETDATE()-27) AS NVARCHAR(MAX))+'0'+CAST(DATEPART(ww,GETDATE()-27) AS NVARCHAR(MAX))+'')
										ELSE (select ''+CAST(DATEPART(YYYY,GETDATE()-27) AS NVARCHAR(MAX))+''+CAST(DATEPART(ww,GETDATE()-27) AS NVARCHAR(MAX))+'') END ))AND COD_LOCAL not in (209,203,205,202,206,105,129,107,207)) AS E ON E.CUADRO_RESUMEN=A.CUADRO_RESUMEN 										

----------
-- PGC ---
----------
UNION

SELECT A.CUADRO_RESUMEN,  E.INSTOCK AS SEM4,D.INSTOCK AS SEM3, C.INSTOCK AS SEM2, B.INSTOCK AS SEM1, A.INSTOCK AS SEM_ACTUAL
FROM
(SELECT     'PGC' AS CUADRO_RESUMEN
           --SEMANA ACTUAL
           , '' + CONVERT(VARCHAR(10), CONVERT(NUMERIC(12, 1), SUM(NUM_OH_VALORIZADO) / NULLIF (SUM(NUM_VTA_SEM_X_PERFIL), 0)* 100)) + '%' AS INSTOCK
FROM         INSTOCK_NUEVA_PLANILLA_HISTORIA AS A
WHERE     ((DIVISION IN ('J01 - PGC COMESTIBLE')) AND (SIS_REPOSICION IN ('Reposicion x ASR', 'Informar a ASR')) AND (SEMANA = (CASE WHEN DATEPART(ww, GETDATE()) < 10 THEN
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE()) AS NVARCHAR(MAX)) + '0' + CAST(DATEPART(ww, GETDATE()) AS NVARCHAR(MAX)) + '') ELSE
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE()) AS NVARCHAR(MAX)) + '' + CAST(DATEPART(ww, GETDATE()) AS NVARCHAR(MAX)) + '') END)) OR
                      (DIVISION IN ('J02 - PGC NO COMESTIBLE')) AND (SIS_REPOSICION IN ('Reposicion x ASR')) AND (SEMANA = (CASE WHEN DATEPART(ww, GETDATE())< 10 THEN
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE()) AS NVARCHAR(MAX)) + '0' + CAST(DATEPART(ww, GETDATE()) AS NVARCHAR(MAX)) + '') ELSE
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE()) AS NVARCHAR(MAX)) + '' + CAST(DATEPART(ww, GETDATE()) AS NVARCHAR(MAX)) + '') END))) AND COD_LOCAL not in (209,203,205,202,206,105,129,107,207)) AS A JOIN


(SELECT     'PGC' AS CUADRO_RESUMEN
           --SEMANA 1
           , '' + CONVERT(VARCHAR(10), CONVERT(NUMERIC(12, 1), SUM(NUM_OH_VALORIZADO) / NULLIF (SUM(NUM_VTA_SEM_X_PERFIL), 0)* 100)) + '%' AS INSTOCK
FROM         INSTOCK_NUEVA_PLANILLA_RESUMEN_SEMANA AS A
WHERE     ((DIVISION IN ('J01 - PGC COMESTIBLE')) AND (SIS_REPOSICION IN ('Reposicion x ASR', 'Informar a ASR')) AND (SEMANA = (CASE WHEN DATEPART(ww, GETDATE() 
                      - 7) < 10 THEN
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE() - 7) AS NVARCHAR(MAX)) + '0' + CAST(DATEPART(ww, GETDATE() - 7) AS NVARCHAR(MAX)) + '') ELSE
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE() - 7) AS NVARCHAR(MAX)) + '' + CAST(DATEPART(ww, GETDATE() - 7) AS NVARCHAR(MAX)) + '') END)) OR
                      (DIVISION IN ('J02 - PGC NO COMESTIBLE')) AND (SIS_REPOSICION IN ('Reposicion x ASR')) AND (SEMANA = (CASE WHEN DATEPART(ww, GETDATE() - 7) 
                      < 10 THEN
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE() - 7) AS NVARCHAR(MAX)) + '0' + CAST(DATEPART(ww, GETDATE() - 7) AS NVARCHAR(MAX)) + '') ELSE
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE() - 7) AS NVARCHAR(MAX)) + '' + CAST(DATEPART(ww, GETDATE() - 7) AS NVARCHAR(MAX)) + '') END))) AND COD_LOCAL not in (209,203,205,202,206,105,129,107,207)) AS B ON B.CUADRO_RESUMEN = A.CUADRO_RESUMEN JOIN

(SELECT     'PGC' AS CUADRO_RESUMEN
           --SEMANA 2
           , '' + CONVERT(VARCHAR(10), CONVERT(NUMERIC(12, 1), SUM(NUM_OH_VALORIZADO) / NULLIF (SUM(NUM_VTA_SEM_X_PERFIL), 0)* 100)) + '%' AS INSTOCK
FROM         INSTOCK_NUEVA_PLANILLA_RESUMEN_SEMANA AS A
WHERE     ((DIVISION IN ('J01 - PGC COMESTIBLE')) AND (SIS_REPOSICION IN ('Reposicion x ASR', 'Informar a ASR')) AND (SEMANA = (CASE WHEN DATEPART(ww, GETDATE() 
                      -13) < 10 THEN
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE() -13) AS NVARCHAR(MAX)) + '0' + CAST(DATEPART(ww, GETDATE() -13) AS NVARCHAR(MAX)) + '') ELSE
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE() -13) AS NVARCHAR(MAX)) + '' + CAST(DATEPART(ww, GETDATE() -13) AS NVARCHAR(MAX)) + '') END)) OR
                      (DIVISION IN ('J02 - PGC NO COMESTIBLE')) AND (SIS_REPOSICION IN ('Reposicion x ASR')) AND (SEMANA = (CASE WHEN DATEPART(ww, GETDATE() -13) 
                      < 10 THEN
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE() -13) AS NVARCHAR(MAX)) + '0' + CAST(DATEPART(ww, GETDATE() -13) AS NVARCHAR(MAX)) + '') ELSE
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE() -13) AS NVARCHAR(MAX)) + '' + CAST(DATEPART(ww, GETDATE() -13) AS NVARCHAR(MAX)) + '') END)))
                          AND COD_LOCAL not in (209,203,205,202,206,105,129,107,207)) AS C ON C.CUADRO_RESUMEN=A.CUADRO_RESUMEN JOIN

(SELECT     'PGC' AS CUADRO_RESUMEN
           --SEMANA 3
           , '' + CONVERT(VARCHAR(10), CONVERT(NUMERIC(12, 1), SUM(NUM_OH_VALORIZADO) / NULLIF (SUM(NUM_VTA_SEM_X_PERFIL), 0)* 100)) + '%' AS INSTOCK
FROM         INSTOCK_NUEVA_PLANILLA_RESUMEN_SEMANA AS A
WHERE     ((DIVISION IN ('J01 - PGC COMESTIBLE')) AND (SIS_REPOSICION IN ('Reposicion x ASR', 'Informar a ASR')) AND (SEMANA = (CASE WHEN DATEPART(ww, GETDATE() 
                      - 20) < 10 THEN
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE() - 20) AS NVARCHAR(MAX)) + '0' + CAST(DATEPART(ww, GETDATE() - 20) AS NVARCHAR(MAX)) + '') ELSE
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE() - 20) AS NVARCHAR(MAX)) + '' + CAST(DATEPART(ww, GETDATE() - 20) AS NVARCHAR(MAX)) + '') END)) OR
                      (DIVISION IN ('J02 - PGC NO COMESTIBLE')) AND (SIS_REPOSICION IN ('Reposicion x ASR')) AND (SEMANA = (CASE WHEN DATEPART(ww, GETDATE() - 20) 
                      < 10 THEN
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE() - 20) AS NVARCHAR(MAX)) + '0' + CAST(DATEPART(ww, GETDATE() - 20) AS NVARCHAR(MAX)) + '') ELSE
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE() - 20) AS NVARCHAR(MAX)) + '' + CAST(DATEPART(ww, GETDATE() - 20) AS NVARCHAR(MAX)) + '') END)))
                          AND COD_LOCAL not in (209,203,205,202,206,105,129,107,207)) AS D ON D.CUADRO_RESUMEN=A.CUADRO_RESUMEN JOIN

(SELECT     'PGC' AS CUADRO_RESUMEN
           --SEMANA 4
           , '' + CONVERT(VARCHAR(10), CONVERT(NUMERIC(12, 1), SUM(NUM_OH_VALORIZADO) / NULLIF (SUM(NUM_VTA_SEM_X_PERFIL), 0)* 100)) + '%' AS INSTOCK
FROM         INSTOCK_NUEVA_PLANILLA_RESUMEN_SEMANA AS A
WHERE     ((DIVISION IN ('J01 - PGC COMESTIBLE')) AND (SIS_REPOSICION IN ('Reposicion x ASR', 'Informar a ASR')) AND (SEMANA = (CASE WHEN DATEPART(ww, GETDATE() 
                      - 27) < 10 THEN
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE() - 27) AS NVARCHAR(MAX)) + '0' + CAST(DATEPART(ww, GETDATE() - 27) AS NVARCHAR(MAX)) + '') ELSE
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE() - 27) AS NVARCHAR(MAX)) + '' + CAST(DATEPART(ww, GETDATE() - 27) AS NVARCHAR(MAX)) + '') END)) OR
                      (DIVISION IN ('J02 - PGC NO COMESTIBLE')) AND (SIS_REPOSICION IN ('Reposicion x ASR')) AND (SEMANA = (CASE WHEN DATEPART(ww, GETDATE() - 27) 
                      < 10 THEN
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE() - 27) AS NVARCHAR(MAX)) + '0' + CAST(DATEPART(ww, GETDATE() - 27) AS NVARCHAR(MAX)) + '') ELSE
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE() - 27) AS NVARCHAR(MAX)) + '' + CAST(DATEPART(ww, GETDATE() - 27) AS NVARCHAR(MAX)) + '') END)))
                          AND COD_LOCAL not in (209,203,205,202,206,105,129,107,207)) AS E ON E.CUADRO_RESUMEN=A.CUADRO_RESUMEN



-----------------
-- PERECIBLES ---
-----------------
UNION

SELECT A.CUADRO_RESUMEN,  E.INSTOCK AS SEM4,D.INSTOCK AS SEM3, C.INSTOCK AS SEM2, B.INSTOCK AS SEM1, A.INSTOCK AS SEM_ACTUAL
FROM
(SELECT     'PERECIBLES' AS CUADRO_RESUMEN
           --SEMANA ACTUAL
           , '' + CONVERT(VARCHAR(10), CONVERT(NUMERIC(12, 1), SUM(NUM_OH_VALORIZADO) / NULLIF (SUM(NUM_VTA_SEM_X_PERFIL), 0)* 100)) + '%' AS INSTOCK
FROM         INSTOCK_NUEVA_PLANILLA_HISTORIA AS A
WHERE     ((A.DIVISION in ('J05 - FLC') and  A.SIS_REPOSICION in ('Reposicion x ASR')) AND (SEMANA = (CASE WHEN DATEPART(ww, GETDATE()) < 10 THEN
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE()) AS NVARCHAR(MAX)) + '0' + CAST(DATEPART(ww, GETDATE()) AS NVARCHAR(MAX)) + '') ELSE
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE()) AS NVARCHAR(MAX)) + '' + CAST(DATEPART(ww, GETDATE()) AS NVARCHAR(MAX)) + '') END)) OR
                      (A.DIVISION in ('J05 - FLC') and  A.SIS_REPOSICION in ('Reposicion x ASR')) AND (SEMANA = (CASE WHEN DATEPART(ww, GETDATE())< 10 THEN
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE()) AS NVARCHAR(MAX)) + '0' + CAST(DATEPART(ww, GETDATE()) AS NVARCHAR(MAX)) + '') ELSE
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE()) AS NVARCHAR(MAX)) + '' + CAST(DATEPART(ww, GETDATE()) AS NVARCHAR(MAX)) + '') END))) AND COD_LOCAL not in (209,203,205,202,206,105,129,107,207)) AS A JOIN


(SELECT      'PERECIBLES' AS CUADRO_RESUMEN
           --SEMANA 1
           , '' + CONVERT(VARCHAR(10), CONVERT(NUMERIC(12, 1), SUM(NUM_OH_VALORIZADO) / NULLIF (SUM(NUM_VTA_SEM_X_PERFIL), 0)* 100)) + '%' AS INSTOCK
FROM         INSTOCK_NUEVA_PLANILLA_RESUMEN_SEMANA AS A
WHERE     ((A.DIVISION in ('J05 - FLC','J06 - PANADERIA Y PASTELERIA','J07 - PLATOS PREPARADOS') and  A.SIS_REPOSICION in ('Reposicion x ASR')) AND (SEMANA = (CASE WHEN DATEPART(ww, GETDATE() 
                      - 7) < 10 THEN
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE() - 7) AS NVARCHAR(MAX)) + '0' + CAST(DATEPART(ww, GETDATE() - 7) AS NVARCHAR(MAX)) + '') ELSE
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE() - 7) AS NVARCHAR(MAX)) + '' + CAST(DATEPART(ww, GETDATE() - 7) AS NVARCHAR(MAX)) + '') END)) OR
                      (A.DIVISION in ('J05 - FLC','J06 - PANADERIA Y PASTELERIA','J07 - PLATOS PREPARADOS') and  A.SIS_REPOSICION in ('Reposicion x ASR')) AND (SEMANA = (CASE WHEN DATEPART(ww, GETDATE() - 7) 
                      < 10 THEN
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE() - 7) AS NVARCHAR(MAX)) + '0' + CAST(DATEPART(ww, GETDATE() - 7) AS NVARCHAR(MAX)) + '') ELSE
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE() - 7) AS NVARCHAR(MAX)) + '' + CAST(DATEPART(ww, GETDATE() - 7) AS NVARCHAR(MAX)) + '') END))) AND COD_LOCAL not in (209,203,205,202,206,105,129,107,207)) AS B ON B.CUADRO_RESUMEN = A.CUADRO_RESUMEN JOIN

(SELECT      'PERECIBLES' AS CUADRO_RESUMEN
           --SEMANA 2
           , '' + CONVERT(VARCHAR(10), CONVERT(NUMERIC(12, 1), SUM(NUM_OH_VALORIZADO) / NULLIF (SUM(NUM_VTA_SEM_X_PERFIL), 0)* 100)) + '%' AS INSTOCK
FROM         INSTOCK_NUEVA_PLANILLA_RESUMEN_SEMANA AS A
WHERE     ((A.DIVISION in ('J05 - FLC','J06 - PANADERIA Y PASTELERIA','J07 - PLATOS PREPARADOS') and  A.SIS_REPOSICION in ('Reposicion x ASR')) AND (SEMANA = (CASE WHEN DATEPART(ww, GETDATE() 
                      -13) < 10 THEN
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE() -13) AS NVARCHAR(MAX)) + '0' + CAST(DATEPART(ww, GETDATE() -13) AS NVARCHAR(MAX)) + '') ELSE
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE() -13) AS NVARCHAR(MAX)) + '' + CAST(DATEPART(ww, GETDATE() -13) AS NVARCHAR(MAX)) + '') END)) OR
                      (A.DIVISION in ('J05 - FLC','J06 - PANADERIA Y PASTELERIA','J07 - PLATOS PREPARADOS') and  A.SIS_REPOSICION in ('Reposicion x ASR')) AND (SEMANA = (CASE WHEN DATEPART(ww, GETDATE() -13) 
                      < 10 THEN
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE() -13) AS NVARCHAR(MAX)) + '0' + CAST(DATEPART(ww, GETDATE() -13) AS NVARCHAR(MAX)) + '') ELSE
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE() -13) AS NVARCHAR(MAX)) + '' + CAST(DATEPART(ww, GETDATE() -13) AS NVARCHAR(MAX)) + '') END)))
                          AND COD_LOCAL not in (209,203,205,202,206,105,129,107,207)) AS C ON C.CUADRO_RESUMEN=A.CUADRO_RESUMEN JOIN

(SELECT      'PERECIBLES' AS CUADRO_RESUMEN
           --SEMANA 3
           , '' + CONVERT(VARCHAR(10), CONVERT(NUMERIC(12, 1), SUM(NUM_OH_VALORIZADO) / NULLIF (SUM(NUM_VTA_SEM_X_PERFIL), 0)* 100)) + '%' AS INSTOCK
FROM         INSTOCK_NUEVA_PLANILLA_RESUMEN_SEMANA AS A
WHERE     ((A.DIVISION in ('J05 - FLC','J06 - PANADERIA Y PASTELERIA','J07 - PLATOS PREPARADOS') and  A.SIS_REPOSICION in ('Reposicion x ASR')) AND (SEMANA = (CASE WHEN DATEPART(ww, GETDATE() 
                      - 20) < 10 THEN
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE() - 20) AS NVARCHAR(MAX)) + '0' + CAST(DATEPART(ww, GETDATE() - 20) AS NVARCHAR(MAX)) + '') ELSE
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE() - 20) AS NVARCHAR(MAX)) + '' + CAST(DATEPART(ww, GETDATE() - 20) AS NVARCHAR(MAX)) + '') END)) OR
                      (A.DIVISION in ('J05 - FLC','J06 - PANADERIA Y PASTELERIA','J07 - PLATOS PREPARADOS') and  A.SIS_REPOSICION in ('Reposicion x ASR')) AND (SEMANA = (CASE WHEN DATEPART(ww, GETDATE() - 20) 
                      < 10 THEN
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE() - 20) AS NVARCHAR(MAX)) + '0' + CAST(DATEPART(ww, GETDATE() - 20) AS NVARCHAR(MAX)) + '') ELSE
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE() - 20) AS NVARCHAR(MAX)) + '' + CAST(DATEPART(ww, GETDATE() - 20) AS NVARCHAR(MAX)) + '') END)))
                          AND COD_LOCAL not in (209,203,205,202,206,105,129,107,207)) AS D ON D.CUADRO_RESUMEN=A.CUADRO_RESUMEN JOIN

(SELECT      'PERECIBLES' AS CUADRO_RESUMEN
           --SEMANA 4
           , '' + CONVERT(VARCHAR(10), CONVERT(NUMERIC(12, 1), SUM(NUM_OH_VALORIZADO) / NULLIF (SUM(NUM_VTA_SEM_X_PERFIL), 0)* 100)) + '%' AS INSTOCK
FROM         INSTOCK_NUEVA_PLANILLA_RESUMEN_SEMANA AS A
WHERE     ((A.DIVISION in ('J05 - FLC','J06 - PANADERIA Y PASTELERIA','J07 - PLATOS PREPARADOS') and  A.SIS_REPOSICION in ('Reposicion x ASR')) AND (SEMANA = (CASE WHEN DATEPART(ww, GETDATE() 
                      - 27) < 10 THEN
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE() - 27) AS NVARCHAR(MAX)) + '0' + CAST(DATEPART(ww, GETDATE() - 27) AS NVARCHAR(MAX)) + '') ELSE
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE() - 27) AS NVARCHAR(MAX)) + '' + CAST(DATEPART(ww, GETDATE() - 27) AS NVARCHAR(MAX)) + '') END)) OR
                      (A.DIVISION in ('J05 - FLC','J06 - PANADERIA Y PASTELERIA','J07 - PLATOS PREPARADOS') and  A.SIS_REPOSICION in ('Reposicion x ASR')) AND (SEMANA = (CASE WHEN DATEPART(ww, GETDATE() - 27) 
                      < 10 THEN
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE() - 27) AS NVARCHAR(MAX)) + '0' + CAST(DATEPART(ww, GETDATE() - 27) AS NVARCHAR(MAX)) + '') ELSE
                          (SELECT     '' + CAST(DATEPART(YYYY, GETDATE() - 27) AS NVARCHAR(MAX)) + '' + CAST(DATEPART(ww, GETDATE() - 27) AS NVARCHAR(MAX)) + '') END)))
                          AND COD_LOCAL not in (209,203,205,202,206,105,129,107,207)) AS E ON E.CUADRO_RESUMEN=A.CUADRO_RESUMEN

) AS TB_CUADRO_RESUMEN
END