TRUNCATE TABLE [INFORMES3].[dbo].[INSTOCK_RESUMEN_CARROS]

INSERT INTO [INFORMES3].[dbo].[INSTOCK_RESUMEN_CARROS]
  (
  [RESUMEN]
  ,[INSTOCK]
  )

SELECT *
--INTO [INFORMES3].[dbo].[INSTOCK_RESUMEN_CARROS]
FROM (SELECT 'PGC' AS RESUMEN, A.PGC AS INSTOCK
FROM (SELECT * FROM [INFORMES3].[dbo].[INSTOCK_DIARIO_RESUMEN] WHERE FECHA=CONVERT(DATE,GETDATE())) AS A

UNION

SELECT 'PERECIBLES' AS RESUMEN, A.PERECIBLES AS INSTOCK
  FROM (SELECT * FROM [INFORMES3].[dbo].[INSTOCK_DIARIO_RESUMEN] WHERE FECHA=CONVERT(DATE,GETDATE())) AS A 
 
UNION ALL

SELECT 'CARNES' AS RESUMEN, CONVERT(NUMERIC(18,2),LEFT(INSTOCK,5)) AS INSTOCK
FROM [INFORMES3].[dbo].[INSTOCK_CARNES_VACUNO_TOTAL]

UNION ALL

SELECT 'FFVV' AS RESUMEN, CONVERT(NUMERIC(18,2),LEFT(INSTOCK,4)) AS INSTOCK
FROM [INFORMES3].dbo.FFVV_INSTOCK_TOTAL_DIA) as T