-- TRUNCATE TABLE [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA]

-- INSERT INTO [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA]

SELECT 
	[NOM_PRODUCTO]
	,A.[SKU]
	,[CANTIDAD]
	,[COD_CLASIFICACION_SKU]
	,[ABC_2018]
	,[ABC_CL_2018]
	,[IND_SURTIDO]
	,[ESTADO]
	,[TOP_2100]
	,[TOP_500]
	,[MMPP]
	,[INV_NEGATIVO]
	,[NOM_LOCAL]
	,A.[COD_LOCAL]
	,[TIPO_TIENDA]
	,[NOMBRE_TIPO_TIENDA]
	,B.ZONA
	,B.[SUB GERENTE ZONAL]
	,[DIVISION]
	,A.[DEPARTAMENTO]
	,[SUBDEP]
	,A.[CLASE]
	,[SUBCLASE]
	,[COD_PROV]
	,[NOM_PROV]
	,[RUT]
	,[MARCA]
	,[METOD_ABAST]
	,[NUM_OH_VALORIZADO]
	,[NUM_OH_BINARIO_]
	,[NUM_VTA_SEM_X_PERFIL]
	,[VTA_PERDIDA_VP]
	,[OH_QUIEBRE]
	,[COSTO_INV_DISP_HOY]
	,[MONTO_VTA]
	,[CANTIDAD_SKUS]
	,[DEMANDA_SEMANAL]
	,CONVERT(DATE,[FECHA_ACTUALIZ]) AS FECHA_ACTUALIZ
	,[SIS_REPOSICION]
	,[PROCEDENCIA]
	,[RESPONSABLE]
	,PM.PM
	,ISNULL(PLANO.PLANOGRAMADO,'NO') AS PLANOGRAMADO
--INTO [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA]
FROM [INSTOCK_OPT].[dbo].[INSTOCK_NUEVA_PLANILLA] AS A 
LEFT JOIN [INFORMES3].dbo.INSTOCK_NUEVA_PLANILLA_ZONALES AS B 
	ON B.COD_LOCAL=A.COD_LOCAL
LEFT JOIN INFORMES3.dbo.instock_pm PM
	ON PM.CLASE = A.CLASE
LEFT JOIN (SELECT DISTINCT SALA,SKU,PLANOGRAMADO FROM [INFORMES3].[dbo].[SKU_PLANOGRAMADO_UNICO]) AS PLANO 
	ON PLANO.SKU=A.SKU
	AND PLANO.SALA=A.COD_LOCAL