/* Updated_at: 2019/11/20
 * Updated_by: Sebastian Cornejo
 * Detalle: Filtro de salas cerradas se hace en la vista
 */

-- INSERT INTO [INFORMES3].[dbo].[INSTOCK_DIARIO_NICO] (
-- 	[COD_LOCAL]
-- 	,[COMPAÑIA]
-- 	,[TOP500]
-- 	,[TOP2100]
-- 	,[PGC]
-- 	,[PERECIBLES]
-- 	,[MMPP]
-- 	,[IMPORTADOS]
-- 	,[FECHA]
-- )

-- SELECT C.COD_LOCAL
--        ,convert(NUMERIC(18,2),C.INSTOCK) AS COMPAÑIA
--        ,convert(NUMERIC(18,2),T5.INSTOCK) AS TOP500
--        ,convert(NUMERIC(18,2),T2.INSTOCK) AS TOP2100
--        ,PGC.INSTOCK AS PGC
--        ,PER.INSTOCK AS PERECIBLES
--        ,M.INSTOCK AS MMPP
--        ,I.INSTOCK AS IMPORTADOS
--       -- ,CONVERT(DATE,PGC.FECHA_ACTUALIZ) AS FECHA
--        ,CONVERT(DATE,C.FECHA_ACTUALIZ) AS FECHA
-- FROM (SELECT INSTOCK,COD_LOCAL,FECHA_ACTUALIZ FROM View_NUEVO_INSTOCK_TABLA_DIA_LOCAL WHERE [Cuadro Resumen]='COMPAÑÍA') AS C JOIN
-- 	 (SELECT INSTOCK,COD_LOCAL,FECHA_ACTUALIZ FROM dbo.View_NUEVO_INSTOCK_TABLA_DIA_LOCAL WHERE [Cuadro Resumen]='TOP500') AS T5 ON T5.FECHA_ACTUALIZ=C.FECHA_ACTUALIZ AND T5.COD_LOCAL=C.COD_LOCAL JOIN
--      (SELECT INSTOCK,COD_LOCAL,FECHA_ACTUALIZ FROM dbo.View_NUEVO_INSTOCK_TABLA_DIA_LOCAL WHERE [Cuadro Resumen]='TOP2100') AS T2 ON T2.FECHA_ACTUALIZ=C.FECHA_ACTUALIZ AND T2.COD_LOCAL=C.COD_LOCAL JOIN
--       (SELECT INSTOCK,COD_LOCAL,FECHA_ACTUALIZ FROM dbo.View_NUEVO_INSTOCK_TABLA_DIA_LOCAL WHERE [Cuadro Resumen]='PGC') AS PGC ON PGC.FECHA_ACTUALIZ=C.FECHA_ACTUALIZ AND PGC.COD_LOCAL=C.COD_LOCAL JOIN
--       (SELECT INSTOCK,COD_LOCAL,FECHA_ACTUALIZ FROM dbo.View_NUEVO_INSTOCK_TABLA_DIA_LOCAL WHERE [Cuadro Resumen]='PERECIBLES') AS PER ON PER.FECHA_ACTUALIZ=C.FECHA_ACTUALIZ AND PER.COD_LOCAL=C.COD_LOCAL JOIN
--       (SELECT INSTOCK,COD_LOCAL,FECHA_ACTUALIZ FROM dbo.View_NUEVO_INSTOCK_TABLA_DIA_LOCAL WHERE [Cuadro Resumen]='MMPP') AS M ON M.FECHA_ACTUALIZ=C.FECHA_ACTUALIZ AND M.COD_LOCAL=C.COD_LOCAL JOIN
--       (SELECT INSTOCK,COD_LOCAL,FECHA_ACTUALIZ FROM dbo.View_NUEVO_INSTOCK_TABLA_DIA_LOCAL WHERE [Cuadro Resumen]='IMPORTADOS') AS I ON I.FECHA_ACTUALIZ=C.FECHA_ACTUALIZ AND I.COD_LOCAL=C.COD_LOCAL



SELECT
	COD_LOCAL,
	COMPAÑÍA,
	TOP500,
	TOP2100,
	PGC,
	PERECIBLES,
	MMPP,
	IMPORTADOS,
	[FECHA_ACTUALIZ] FECHA
FROM dbo.View_NUEVO_INSTOCK_TABLA_DIA_LOCAL
PIVOT (
	SUM(INSTOCK)
	FOR [Cuadro Resumen] IN ([COMPAÑÍA], [TOP500], [TOP2100], [PGC], [PERECIBLES], [MMPP], [IMPORTADOS])
) AS pvtable