/* Updated_at: 2019/11/20
 * Updated_by: Sebastian Cornejo
 * Detalle: Filtro de salas cerradas se hace cruzando con la tabla TIENDAS_ASENTADAS
 */


-- INSERT INTO [INFORMES3].dbo.INSTOCK_NUEVA_PLANILLA_RESPONSABLES_DIARIO

-- SELECT 
-- 	semana
-- 	,[ZONA]
-- 	,[SUB GERENTE ZONAL]
-- 	,sum([NUM_OH_VALORIZADO]) [NUM_OH_VALORIZADO]
-- 	,sum([NUM_VTA_SEM_X_PERFIL]) [NUM_VTA_SEM_X_PERFIL]
-- 	,[FECHA_ACTUALIZ]
-- 	,[RESPONSABLE]
--  --INTO [INFORMES3].dbo.INSTOCK_NUEVA_PLANILLA_RESPONSABLES_DIARIO
-- FROM (
-- 	SELECT (
-- 		SELECT semana
-- 		FROM DHW_MES_GC
-- 		WHERE convert(DATE,FECHA) = CONVERT(DATE,FECHA_ACTUALIZ)
-- 	) semana
-- 	,[ZONA]
-- 	,[SUB GERENTE ZONAL]
-- 	,[NUM_OH_VALORIZADO]
-- 	,[NUM_VTA_SEM_X_PERFIL]
-- 	,[FECHA_ACTUALIZ]
-- 	,[RESPONSABLE]
--   FROM [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA]
-- 	WHERE COD_LOCAL NOT IN (209,203,205,202,206,105,129,107,207)
-- ) t
-- GROUP BY
-- 	semana
-- 	,[ZONA]
-- 	,[SUB GERENTE ZONAL]  
-- 	,[FECHA_ACTUALIZ]
-- 	,[RESPONSABLE]


SELECT
	semana
	,[ZONA]
	,[SUB GERENTE ZONAL]
	,sum([NUM_OH_VALORIZADO]) [NUM_OH_VALORIZADO]
	,sum([NUM_VTA_SEM_X_PERFIL]) [NUM_VTA_SEM_X_PERFIL]
	,[FECHA_ACTUALIZ]
	,[RESPONSABLE]
FROM (
	SELECT
	DATEPART(wk, FECHA_ACTUALIZ) + DATEPART(yy, FECHA_ACTUALIZ) * 100 AS SEMANA
	,I.[ZONA]
	,I.[SUB GERENTE ZONAL]
	,I.[NUM_OH_VALORIZADO]
	,I.[NUM_VTA_SEM_X_PERFIL]
	,I.[FECHA_ACTUALIZ]
	,I.[RESPONSABLE]
  FROM [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA] I
	LEFT JOIN [INFORMES3].[dbo].[TIENDAS_ASENTADAS] T
		ON I.COD_LOCAL = T.COD_LOCAL
	WHERE T.COD_LOCAL IS NULL
) t
GROUP BY
	semana
	,[ZONA]
	,[SUB GERENTE ZONAL]
	,[FECHA_ACTUALIZ]
	,[RESPONSABLE]