-- TRUNCATE TABLE [INFORMES3].[dbo].[INSTOCK_CARNES_POLLO_LOCAL_ASISTIDO]

-- INSERT INTO [INFORMES3].[dbo].[INSTOCK_CARNES_POLLO_LOCAL_ASISTIDO] (
-- 	[COD_LOCALFISICO]
-- 	,[NOM_LOCAL]
-- 	,[INSTOCK_NUM]
-- )

-- SELECT [COD_LOCAL]
--        ,[NOM_LOCAL]  
--        --,SUBDEP
--        , CASE WHEN (SUM([NUM_VTA_SEM_X_PERFIL]) IS NULL OR SUM([NUM_VTA_SEM_X_PERFIL])<=0) THEN 0
--            ELSE CONVERT(NUMERIC(18,2),(SUM([NUM_OH_VALORIZADO])/SUM([NUM_VTA_SEM_X_PERFIL]))*100) END AS INSTOCK
-- FROM (select A.* 
-- from [INFORMES3].[dbo].[CE_INSTOCK] AS A INNER JOIN
--      (SELECT NOM_LOCAL
--       ,COD_LOCAL
--       ,A.NOM_SKU
--       ,A.SKU
--       ,B.DIVISION
--       ,B.DEPARTAMENTO
--       ,B.SUBDEPARTAMENTO
--       ,IND_SURTIDO  
-- FROM [INFORMES3].[dbo].[MAESTRA_PRODUCTOS_SURTIDOS] AS A LEFT JOIN
--      [RepNonFood].dbo.MAESTRA_SKU AS B ON B.SKU=A.SKU
-- where (B.SUBDEPARTAMENTO LIKE '%CERDO%' OR B.SUBDEPARTAMENTO LIKE '%POLLO%' OR B.SUBDEPARTAMENTO LIKE '%PAVO%')
-- AND IND_SURTIDO=1) AS B ON B.COD_LOCAL=A.COD_LOCAL AND B.SKU=A.SKU
-- ) AS T
-- WHERE (SUBDEP LIKE '%POLLO%') AND SUBCLASE LIKE '%ASISTIDO%'
-- GROUP BY [COD_LOCAL]
--        ,[NOM_LOCAL]  
--        ,SUBDEP


SELECT 
	[COD_LOCAL]
	,[NOM_LOCAL]
	--,SUBDEP
	,CASE 
		WHEN (SUM([NUM_VTA_SEM_X_PERFIL]) IS NULL OR SUM([NUM_VTA_SEM_X_PERFIL])<=0) THEN 0
		ELSE CONVERT(NUMERIC(18,2),(SUM([NUM_OH_VALORIZADO])/SUM([NUM_VTA_SEM_X_PERFIL]))*100)
	END AS INSTOCK
FROM (
	SELECT A.*
	FROM [INFORMES3].[dbo].[CE_INSTOCK] AS A 
	INNER JOIN (
		SELECT 
			NOM_LOCAL
			,COD_LOCAL
			,A.NOM_SKU
			,A.SKU
			,B.DIVISION
			,B.DEPARTAMENTO
			,B.SUBDEPARTAMENTO
			,IND_SURTIDO  
		FROM [INFORMES3].[dbo].[MAESTRA_PRODUCTOS_SURTIDOS] AS A 
		LEFT JOIN [RepNonFood].dbo.MAESTRA_SKU AS B 
			ON B.SKU = A.SKU
		WHERE 
		(
			B.SUBDEPARTAMENTO LIKE '%CERDO%' 
			OR B.SUBDEPARTAMENTO LIKE '%POLLO%' 
			OR B.SUBDEPARTAMENTO LIKE '%PAVO%'
		)
		AND IND_SURTIDO=1
	) AS B 
		ON B.COD_LOCAL = A.COD_LOCAL 
		AND B.SKU = A.SKU
) AS T
WHERE 
	SUBDEP LIKE '%POLLO%' 
	AND SUBCLASE LIKE '%ASISTIDO%'
GROUP BY 
	[COD_LOCAL]
	,[NOM_LOCAL]
	,SUBDEP