USE [RepNonFood]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author: Sebastian Cornejo
-- Create date: 2020/01/09
-- Description: Informe de Obsoletos con precio oferta calculado automaticamente
-- ?? (104) EXEC [dbo].[SP_OBSOLETO_PRECIO]
-- =============================================
ALTER PROCEDURE [dbo].[SP_OBSOLETO_PRECIO]
	
AS
BEGIN

	SELECT 
		O.*,
		CASE WHEN O.RANGO_OBSOLETOS LIKE '%PRE%'
			THEN (CONVERT(INT, ISNULL(O.PRECIO_REGULAR, O.PRECIO_ORIGINAL) * (1 - O.DESCUENTO) / 10) * 10 + 6)
			ELSE (CONVERT(INT, ISNULL(O.PRECIO_REGULAR, O.PRECIO_ORIGINAL) * (1 - O.DESCUENTO) / 10) * 10 + 7)
		END PRECIO_OBSOLETO,
		CASE WHEN O.RANGO_OBSOLETOS LIKE '%PRE%'
			THEN CASE WHEN (CONVERT(INT, ISNULL(O.PRECIO_REGULAR, O.PRECIO_ORIGINAL) * (1 - O.DESCUENTO) / 10) * 10 + 6) < O.PRECIO_VIGENTE
				THEN CONVERT(INT, ISNULL(O.PRECIO_REGULAR, O.PRECIO_ORIGINAL) * (1 - O.DESCUENTO) / 10) * 10 + 6
				ELSE O.PRECIO_VIGENTE
			END 
			ELSE CASE WHEN (CONVERT(INT, ISNULL(O.PRECIO_REGULAR, O.PRECIO_ORIGINAL) * (1 - O.DESCUENTO) / 10) * 10 + 7) < O.PRECIO_VIGENTE
				THEN CONVERT(INT, ISNULL(O.PRECIO_REGULAR, O.PRECIO_ORIGINAL) * (1 - O.DESCUENTO) / 10) * 10 + 7
				ELSE O.PRECIO_VIGENTE
			END
		END NUEVO_PRECIO
	FROM (
		SELECT
			O.*,
			CASE 
				WHEN O.SUB_CLASE IN ('J1101020305 - LED TV', 'J1104030301 - CELULARES PRE PAGO') THEN DT.DESCUENTO
				ELSE DO.DESCUENTO
			END DESCUENTO
		FROM (
			SELECT DISTINCT
				O.RANGO_OBSOLETOS_2 RANGO_OBSOLETOS,
				CASE WHEN O.RANGO_OBSOLETOS_2 LIKE '%PRE%' THEN 'PRE-OBSOLETO'
					WHEN CONVERT(DATE, GETDATE()) > CONVERT(DATE, O.FECHA_VENCIMIENTO)
					THEN CASE 
						WHEN DATEDIFF(DAY, CONVERT(DATE, O.FECHA_VENCIMIENTO), CONVERT(DATE, GETDATE())) >=14 THEN '1-14 Días'
						WHEN DATEDIFF(DAY, CONVERT(DATE, O.FECHA_VENCIMIENTO), CONVERT(DATE, GETDATE())) >=28 THEN '15-28 Días'
						ELSE '+28 Días' 
					END ELSE 'PRE-OBSOLETO'
				END RANGO_OBSOLETOS_2,
				O.DIVISION,
				O.DEPARTAMENTO,
				O.SUBDEP,
				O.CLASE,
				O.SUB_CLASE,
				O.SKU,
				M.EAN UPC,
				O.NOM_SKU,
				O.FECHA_ULT_RECEP,
				O.FECHA_VENCIMIENTO,
				O.NOM_PROVEEDOR,
				O.MARCA,
				O.PRECIO_COSTO,
				O.PRECIO_VIGENTE,
				M.PRECIO_REGULAR,
				O.PRECIO_ORIGINAL
			FROM INFORMES3.dbo.ROBSOLETOS_PRINCIPAL O 
			LEFT JOIN [192.168.148.177].[RepNonFood].dbo.MAESTRA_SKU_2 M
				ON O.SKU = M.SKU
			WHERE 
				O.DIVISION NOT LIKE 'J12%'
				AND RANGO_OBSOLETOS_2 LIKE '%OBS%'
				-- AND SUB_CLASE LIKE 'J1104030301%'
		) O
		LEFT JOIN RepNonFood.dbo.DESCUENTOS_OBSOLETOS DO
			ON DO.RANGO_OBSOLETOS = O.RANGO_OBSOLETOS
			AND DO.RANGO_OBSOLETOS_2 = O.RANGO_OBSOLETOS_2
			AND DO.FILTRO = O.DIVISION
		LEFT JOIN RepNonFood.dbo.DESCUENTOS_OBSOLETOS DT
			ON DT.RANGO_OBSOLETOS = O.RANGO_OBSOLETOS
			AND DT.RANGO_OBSOLETOS_2 = O.RANGO_OBSOLETOS_2
			AND DT.FILTRO = O.SUB_CLASE
	) O

END
