USE [RepNonFood]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author: Sebastian Cornejo
-- Created_at:	2021/03/15
-- Updated_at:	
-- Description: Compia informe sp_obsoletos_precios
-- Changes:
--	*>> 2021/04/14: Informe obsoletos precio 430 muestra stock disponible en local 430 y precios de local 115.
-- ?? EXEC [RepNonFood].[dbo].[SP_OBSOLETO_PRECIO_430]
-- =============================================
ALTER PROCEDURE [dbo].[SP_OBSOLETO_PRECIO_430]
	
AS
BEGIN

	SELECT 
		O.*,
		CASE WHEN O.RANGO_OBSOLETOS LIKE '%PRE%'
			THEN (CONVERT(INT, ISNULL(O.PRECIO_REGULAR, O.PRECIO_ORIGINAL) * (1 - O.DESCUENTO) / 10) * 10 + 6)
			ELSE (CONVERT(INT, ISNULL(O.PRECIO_REGULAR, O.PRECIO_ORIGINAL) * (1 - O.DESCUENTO) / 10) * 10 + 7)
		END PRECIO_OBSOLETO,
		CASE WHEN O.RANGO_OBSOLETOS LIKE '%PRE%'
			THEN CASE WHEN (CONVERT(INT, ISNULL(O.PRECIO_REGULAR, O.PRECIO_ORIGINAL) * (1 - O.DESCUENTO) / 10) * 10 + 6) < O.PRECIO_VIGENTE
				THEN CONVERT(INT, ISNULL(O.PRECIO_REGULAR, O.PRECIO_ORIGINAL) * (1 - O.DESCUENTO) / 10) * 10 + 6
				ELSE O.PRECIO_VIGENTE
			END 
			ELSE CASE WHEN (CONVERT(INT, ISNULL(O.PRECIO_REGULAR, O.PRECIO_ORIGINAL) * (1 - O.DESCUENTO) / 10) * 10 + 7) < O.PRECIO_VIGENTE
				THEN CONVERT(INT, ISNULL(O.PRECIO_REGULAR, O.PRECIO_ORIGINAL) * (1 - O.DESCUENTO) / 10) * 10 + 7
				ELSE O.PRECIO_VIGENTE
			END
		END NUEVO_PRECIO
	FROM (
		SELECT
			O.*,
			CASE 
				WHEN O.SUB_CLASE IN ('J1101020305 - LED TV', 'J1104030301 - CELULARES PRE PAGO') THEN DT.DESCUENTO
				ELSE DO.DESCUENTO
			END DESCUENTO,
			isnull(S.COSTO_INV_DISP_HOY, 0) COSTO_INV_DISP_HOY,
			isnull(S.COSTO_INV_CONT_HOY, 0) COSTO_INV_CONT_HOY,
			isnull(S.UN_INV_CONT_HOY, 0) UN_INV_CONT_HOY,
			isnull(S.UN_INV_DISP_HOY, 0) UN_INV_DISP_HOY,
			isnull(A.ON_ORDER_ASR, 0) ON_ORDER_ASR,
			ISNULL(OO.ON_ORDER, 0) ON_ORDER,
			ISNULL(V.PROM_UN_VTA, 0) PROM_UN_VTA
		FROM (
			SELECT DISTINCT
				O.RANGO_OBSOLETOS_2 RANGO_OBSOLETOS,
				CASE 
					WHEN O.RANGO_OBSOLETOS_2 LIKE '%PRE%' THEN 'PRE-OBSOLETO'
					WHEN CONVERT(DATE, GETDATE()) > CONVERT(DATE, O.FECHA_VENCIMIENTO)
						THEN CASE 
							WHEN DATEDIFF(DAY, CONVERT(DATE, O.FECHA_VENCIMIENTO), CONVERT(DATE, GETDATE())) <=14 THEN '1-14 Días'
							WHEN DATEDIFF(DAY, CONVERT(DATE, O.FECHA_VENCIMIENTO), CONVERT(DATE, GETDATE())) <=28 THEN '15-28 Días'
							ELSE '+28 Días' 
						END
					ELSE 'PRE-OBSOLETO'
				END RANGO_OBSOLETOS_2,
				CASE 
					WHEN O.RANGO_OBSOLETOS_2 LIKE '%PRE%' THEN 0
					WHEN CONVERT(DATE, GETDATE()) > CONVERT(DATE, O.FECHA_VENCIMIENTO)
						THEN DATEDIFF(DAY, CONVERT(DATE, O.FECHA_VENCIMIENTO), CONVERT(DATE, GETDATE()))
				END DIAS_OBSOLETO,
				O.DIVISION,
				O.DEPARTAMENTO,
				O.SUBDEP,
				O.CLASE,
				O.SUB_CLASE,
				O.SKU,
				M.EAN UPC,
				O.NOM_SKU,
				O.FECHA_ULT_RECEP,
				convert(smalldatetime, pr.FECHA_UL_RECEPCION) FECHA_UL_RECEPCION_PR,
				O.FECHA_VENCIMIENTO,
				O.NOM_PROVEEDOR,
				O.MARCA,
				pv.P_COSTO PRECIO_COSTO,
				pv.P_VIGENTE PRECIO_VIGENTE,
				pv.P_REGULAR PRECIO_REGULAR,
				pv.P_VENTA_ORIGINAL PRECIO_ORIGINAL
			FROM INFORMES3.dbo.ROBSOLETOS_PRINCIPAL O 
			left join (
				select distinct 
					ob.SKU, 
					--ms.FECHA_UL_RECEPCION
					max(ms.FECHA_UL_RECEPCION) FECHA_UL_RECEPCION
				from INFORMES3.dbo.ROBSOLETOS_PRINCIPAL ob
				inner join INFORMES3.dbo.BREAK_SET bs
					on bs.SKU_DET = ob.SKU
				inner join RepNonFood.dbo.MAESTRA_SKU ms
					on ms.SKU = bs.SKU
				where ms.FECHA_UL_RECEPCION is not null
				group by ob.SKU
				-- order by ob.SKU
			) pr
				on pr.sku = o.sku
			LEFT JOIN [RepNonFood].dbo.MAESTRA_SKU_FULL M
			  ON O.SKU = M.SKU
			left join MAESTRAS.dbo.MAESTRA_PRECIO_VIGENTE_115 pv
				on pv.COD_LOCAL = 115
				and o.SKU = pv.SKU
			WHERE O.DIVISION NOT LIKE 'J12%'
				AND RANGO_OBSOLETOS_2 LIKE '%OBS%'
				AND o.cod_local = 430
				-- AND SUB_CLASE LIKE 'J1104030301%'
		) O
		LEFT JOIN RepNonFood.dbo.DESCUENTOS_OBSOLETOS DO
			ON DO.RANGO_OBSOLETOS = O.RANGO_OBSOLETOS
			AND DO.RANGO_OBSOLETOS_2 = O.RANGO_OBSOLETOS_2
			AND DO.FILTRO = O.DIVISION
		LEFT JOIN RepNonFood.dbo.DESCUENTOS_OBSOLETOS DT
			ON DT.RANGO_OBSOLETOS = O.RANGO_OBSOLETOS
			AND DT.RANGO_OBSOLETOS_2 = O.RANGO_OBSOLETOS_2
			AND DT.FILTRO = O.SUB_CLASE
		LEFT JOIN (
			select
				SKU,
				SUM(UN_SOLICITADO) ON_ORDER
			from RepNonFood.dbo.obsoletos_on_order
			where COD_LOCAL = 430
				and (DIA_CANCELACION >= CONVERT(date, getdate() - 30)
					or DIA_RECEPCION <= CONVERT(date, getdate())
				)
				--and SKU = 
			group by SKU
			-- order by SKU asc
		) OO
			ON OO.SKU = O.SKU
		LEFT JOIN (
			SELECT 
				SKU, 
				SUM(COSTO_INV_DISP_HOY) COSTO_INV_DISP_HOY, 
				SUM(COSTO_INV_CONT_HOY) COSTO_INV_CONT_HOY, 
				SUM(UN_INV_DISP_HOY) UN_INV_DISP_HOY, 
				SUM(UN_INV_CONT_HOY) UN_INV_CONT_HOY
			FROM INFORMES3.dbo.STOCK_HOY_CIA S
			where cod_local = 430
			GROUP BY SKU
		) S
			ON S.SKU = O.SKU
		LEFT JOIN (
			SELECT IITEM, SUM(IONORD) ON_ORDER_ASR
			FROM INFORMES3.dbo.DATA_ASR_CONTINGENCIA
			GROUP BY IITEM
		) A
			ON A.IITEM = O.SKU
		LEFT JOIN (
			SELECT 
				SKU,
				AVG(UN_VTA) PROM_UN_VTA
			FROM [RepNonFood].[dbo].[ACCDB_TABLA_VTA]
			WHERE SEMANA IN (
				SELECT DISTINCT TOP 2 SEMANA
				FROM [RepNonFood].[dbo].[ACCDB_TABLA_VTA]
				ORDER BY SEMANA DESC
				)
			GROUP BY SKU
		) V
		ON V.SKU = O.SKU
	) O

END
