USE [INFORMES3]
GO
/****** Object:  StoredProcedure [dbo].[Sp_Mail_INSTOCK_FFVV_CLASE_A_DETALLE]    Script Date: 20-11-2019 17:12:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Carlos Reyes L.
-- Create date: <Create Date,,>
-- Description:	Detalle clase A FFVV
-- EXEC Sp_Mail_INSTOCK_FFVV_CLASE_A_DETALLE
-- =============================================
ALTER PROCEDURE [dbo].[Sp_Mail_INSTOCK_FFVV_CLASE_A_DETALLE] 
	AS
BEGIN
--TRUNCATE TABLE [INFORMES3].[dbo].[FFVV_INSTOCK_CLASE_A_DETALLE]

--INSERT INTO [INFORMES3].[dbo].[FFVV_INSTOCK_CLASE_A_DETALLE]
--           ([SKU]
--           ,[DESCRIPCION SKU]
--           ,[INSTOCK]
--           ,[INSTOCK_NUM])
--SELECT    SKU
--          ,NOM_PRODUCTO AS [DESCRIPCION SKU]
--          ,''+CONVERT(VARCHAR(10),CONVERT(NUMERIC(12,1),SUM([NUM_OH_VALORIZADO])/nullif(SUM([NUM_VTA_SEM_X_PERFIL]),0)*100))+'%'		AS INSTOCK
--          ,CONVERT(NUMERIC(12,1),SUM([NUM_OH_VALORIZADO])/nullif(SUM([NUM_VTA_SEM_X_PERFIL]),0)*100)	AS INSTOCK_NUM
----INTO [INFORMES3].[dbo].[FFVV_INSTOCK_CLASE_A_DETALLE]
--FROM         dbo.CE_INSTOCK
--WHERE     (SUBDEP LIKE '%J04%') AND (SKU IN
--                          (SELECT     SKU
--                            FROM          [INFORMES3].[dbo].[FFVV_SKUS_CLASE_A]))
--group by SKU, NOM_PRODUCTO
--ORDER BY INSTOCK_NUM

--===== NUEVA CLASIFICACION GRUPOS==============

	TRUNCATE TABLE [INFORMES3].[dbo].[FFVV_INSTOCK_CLASE_A_DETALLE]

	INSERT INTO [INFORMES3].[dbo].[FFVV_INSTOCK_CLASE_A_DETALLE] (
		[GRUPO DE PRODUCTOS]
		,[INSTOCK]
		,[INSTOCK_NUM]
	)

-- SELECT    A.[GRUPO] AS [GRUPO DE PRODUCTOS]
--           ,''+CONVERT(VARCHAR(10),CONVERT(NUMERIC(12,1),SUM(B.[NUM_OH_VALORIZADO])/nullif(SUM(B.[NUM_VTA_SEM_X_PERFIL]),0)*100))+'%'		AS INSTOCK
--           ,CONVERT(NUMERIC(12,1),SUM(B.[NUM_OH_VALORIZADO])/nullif(SUM(B.[NUM_VTA_SEM_X_PERFIL]),0)*100)	AS INSTOCK_NUM
-- --INTO [INFORMES3].[dbo].[FFVV_INSTOCK_CLASE_A_DETALLE]
-- FROM   [INFORMES3].[dbo].[FFVV_SKUS_CLASE_A] AS A LEFT JOIN 
--        [INFORMES3].dbo.CE_INSTOCK_FYV AS B ON convert(float,B.SKU)=convert(float,A.SKU)
-- where COD_LOCAL not in (209,203,205,202,206,105,129,107,207)
-- GROUP BY A.GRUPO
-- ORDER BY INSTOCK_NUM


	SELECT
		A.[GRUPO] AS [GRUPO DE PRODUCTOS]
		,''+CONVERT(VARCHAR(10),CONVERT(NUMERIC(12,1),SUM(B.[NUM_OH_VALORIZADO])/nullif(SUM(B.[NUM_VTA_SEM_X_PERFIL]),0)*100))+'%' AS INSTOCK
		,CONVERT(NUMERIC(12,1),SUM(B.[NUM_OH_VALORIZADO])/nullif(SUM(B.[NUM_VTA_SEM_X_PERFIL]),0)*100)	AS INSTOCK_NUM 
	FROM [INFORMES3].[dbo].[FFVV_SKUS_CLASE_A] AS A
	LEFT JOIN [INFORMES3].dbo.CE_INSTOCK_FYV AS B
		ON CONVERT(FLOAT, B.SKU)=CONVERT(FLOAT, A.SKU)
	LEFT JOIN  [INFORMES3].[dbo].[TIENDAS_ASENTADAS] T
		ON B.COD_LOCAL = T.COD_LOCAL
	WHERE T.COD_LOCAL IS NULL
	GROUP BY A.GRUPO
	ORDER BY INSTOCK_NUM

END