
TRUNCATE TABLE NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_PERFIL_DIARIO
INSERT INTO NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_PERFIL_DIARIO
-- ?? SELECT * FROM NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_PERFIL_DIARIO where cod_local = 104 order by subclase, dia_semana

	SELECT 
		B.COD_LOCAL,
		B.SUBCLASE,
		B.DIA_SEMANA,
		V.VTA,
		VT.VTA VTA_TOTAL,
		V.VTA / CASE WHEN VT.VTA = 0 THEN NULL ELSE VT.VTA END PERFIL_DIA
	FROM (
		SELECT * FROM
			(SELECT DISTINCT COD_LOCAL FROM NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_VTA_DIA_SEMANA) L,
			(SELECT DISTINCT DIA_SEMANA FROM NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_VTA_DIA_SEMANA) D,
			(SELECT DISTINCT SUBCLASE FROM RepNonFood.dbo.MAESTRA_SKU WHERE DIVISION LIKE 'J04%') S
	) B
	LEFT JOIN NUEVO_SUGERIDO_FFVV.dbo.vw_sug_sem_vta_promedio_dia V -- VENTA TOTAL DIA
		ON V.COD_LOCAL = B.COD_LOCAL
		AND V.SUBCLASE = B.SUBCLASE
		AND V.DIA_SEMANA = B.DIA_SEMANA
	LEFT JOIN (
		SELECT 
			COD_LOCAL
			,SUBCLASE
			,SUM(VTA) VTA
		FROM NUEVO_SUGERIDO_FFVV.dbo.vw_sug_sem_vta_promedio_dia VT
		GROUP BY
			COD_LOCAL
			,SUBCLASE
	) VT -- VENTA TOTAL SEMANAL
		ON VT.COD_LOCAL = B.COD_LOCAL
		AND VT.SUBCLASE = B.SUBCLASE
	WHERE B.COD_LOCAL NOT IN (115)


---------------------------------------------------
-- UPDATE PERFILES INCOMPLETOS
---------------------------------------------------
UPDATE NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_PERFIL_DIARIO
	SET VTA = 1, VTA_TOTAL = 7, PERFIL_DIA = 1.0 / 7.0
	FROM NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_PERFIL_DIARIO P
	INNER JOIN (
		SELECT DISTINCT COD_LOCAL, SUBCLASE
		FROM NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_PERFIL_DIARIO
		WHERE PERFIL_DIA IS NULL
	) F
		ON F.COD_LOCAL = P.COD_LOCAL
		AND F.SUBCLASE = P.SUBCLASE
