
TRUNCATE TABLE NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_FORECAST_SEMANA_T_PIVOT
INSERT INTO NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_FORECAST_SEMANA_T_PIVOT
	--?? select * from NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_FORECAST_SEMANA_T_PIVOT

	SELECT 
		SKU
		,[COD_LOCAL]
		,ISNULL(CONVERT(NUMERIC(18, 2), [1]), 0) AS LUN
		,ISNULL(CONVERT(NUMERIC(18, 2), [2]), 0) AS MAR
		,ISNULL(CONVERT(NUMERIC(18, 2), [3]), 0) AS MIE
		,ISNULL(CONVERT(NUMERIC(18, 2), [4]), 0) AS JUE
		,ISNULL(CONVERT(NUMERIC(18, 2), [5]), 0) AS VIE
		,ISNULL(CONVERT(NUMERIC(18, 2), [6]), 0) AS SAB
		,ISNULL(CONVERT(NUMERIC(18, 2), [7]), 0) AS DOM
	FROM (
		SELECT 
			COD_LOCAL,
			SKU,
			DIA_SEMANA,
			FORECAST_DIA
		from NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_FORECAST_DIARIO
		where SEMANA = (datepart(year, getdate() + 1 + 7 - datepart(weekday, getdate())) * 100 + datepart(iso_week, getdate() + 1 + 7 - datepart(weekday, getdate())))
	) AS VENTAS_PROM 
	PIVOT (
		avg([FORECAST_DIA]) 
		FOR DIA_SEMANA IN ([1], [2], [3], [4], [5], [6], [7])
	) AS pvt

