
TRUNCATE TABLE NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_VENTA_SEMANAL
INSERT INTO NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_VENTA_SEMANAL
	--?? select * from NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_VENTA_SEMANAL where cod_local = 104 and sku = 5014038

	select 
		COD_LOCAL,
		SKU,
		SEMANA,
		sum(vta) vta
	from NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_VENTA_DIARIA
	group by 	
		COD_LOCAL,
		SKU,
		SEMANA