
TRUNCATE TABLE NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_VENTA_DIARIA
INSERT INTO NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_VENTA_DIARIA

	SELECT *
	FROM (
		-- TIENDAS NORMALES
		SELECT 
			[COD_LOCALFISICO] COD_LOCAL
			,[CUSTCOL_7] SKU
			,[ID_SEMANACANALISIS] SEMANA
			,ID_DIAANALISIS DIA
			,SUM([UN_VENTA]) VTA
		FROM (
			SELECT 
				[CUSTCOL_7]
				,VTA.[COD_LOCALFISICO]
				,[ID_SEMANACANALISIS]
				,VTA.[ID_DIAANALISIS]
				,CASE 
					WHEN (ISNULL([UN_VENTA], 0) - ISNULL(VTA_LL.UNIDADES, 0)) < 0 THEN 0
					ELSE (ISNULL([UN_VENTA], 0) - ISNULL(VTA_LL.UNIDADES, 0)) 
				END AS UN_VENTA
			FROM [SUGERIDO_COMPRA].[dbo].[FFYVV_VTA_SEMANAS] VTA 
			LEFT JOIN [NUEVO_SUGERIDO_FFVV].[dbo].[vw_sug_sem_vta_llave] VTA_LL 
				ON VTA_LL.SKU = VTA.CUSTCOL_7 
				AND VTA_LL.cod_local = VTA.COD_LOCALFISICO 
				AND CONVERT(DATE, VTA_LL.ID_DIAANALISIS) = CONVERT(DATE,VTA.ID_DIAANALISIS)
		) T
		WHERE ID_SEMANACANALISIS IN (
				SELECT DISTINCT TOP 4 ID_SEMANACANALISIS
				FROM [SUGERIDO_COMPRA].[dbo].[FFYVV_VTA_SEMANAS]
				where ID_SEMANACANALISIS NOT IN (datepart(year, getdate() + 1 - datepart(weekday, getdate())) * 100 + datepart(iso_week, getdate() + 1 - datepart(weekday, getdate())))
				ORDER BY ID_SEMANACANALISIS DESC
			)
			AND COD_LOCALFISICO NOT IN (115)
		GROUP BY 
			[COD_LOCALFISICO] 
			,[CUSTCOL_7]
			,[ID_SEMANACANALISIS]
			,ID_DIAANALISIS

		UNION ALL

		-- TIENDAS GRISES
		SELECT 
			A.[COD_LOCAL]
			,A.[SKU]
			,B.SEMANA
			,[ID_DIAANALISIS] DIA
			,sum([UNIDADES_VENTA]) VTA
		FROM [10.195.254.201].[TIENDA_GRIS].[dbo].[VENTA_VNP_DIARIA] A 
		LEFT JOIN [10.195.254.201].INFORMES3.dbo.DHW_MES_GC B 
			ON B.FECHA = A.ID_DIAANALISIS 
		LEFT JOIN [10.195.254.201].RepNonFood.dbo.MAESTRA_SKU C 
			ON C.SKU = A.SKU
		WHERE B.SEMANA IN (
				SELECT DISTINCT TOP 4 SEMANA
				FROM [10.195.254.201].[TIENDA_GRIS].[dbo].[VENTA_VNP_DIARIA] A 
				LEFT JOIN [10.195.254.201].INFORMES3.dbo.DHW_MES_GC B 
					ON B.FECHA = A.ID_DIAANALISIS
				where SEMANA NOT IN (datepart(year, getdate() + 1 - datepart(weekday, getdate())) * 100 + datepart(iso_week, getdate() + 1 - datepart(weekday, getdate())))
				ORDER BY SEMANA DESC
			)
			and C.DIVISION LIKE 'J04%' AND COD_LOCAL IN (138,147)
		GROUP BY A.[COD_LOCAL]
			,A.[SKU]
			,B.SEMANA
			,[ID_DIAANALISIS]

	) T