
TRUNCATE TABLE NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_PROM_SEMANAL_ACOTADO
INSERT INTO NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_PROM_SEMANAL_ACOTADO
--?? select * from NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_PROM_SEMANAL_ACOTADO

	SELECT 
		VF.COD_LOCAL,
		VF.SKU,
		VF.SUBCLASE,
		VF.ESTADO,
		VF.IND_SURTIDO,
		AVG(VF.VTA) PROM_SEM_ACOTADO
	FROM (
		SELECT 
			V.COD_LOCAL,
			V.SKU,
			M.SUBCLASE,
			SEMANA,
			SUM(VTA) VTA,
			CASE WHEN S.SKU IS NULL AND S.LOCAL IS NULL THEN 0 ELSE 1 END IND_SURTIDO,
			M.ESTADO
		FROM NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_VENTA_SEMANAL V
		LEFT JOIN RepNonFood.dbo.MAESTRA_SKU M
			ON M.SKU = V.SKU
		LEFT JOIN 	 
		( 
			SELECT Codigo SKU, Division DIVISION, Surtido, Sala LOCAL
			FROM [10.195.254.201].[NUEVO_SUGERIDO_FFVV].[dbo].[NSFFVV_SURTIDO_TIENDA]
			WHERE Surtido=1
		) S
			ON S.LOCAL = V.COD_LOCAL
			AND S.SKU = V.SKU
		GROUP BY 
			V.COD_LOCAL,
			V.SKU,
			M.SUBCLASE,
			SEMANA,
			CASE WHEN S.SKU IS NULL AND S.LOCAL IS NULL THEN 0 ELSE 1 END,
			M.ESTADO
	) VF
	LEFT JOIN NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_PROM_VTA_SEM PV
		ON PV.COD_LOCAL = VF.COD_LOCAL
		AND PV.SKU = VF.SKU
	WHERE VF.VTA <= (PV.PROM_SIMPLE + PV.DESV_EST)
		AND VF.VTA >= (PV.PROM_SIMPLE - PV.DESV_EST)
		-- AND VF.COD_LOCAL = 501
		-- AND VF.SUBCLASE LIKE '%PAPA'
	GROUP BY
		VF.COD_LOCAL,
		VF.SKU,
		VF.SUBCLASE,
		VF.ESTADO,
		VF.IND_SURTIDO
