--===================================
--=== PROCESO CALCULO SUGERIDO SEMANAL
--====================================

----------------------------------------------------------
-- CALCULA VTA SEMANA ANTERIOR
----------------------------------------------------------
TRUNCATE TABLE NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_VENTA_SEM_ANTERIOR
INSERT INTO NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_VENTA_SEM_ANTERIOR
	--?? select * from NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_VENTA_SEM_ANTERIOR

	SELECT 
		COD_LOCAL
		,SKU
		,SUM(VTA) VTA_SEM_ANTERIOR
	FROM NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_VENTA_SEMANAL
	WHERE SEMANA = (datepart(year, getdate() + 1 - 7 - datepart(weekday, getdate())) * 100 + datepart(iso_week, getdate() + 1 - 7 - datepart(weekday, getdate())))
	GROUP BY 
		COD_LOCAL
		,SKU

----------------------------------------------------------
-- CALCULA FORECAST DESDE DIA PEDIDO HASTA INICIO SEMANA T
----------------------------------------------------------
TRUNCATE TABLE NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_FORECAST_SEMANA_ACTUAL
INSERT INTO NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_FORECAST_SEMANA_ACTUAL
	--?? select * from NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_FORECAST_SEMANA_ACTUAL

	SELECT 
		SEMANA,
		COD_LOCAL,
		SKU,
		sum(FORECAST_DIA) FORECAST_SEM_ACTUAL
	from NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_FORECAST_DIARIO
	where SEMANA = (datepart(year, getdate() + 1 - datepart(weekday, getdate())) * 100 + datepart(iso_week, getdate() + 1 - datepart(weekday, getdate())))
		AND FECHA >= convert(date, getdate())
		AND DIA_SEMANA <= 7
	GROUP BY 
		SEMANA,
		COD_LOCAL,
		SKU
	ORDER BY 
		SEMANA,
		COD_LOCAL,
		SKU


--------------------------------------------------------------
-- PIVOTE SOBRE TABLA DE FORECAST SEMANA T
--------------------------------------------------------------
TRUNCATE TABLE NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_FORECAST_SEMANA_T_PIVOT
INSERT INTO NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_FORECAST_SEMANA_T_PIVOT
	--?? select * from NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_FORECAST_SEMANA_T_PIVOT

	SELECT 
		SKU
		,[COD_LOCAL]
		,ISNULL(CONVERT(NUMERIC(18, 2), [1]), 0) AS LUN
		,ISNULL(CONVERT(NUMERIC(18, 2), [2]), 0) AS MAR
		,ISNULL(CONVERT(NUMERIC(18, 2), [3]), 0) AS MIE
		,ISNULL(CONVERT(NUMERIC(18, 2), [4]), 0) AS JUE
		,ISNULL(CONVERT(NUMERIC(18, 2), [5]), 0) AS VIE
		,ISNULL(CONVERT(NUMERIC(18, 2), [6]), 0) AS SAB
		,ISNULL(CONVERT(NUMERIC(18, 2), [7]), 0) AS DOM
	FROM (
		SELECT 
			COD_LOCAL,
			SKU,
			DIA_SEMANA,
			FORECAST_DIA
		from NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_FORECAST_DIARIO
		where SEMANA = (datepart(year, getdate() + 1 + 7 - datepart(weekday, getdate())) * 100 + datepart(iso_week, getdate() + 1 + 7 - datepart(weekday, getdate())))
	) AS VENTAS_PROM 
	PIVOT (
		avg([FORECAST_DIA]) 
		FOR DIA_SEMANA IN ([1], [2], [3], [4], [5], [6], [7])
	) AS pvt


--------------------------------------------------------------
-- CALCULA FORECAST PROMEDIO Y TOTAL SEMANA T
--------------------------------------------------------------
TRUNCATE TABLE NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_FORECAST_SEMANA_T
INSERT INTO NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_FORECAST_SEMANA_T
	--?? select * from NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_FORECAST_SEMANA_T

	SELECT 
		SEMANA,
		COD_LOCAL,
		SKU,
		AVG(FORECAST_DIA) FORECAST_PROM_DIA_SEM_T,
		SUM(FORECAST_DIA) FORECAST_SEM_T
	from NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_FORECAST_DIARIO
	where SEMANA = (datepart(year, getdate() + 1 + 7 - datepart(weekday, getdate())) * 100 + datepart(iso_week, getdate() + 1 + 7 - datepart(weekday, getdate())))
	GROUP BY 
		SEMANA,
		COD_LOCAL,
		SKU
	ORDER BY 
		SEMANA,
		COD_LOCAL,
		SKU
     
--------------------------------------------------------------
-- TABLA DATA BASE SUGERIDO
--------------------------------------------------------------
TRUNCATE TABLE NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_BASE_SUGERIDO_SEMANAL
INSERT INTO NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_BASE_SUGERIDO_SEMANAL
	--?? select * from NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_BASE_SUGERIDO_SEMANAL
	--?? select * from NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_BASE_SUGERIDO_SEMANAL where MIN_PRES_SS is null

	SELECT 
		A.LOCAL
		,M.SUBCLASE
		,M.CASEPACK
		,A.SKU
		,M.NOM_SKU
		,A.dir_cd
		,ISNULL(O.UN_INV, 0) OH_INICIAL
		,ISNULL(VTA.FORECAST_SEM_ACTUAL, 0) FORECAST_SEM_ACTUAL
		,ISNULL(FST.FORECAST_PROM_DIA_SEM_T, 0) FORECAST_PROM_DIA_SEM_T
		,ISNULL(FORECAST_SEM_T, 0) FORECAST_SEM_T
		,ISNULL(MER.MERMA_UNIDADES, 0) MERMA_SEM_ANT
		,ISNULL(VTAANT.VTA_SEM_ANTERIOR, 0) VTA_SEM_ANT
		,LM.LIMITE_MERMA
		,CASE 
			WHEN ISNULL(VTAANT.VTA_SEM_ANTERIOR, 0) > 0 AND ISNULL(ABS(MER.MERMA_UNIDADES), 0) >= LM.LIMITE_MERMA * ISNULL(VTAANT.VTA_SEM_ANTERIOR, 0) THEN 1
			ELSE 0 
		END CRITERIO_MERMA
		,M.CASEPACK * ISNULL(COMP.COMPRAS, 0) COMPRAS_SEMANA_ACTUAL
		,ISNULL(FR.FR_PONDERADO, 0) FR_PONDERADO
		,EFR.PFR EFECTO_FR
		,(1 - (ISNULL(FR.FR_PONDERADO, 0) / 100)) * (1 - EFR.PFR) + (ISNULL(FR.FR_PONDERADO, 0) / 100) FACTOR_FR
		,ISNULL(TRFCD.TRF_CD, 0) TRANSITO_CD
		,0 EN_PROMO
		,isnull(MP.[MIN], 1) MIN_PRES
		,isnull(MP.[MIN], 1) * ISNULL(FST.FORECAST_PROM_DIA_SEM_T, 0) MIN_PRES_UN
		,MPP.[MIN_PROMO] * isnull(MP.[MIN], 1) MIN_PRES_PROMO
		,MPP.[MIN_PROMO] * isnull(MP.[MIN], 1) * M.CASEPACK MIN_PRES_PROMO_UN
		,CASE 
			WHEN 0 = 0 THEN isnull(MP.[MIN], 1)*M.CASEPACK -- CAMBIAR CUANDO SE APLIQUEN PROMOCIONES
			ELSE isnull(MP.[MIN], 1) * isnull(MPP.[MIN_PROMO], 1) * M.CASEPACK
		END MIN_PRES_FINAL_UN
		,VU.VIDA_UTIL
		,isnull(VU.SS, 0) SS
		,ISNULL(FST.FORECAST_PROM_DIA_SEM_T, 0) * isnull(VU.SS, 0) SS_UN   
		,ISNULL(FST.FORECAST_PROM_DIA_SEM_T, 0) * isnull(VU.SS, 0) + (
			CASE 
				WHEN 0 = 0 THEN isnull(MP.[MIN], 1) * M.CASEPACK -- CAMBIAR CUANDO SE APLIQUEN PROMOCIONES
				ELSE isnull(MP.[MIN], 1) * isnull(MPP.[MIN_PROMO], 1)*M.CASEPACK
			END
		) MIN_PRES_SS
		,SP.SEMANA
	--INTO NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_BASE_SUGERIDO_SEMANAL   
	FROM (
		SELECT Codigo SKU, Division DIVISION, Surtido, Sala LOCAL, dir_cd
		FROM NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_SURTIDO_TIENDA
		Where Surtido = 1
	) A
	LEFT JOIN RepNonFood.dbo.MAESTRA_SKU M 
		ON M.SKU = A.SKU 
	LEFT JOIN (
		SELECT 
			[CUSTCOL_7] SKU
			,[COD_LOCALFISICO] COD_LOCAL
			,[UNIDINVDISPOHOY] UN_INV
		FROM [SUGERIDO_COMPRA].[dbo].[FFYVV_ONHAND]
	) O 
		ON O.COD_LOCAL = A.LOCAL 
		AND O.SKU = A.SKU
	LEFT JOIN NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_FILLRATE_SEMANAL_PONDERADO FR 
		ON FR.SUBCLASE = M.SUBCLASE
	LEFT JOIN NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_FORECAST_SEMANA_ACTUAL VTA 
		ON VTA.SKU = A.SKU 
		AND VTA.COD_LOCAL = A.LOCAL
	LEFT JOIN (
		SELECT 
			[CUSTCOL_7] SKU
			,[COD_LOCALFISICO] COD_LOCAL
			,[ID_SEMANACANALISIS] SEMANA
			,SUM(ISNULL([UNIDADES],0)) MERMA_UNIDADES
		FROM [SUGERIDO_COMPRA].[dbo].[FFYVV_MERMA]
		GROUP BY [CUSTCOL_7]
			,[COD_LOCALFISICO] 
			,[ID_SEMANACANALISIS]
	) MER 
		ON MER.COD_LOCAL = A.LOCAL 
		AND MER.SKU = A.SKU
	LEFT JOIN (
		select 
			SKU
			,SALA COD_LOCAL
			,SUM(CAJAS) COMPRAS
		FROM [NUEVO_SUGERIDO_FFVV].[dbo].vw_comprado
		WHERE fecha_entrega_cd >= CONVERT(DATE, GETDATE())
		GROUP BY SKU, SALA
	) COMP 
		ON COMP.COD_LOCAL = A.LOCAL 
		AND COMP.SKU = A.SKU
	LEFT JOIN (
		SELECT 
			SKU
			,TIENDA_RECIBO COD_LOCAL
			,ASIGNADO TRF_CD
		FROM [SUGERIDO_COMPRA].[dbo].[FFYVV_TRFS_TRANSITO]
	) TRFCD 
		ON TRFCD.SKU = A.SKU 
		AND TRFCD.COD_LOCAL = A.LOCAL
	LEFT JOIN (
		SELECT 
			COD_LOCAL
			,SKU
			,VTA_SEM_ANTERIOR
		FROM NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_VENTA_SEM_ANTERIOR
	) VTAANT 
		ON VTAANT.COD_LOCAL = A.LOCAL 
		AND VTAANT.SKU = A.SKU
	LEFT JOIN [NUEVO_SUGERIDO_FFVV].[dbo].[NSFFVV_EFECTO_FILLRATE] EFR 
		ON EFR.SUBCLASE = M.SUBCLASE
	LEFT JOIN [NUEVO_SUGERIDO_FFVV].[dbo].[NSFFVV_LIMITE_MERMA] LM 
		ON LM.COD_LOCAL = A.LOCAL
	LEFT JOIN [NUEVO_SUGERIDO_FFVV].[dbo].[NSFFVV_MIN_PRES] MP 
		ON MP.SKU = M.SKU
		AND MP.COD_LOCAL = A.LOCAL
	LEFT JOIN [NUEVO_SUGERIDO_FFVV].[dbo].[NSFFVV_MIN_PRES_PROMO] MPP 
		ON MPP.SKU = M.SKU
		AND MPP.COD_LOCAL = A.LOCAL 
	LEFT JOIN (
		SELECT VU.CLASE, VU.VIDA_UTIL, ISNULL(SS.ss,0) SS
		FROM [NUEVO_SUGERIDO_FFVV].[dbo].[NSFFVV_VIDA_UTIL] VU
		LEFT JOIN [NUEVO_SUGERIDO_FFVV].dbo.[NSFFVV_CRITERIOS_SS] SS
			ON VU.VIDA_UTIL >= SS.VU_DESDE
			AND VU.VIDA_UTIL <= 
				CASE 
					WHEN SS.VU_HASTA IS NULL THEN (SELECT MAX(VIDA_UTIL) FROM [NUEVO_SUGERIDO_FFVV].[dbo].[NSFFVV_VIDA_UTIL]) 
					ELSE SS.VU_HASTA 
				END
	) VU 
		ON VU.CLASE = M.CLASE  
	LEFT JOIN NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_FORECAST_SEMANA_T FST 
		ON FST.SKU = A.SKU 
		AND FST.COD_LOCAL = A.LOCAL 
	,(SELECT MAX(SEMANA) SEMANA FROM NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_FORECAST_SEMANA_T) SP
	where A.SKU = 20410128
		and a.[LOCAL] = 104





--------------------------------------------------------------
-- TABLA DATA SUGERIDO SEMANAL FINAL
--------------------------------------------------------------
TRUNCATE TABLE NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_SUGERIDO_SEMANAL_CALCULADO;

	update NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_BASE_SUGERIDO_SEMANAL
	set CASEPACK = 1
	where CASEPACK = 0 or CASEPACK is null

	INSERT INTO NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_SUGERIDO_SEMANAL_CALCULADO 

	SELECT 
		LOCAL
		,SUBCLASE
		,CASEPACK
		,SKU
		,NOM_SKU
		,OH_INICIAL
		,FORECAST_SEM_ACTUAL
		,FORECAST_PROM_DIA_SEM_T
		,FORECAST_SEM_T
		,MERMA_SEM_ANT
		,VTA_SEM_ANT
		,LIMITE_MERMA
		,CRITERIO_MERMA
		,COMPRAS_SEMANA_ACTUAL
		,FR_PONDERADO
		,EFECTO_FR
		,FACTOR_FR
		,TRANSITO_CD
		,EN_PROMO
		,MIN_PRES_FINAL_UN
		,SS_UN   
		,MIN_PRES_SS
		,OH_INICIAL+TRANSITO_CD+COMPRAS_SEMANA_ACTUAL*FACTOR_FR-FORECAST_SEM_ACTUAL OH_TEORICO_SEM_T
		,CASE 
			WHEN CRITERIO_MERMA = 1 
				THEN 
					case 
						when (OH_INICIAL + TRANSITO_CD + COMPRAS_SEMANA_ACTUAL * FACTOR_FR - FORECAST_SEM_ACTUAL) <= 0 then MIN_PRES_SS
						when (OH_INICIAL + TRANSITO_CD + COMPRAS_SEMANA_ACTUAL * FACTOR_FR - FORECAST_SEM_ACTUAL) > MIN_PRES_SS then 0
						else MIN_PRES_SS - (OH_INICIAL + TRANSITO_CD + COMPRAS_SEMANA_ACTUAL * FACTOR_FR - FORECAST_SEM_ACTUAL)
					end 
			WHEN CRITERIO_MERMA = 0 AND (OH_INICIAL + TRANSITO_CD + COMPRAS_SEMANA_ACTUAL * FACTOR_FR - FORECAST_SEM_ACTUAL) < 0 
				THEN FORECAST_SEM_T + MIN_PRES_SS
			WHEN CRITERIO_MERMA = 0 AND (OH_INICIAL + TRANSITO_CD + COMPRAS_SEMANA_ACTUAL * FACTOR_FR - FORECAST_SEM_ACTUAL) >= 0
				THEN (
					CASE 
						WHEN MIN_PRES_SS + FORECAST_SEM_T - (OH_INICIAL + TRANSITO_CD + COMPRAS_SEMANA_ACTUAL * FACTOR_FR - FORECAST_SEM_ACTUAL) < 0 THEN 0
						ELSE MIN_PRES_SS + FORECAST_SEM_T - (OH_INICIAL + TRANSITO_CD + COMPRAS_SEMANA_ACTUAL * FACTOR_FR - FORECAST_SEM_ACTUAL)
					end 
				)
		END SUGERIDO_UN
		,CEILING((
			CASE 
				WHEN CRITERIO_MERMA = 1 
					THEN 
						case 
							when (OH_INICIAL + TRANSITO_CD + COMPRAS_SEMANA_ACTUAL * FACTOR_FR - FORECAST_SEM_ACTUAL) <= 0 then MIN_PRES_SS
							when (OH_INICIAL + TRANSITO_CD + COMPRAS_SEMANA_ACTUAL * FACTOR_FR - FORECAST_SEM_ACTUAL) > MIN_PRES_SS then 0
							else MIN_PRES_SS - (OH_INICIAL + TRANSITO_CD + COMPRAS_SEMANA_ACTUAL * FACTOR_FR - FORECAST_SEM_ACTUAL)
						end 
				WHEN  CRITERIO_MERMA = 0 AND (OH_INICIAL + TRANSITO_CD + COMPRAS_SEMANA_ACTUAL * FACTOR_FR - FORECAST_SEM_ACTUAL) < 0 
					THEN FORECAST_SEM_T + MIN_PRES_SS
				WHEN CRITERIO_MERMA = 0 AND (OH_INICIAL + TRANSITO_CD + COMPRAS_SEMANA_ACTUAL * FACTOR_FR - FORECAST_SEM_ACTUAL) >= 0
					THEN (
						CASE 
							WHEN MIN_PRES_SS + FORECAST_SEM_T - (OH_INICIAL + TRANSITO_CD + COMPRAS_SEMANA_ACTUAL * FACTOR_FR - FORECAST_SEM_ACTUAL) < 0 THEN 0
							ELSE MIN_PRES_SS + FORECAST_SEM_T - (OH_INICIAL + TRANSITO_CD + COMPRAS_SEMANA_ACTUAL * FACTOR_FR - FORECAST_SEM_ACTUAL)
						end 
					)
			END 
		) / CASEPACK) SUGERIDO_CAJAS
		,SEMANA
	FROM NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_BASE_SUGERIDO_SEMANAL


-------------------------------------------------------------------
-- CREA TABLA SUGERIDO CALCULADO PARA PLATAFORMA
-------------------------------------------------------------------
TRUNCATE TABLE NUEVO_SUGERIDO_FFVV.[dbo].[NSFFVV_SUGERIDO_CALCULADO_PLATAFORMA]
INSERT INTO NUEVO_SUGERIDO_FFVV.[dbo].[NSFFVV_SUGERIDO_CALCULADO_PLATAFORMA]

	SELECT 
		DISTINCT --[id], -- M
			A.[local], --M
			A.[sku], --M
			A.NOM_SKU [desc_sku], --M
			A.[casepack], --M
			ISNULL(B.[lun],0) [lun],--M
			ISNULL(B.[mar],0) [mar],--M
			isnull(B.[mie],0) [mie],--M
			isnull(B.[jue],0) [jue],--M
			isnull(B.[vie],0) [vie],--M
			isnull(B.[sab],0) [sab],--M
			isnull(B.[dom],0) [dom],--M
			convert(numeric(18,2),isnull(A.FORECAST_SEM_T,0)) [Fcst Semanal],-- CAMBIA POR FORECAST SEMANAL
			ceiling(A.MIN_PRES_SS/ISNULL(A.[casepack],1)) [Min + SS],-- SE MOSTRARÁ MIN PRES+ SS
			A.FR_PONDERADO [Fillrate Ponderado], -- SE MOSTRARA FILLRATE PONDERADO ULTIMAS 4 SEMANAS SUBCLASE
			A.[merma_sEM_ANT] [Merma], --M
			A.OH_INICIAL [on_hand], -- M (OH INICIAL)
			A.TRANSITO_CD+COMPRAS_SEMANA_ACTUAL*FACTOR_FR [transito], -- TRANSITO CD + COMPRAS SEMANA ACTUAL*EFECTO FR
			A.[SUGERIDO_CAJAS],--M
			NULL [corregido],--M
			'' [comentario],--M
			'AUTOMATICO '[ESTADO],--M
			NULL [id_promocion],--SE LLENA CON CERO INICIALMENTE
			M.[DIVISION], --M
			A.SEMANA
	FROM NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_SUGERIDO_SEMANAL_CALCULADO A 
	LEFT JOIN NUEVO_SUGERIDO_FFVV.dbo.NSFFVV_FORECAST_SEMANA_T_PIVOT B 
		ON B.SKU = A.SKU 
		AND B.COD_LOCAL = A.LOCAL 
	LEFT JOIN RepNonFood.dbo.MAESTRA_SKU M 
		ON M.SKU = A.SKU
	ORDER BY 
		LOCAL, 
		SKU