SELECT
  --PMM_BOLETAS.NUMOC,
  PMM_BOLETAS.NCOMPROBANTE as num_boleta_tirilla,
  '' as 'cod_validacion',
  115 as 'cod_tienda',
  'CL' as 'cod_pais',
  'TOT' as 'cod_marca',
  REPLACE(A.FECHA_COMPRA,'-','') AS fecha_compra,
  -- CASE
  --   WHEN DATEPART(MM,A.FECHA_COMPRA)>9
  --     THEN '0'+CONVERT(CHAR(2),DATEPART(DD,A.FECHA_COMPRA))+''+ CONVERT(CHAR(2),DATEPART(MM,A.FECHA_COMPRA))+''+ CONVERT(CHAR(4),DATEPART(YYYY,A.FECHA_COMPRA))
  --   WHEN DATEPART(DD,A.FECHA_COMPRA)<10
  --     THEN '0'+CONVERT(CHAR(1),DATEPART(DD,A.FECHA_COMPRA))+'0'+ CONVERT(CHAR(1),DATEPART(MM,A.FECHA_COMPRA))+''+ CONVERT(CHAR(4),DATEPART(YYYY,A.FECHA_COMPRA))
  --   ELSE
  --     CONVERT(CHAR(2),DATEPART(DD,A.FECHA_COMPRA))+'0'+ CONVERT(CHAR(1),DATEPART(MM,A.FECHA_COMPRA))+''+ CONVERT(CHAR(4),DATEPART(YYYY,A.FECHA_COMPRA))
  -- END AS fecha_compra,
  -- C.NOMBRES as 'nombre',
  UPPER(RTRIM(LTRIM(SUBSTRING(C.NOMBRES, 1, CHARINDEX(' ', C.NOMBRES) - 1)))) as 'nombre',
  UPPER(RTRIM(LTRIM(SUBSTRING(C.NOMBRES, CHARINDEX(' ', C.NOMBRES) +1, LEN(C.NOMBRES))))) as 'apellidos',
  -- '' as 'apellidos',
  '' as 'telefono_fijo',
  C.CELULAR as 'telefono_celular',
  C.CORREO as 'email',
  '' as 'edad',
  '' as 'sexo',
  'Tottus.cl' as 'nombre_tienda',
  PMM_BOLETAS.MMONTO as 'monto_compra',
  '' as 'cod_departamento_clacom',
  '' as 'des_departamento_clacom',
  '' as 'cod_familia_clacom',
  '' as 'desc_familia_clacom',
  'Venta On Line' as 'punto_contacto'
-- CONVERT(FLOAT, A.SUMDETALLE) AS SUMDETALLE,
-- CONVERT(FLOAT, A.SUMDETALLEPCK_SUSTITUTO) AS SUMDETALLEPCK_SUSTITUTO,
-- CONVERT(FLOAT, A.SUMAPCK_NO_SUSTITUTO) AS SUMAPCK_NO_SUSTITUTO,
-- CONVERT(FLOAT, A.SUMAPCK_NO_SUSTITUTO)/CONVERT(FLOAT, A.SUMDETALLE) AS SUMAPCK_NO_SUSTITUTO
FROM OC_DS_BASE_FILLRATE AS A
  LEFT OUTER JOIN PMM_BOLETAS
  ON A.NUMERO_ORDEN = PMM_BOLETAS.NUMOC
  LEFT OUTER JOIN OC_CABECERA AS B
  ON B.NUMERO_ORDEN = A.NUMERO_ORDEN
  LEFT OUTER JOIN OC_DS_CLIENTES AS C
  ON C.RUT = B.RUT_CLIENTE
  LEFT JOIN View_ON_TIME_TIENDA_GRIS O ON O.OC = A.NUMERO_ORDEN
WHERE (A.ID_SUCURSAL = 4) AND O.ON_TIME = 1
GROUP BY 
	PMM_BOLETAS.NUMOC,
	A.SUMDETALLE, 
	A.SUMDETALLEPCK_SUSTITUTO,
	A.SUMAPCK_NO_SUSTITUTO,
	PMM_BOLETAS.NCOMPROBANTE, 
	A.FECHA_COMPRA,
	C.NOMBRES, 
	C.CELULAR,
	C.CORREO,
	PMM_BOLETAS.MMONTO
HAVING (CONVERT(FLOAT, A.SUMAPCK_NO_SUSTITUTO)/CONVERT(FLOAT, A.SUMDETALLE)) >= 1


OC_estados_folios_f12_qa -> 177 fecha entrega de viaje
CL_DS_CABECESA_PEDIDOS -> 104