SELECT 
	NOM_PRODUCTO, 
	SKU, 
	NOM_LOCAL, 
	COD_LOCAL, 
	SUBDEP, 
	CLASE, 
	SUBCLASE, 
	COD_PROV, 
	NOM_PROV, 
	RUT, 
	MARCA, 
	METOD_ABAST, 
	NUM_OH_VALORIZADO, 
	NUM_VTA_SEM_X_PERFIL, 
	VTA_PERDIDA_VP, 
	CANTIDAD_SKUS, 
	DEMANDA_SEMANAL, 
	FECHA_ACTUALIZ
FROM dbo.CE_INSTOCK
WHERE 
	SUBDEP LIKE '%J04%'
	AND SKU IN (SELECT SKU FROM dbo.INSTOCK_FFVV_LISTA_SKU)