/* View_NUEVO_INSTOCK_TABLA_DIA_LOCAL
 * Updated_by: Sebastian E Cornejo B
 * Updated_at: 2019/12/23
 * Cambios: 
 *	-> Se modifican Filtros de J02 y J05
 */

SELECT 
	COD_LOCAL,
	CONVERT(DATE, FECHA_ACTUALIZ) AS FECHA_ACTUALIZ,
	'COMPAÑÍA' AS [Cuadro Resumen],
	CONVERT(NUMERIC(12, 1), SUM([NUM_OH_VALORIZADO]) / NULLIF (SUM([NUM_VTA_SEM_X_PERFIL]), 0) * 100) AS INSTOCK
FROM [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA]
WHERE 
(
	DIVISION IN ('J01 - PGC COMESTIBLE', 'J02 - PGC NO COMESTIBLE', 'J05 - FLC')
	AND SIS_REPOSICION IN ('Reposicion x ASR', 'Informar a ASR')
)
OR (
	DIVISION IN ('J06 - PANADERIA Y PASTELERIA', 'J07 - PLATOS PREPARADOS')
	AND SIS_REPOSICION IN ('Reposicion x ASR')
)
GROUP BY 
	COD_LOCAL, 
	CONVERT(DATE, FECHA_ACTUALIZ)


UNION


SELECT 
	COD_LOCAL, 
	CONVERT(DATE, FECHA_ACTUALIZ) AS FECHA_ACTUALIZ,
	'TOP500' AS [Cuadro Resumen], 
	CONVERT(NUMERIC(12, 1), SUM([NUM_OH_VALORIZADO]) / NULLIF (SUM([NUM_VTA_SEM_X_PERFIL]), 0) * 100) AS INSTOCK
FROM [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA]
WHERE TOP_500 = 'TOP500'
GROUP BY 
	COD_LOCAL, 
	CONVERT(DATE, FECHA_ACTUALIZ)


UNION


SELECT 
	COD_LOCAL, 
	CONVERT(DATE, FECHA_ACTUALIZ) AS FECHA_ACTUALIZ, 
	'TOP2100' AS [Cuadro Resumen], 
	CONVERT(NUMERIC(12, 1), SUM([NUM_OH_VALORIZADO]) / NULLIF (SUM([NUM_VTA_SEM_X_PERFIL]), 0) * 100) AS INSTOCK
FROM [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA]
WHERE TOP_2100 = 'TOP2100'
GROUP BY 
	COD_LOCAL, 
	CONVERT(DATE, FECHA_ACTUALIZ)


UNION


SELECT 
	COD_LOCAL,
	CONVERT(DATE, FECHA_ACTUALIZ) AS FECHA_ACTUALIZ,
	'PGC' AS [Cuadro Resumen], CONVERT(NUMERIC(12, 1), SUM([NUM_OH_VALORIZADO]) / NULLIF (SUM([NUM_VTA_SEM_X_PERFIL]), 0) * 100) AS INSTOCK
FROM [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA]
WHERE 
(
	DIVISION IN ('J01 - PGC COMESTIBLE', 'J02 - PGC NO COMESTIBLE') 
	AND SIS_REPOSICION IN ('Reposicion x ASR', 'Informar a ASR')
)
GROUP BY 
	COD_LOCAL, 
	CONVERT(DATE, FECHA_ACTUALIZ)


UNION


SELECT 
	COD_LOCAL, 
	CONVERT(DATE, FECHA_ACTUALIZ) AS FECHA_ACTUALIZ, 
	'PERECIBLES' AS [Cuadro Resumen], 
	CONVERT(NUMERIC(12, 1), SUM([NUM_OH_VALORIZADO]) / NULLIF (SUM([NUM_VTA_SEM_X_PERFIL]), 0) * 100) AS INSTOCK
FROM [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA]
WHERE (
	DIVISION IN ('J06 - PANADERIA Y PASTELERIA', 'J07 - PLATOS PREPARADOS') 
	AND SIS_REPOSICION IN ('Reposicion x ASR')
) 
OR (
	DIVISION IN ('J05 - FLC') 
	AND SIS_REPOSICION IN ('Reposicion x ASR', 'Informar a ASR')
)
GROUP BY 
	COD_LOCAL, 
	CONVERT(DATE, FECHA_ACTUALIZ)


UNION


SELECT 
	COD_LOCAL, 
	CONVERT(DATE, FECHA_ACTUALIZ) AS FECHA_ACTUALIZ, 
	'MMPP' AS [Cuadro Resumen], CONVERT(NUMERIC(12, 1), SUM([NUM_OH_VALORIZADO]) / NULLIF (SUM([NUM_VTA_SEM_X_PERFIL]), 0) * 100) AS INSTOCK
FROM [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA]
WHERE MMPP = 'MMPP'
GROUP BY 
COD_LOCAL, 
CONVERT(DATE, FECHA_ACTUALIZ)


UNION


SELECT 
	COD_LOCAL,
	CONVERT(DATE, FECHA_ACTUALIZ) AS FECHA_ACTUALIZ, 
	'IMPORTADOS' AS [Cuadro Resumen], 
	CONVERT(NUMERIC(12, 1), SUM([NUM_OH_VALORIZADO]) / NULLIF (SUM([NUM_VTA_SEM_X_PERFIL]), 0) * 100) AS INSTOCK
FROM [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA]
WHERE PROCEDENCIA = 'IMPORTADO'
GROUP BY 
	COD_LOCAL, 
	CONVERT(DATE, FECHA_ACTUALIZ)