/*-- ?? SELECT * FROM [INFORMES3].[dbo].[View_INSTOCK_SEMANA_NUEVO_ABC]
 * Updated_by: Sebastian E Cornejo B
 * Updated_at: 2019/12/23
 * Cambios: 
 *	-> Se cruza con tabla TIENDAS_ASENTADAS para filtrar por tiendas cerradas
 *	-> Se genera una nueva vista con una sola consutla
 *	-> Se actualizan filtros J02 y J05
 */


SELECT 
	SEMANA,
	[CUADRO_RESUMEN],
	SUM(NUM_OH_VALORIZADO) / SUM(NUM_VTA_SEM_X_PERFIL)*100 AS INSTOCK
FROM (

	SELECT
		SEMANA,
		NUM_OH_VALORIZADO,
		NUM_VTA_SEM_X_PERFIL,
		[CUADRO_RESUMEN],
		FILTRO
	FROM (

		SELECT 
			SEMANA,
			SUM([NUM_OH_VALORIZADO]) NUM_OH_VALORIZADO,
			SUM([NUM_VTA_SEM_X_PERFIL]) NUM_VTA_SEM_X_PERFIL,
			CASE WHEN COD_CLASIFICACION_SKU = 'A' THEN 1 END [CLASE_A],
			CASE WHEN COD_CLASIFICACION_SKU = 'B' THEN 1 END [CLASE_B],
			CASE WHEN COD_CLASIFICACION_SKU = 'C' THEN 1 END [CLASE_C],
			CASE WHEN NUEVO_ABC = 'A' THEN 1 END [NUEVA_CLASE_A],
			CASE WHEN NUEVO_ABC = 'B' THEN 1 END [NUEVA_CLASE_B],
			CASE WHEN NUEVO_ABC = 'C' THEN 1 END [NUEVA_CLASE_C]
		FROM [INFORMES3].[dbo].[INSTOCK_NUEVA_PLANILLA_HISTORIA] I
		LEFT JOIN [INFORMES3].[dbo].[TIENDAS_ASENTADAS_HISTORIA] T
			ON I.COD_LOCAL = T.COD_LOCAL
			AND I.FECHA_ACTUALIZ = T.FECHA
		WHERE 
			SEMANA = DATEPART(WW, GETDATE()) - 1 + DATEPART(YY,GETDATE()) * 100
			AND T.COD_LOCAL IS NULL
			AND (
				(
				DIVISION IN ('J01 - PGC COMESTIBLE', 'J02 - PGC NO COMESTIBLE', 'J05 - FLC')
				AND SIS_REPOSICION IN ('Reposicion x ASR', 'Informar a ASR') 
				) 
				OR (
					DIVISION IN ('J06 - PANADERIA Y PASTELERIA', 'J07 - PLATOS PREPARADOS') 
					AND SIS_REPOSICION IN ('Reposicion x ASR')
				)
			)
		GROUP BY 
			SEMANA,
			COD_CLASIFICACION_SKU,
			NUEVO_ABC

	) AS I
	UNPIVOT (
		FILTRO FOR [CUADRO_RESUMEN] IN (
			[CLASE_A],
			[CLASE_B],
			[CLASE_C],
			[NUEVA_CLASE_A],
			[NUEVA_CLASE_B],
			[NUEVA_CLASE_C]
		)
	) upvtable

) AS I
GROUP BY
	SEMANA,
	[CUADRO_RESUMEN]



