
TRUNCATE TABLE [PronosticosVentas].[dbo].[FACTOR_VNP]
INSERT INTO [PronosticosVentas].[dbo].[FACTOR_VNP]

SELECT 
	[PICKING_CENTER]
	,[COD_LOCAL]
	,V.[DIVISION]
	,(SUM([UNIDADES_VENTA]) / VTA_TOTAL) FACTOR
FROM [10.195.254.201].[TIENDA_GRIS].[dbo].[VENTA_VNP_DIARIA] V
LEFT JOIN (
	SELECT 
		[DIVISION],
		SUM([UNIDADES_VENTA]) [VTA_TOTAL] 
	FROM [10.195.254.201].[TIENDA_GRIS].[dbo].[VENTA_VNP_DIARIA]
	WHERE ID_DIAANALISIS > CONVERT(DATE, GETDATE() - 7)
	GROUP BY [DIVISION]
) VT
	ON VT.[DIVISION] = V.[DIVISION]
WHERE ID_DIAANALISIS > CONVERT(DATE, GETDATE() - 7)
GROUP BY 
	[PICKING_CENTER]
	,[COD_LOCAL]
	,V.[DIVISION]
	,VTA_TOTAL